### ISSUE TITLE
Multiple lineups

### ISSUE THREAD

**Issue by sansbacon** [DimaKudosh/pydfs-lineup-optimizer#1]
There should be an option to have multiple lineups.

If you have a constraint called max_points, set it to some large number initially, then in a loop where you generate lineups set max_points = solution - very small amount, say .001. You will then generate a different lineup each time through the loop. something like this . . . 

    def n_lineups(n):
        max_points = 1000
        for idx in range(n):
            pts_cap = constraint(0, maxpts)
            maxpts = solution_points - .001

**Comment by DimaKudosh** [comment]
I added support for creating many lineups.
