### ISSUE TITLE
Trying To Avoid Hitters vs Pitchers In Same Lineup

### ISSUE THREAD

**Issue by ravashjalil** [DimaKudosh/pydfs-lineup-optimizer#101]
So my understanding is when using the restrict positions for opposing teams method it should not have hitters and the opposing team pitcher in the same lineups.

`optimizer.restrict_positions_for_opposing_team(['P'], ['1B', '2B', '3B', 'C', 'SS', 'OF'])`

I noticed this works sometimes and sometimes it doesn't.  You can test it how I did by taking the salaries for a 2 game slate, run the optimizer, see which pitcher it likes.  Then find an opposing team hitter and edit his projection to something high like 100, then run it again.  The optimizer will pick the same pitchers but add that hitter as well.

**Comment by geoffstrong55** [comment]
I had the same problem. My solution was to change from 'P' to 'SP' because that it is formatted in the CSV.  It should work after that.

**Comment by ravashjalil** [comment]
> I had the same problem. My solution was to change from 'P' to 'SP' because that it is formatted in the CSV. It should work after that.

I appreciate the help, unfortunately it still doesn't work. Thanks anyways.

**Comment by austinjohnson** [comment]
Can you post a picture of you csv and code? This issue was resolved with the last release. @ravashjalil
