### ISSUE TITLE
Error: RB is incorrect position name

### ISSUE THREAD

**Issue by brettdewoody** [DimaKudosh/pydfs-lineup-optimizer#104]
I'm trying to use the `set_players_with_same_position` method to ensure 2 RBs are used, with:

```
optimizer.set_players_with_same_position({'RB': 2})
```

where:

```
optimizer =  get_optimizer(Site.DRAFTKINGS_CAPTAIN_MODE, Sport.FOOTBALL)
```

But am getting the following error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pydfs_lineup_optimizer/lineup_optimizer.py", line 319, in set_players_with_same_position
    self._check_position_constraint(pos)
  File "/Library/Python/2.7/site-packages/pydfs_lineup_optimizer/lineup_optimizer.py", line 515, in _check_position_constraint
    raise LineupOptimizerIncorrectPositionName('%s is incorrect position name.' % position)
pydfs_lineup_optimizer.exceptions.LineupOptimizerIncorrectPositionName: RB is incorrect position name.
```

Does this method work in `DRAFTKINGS_CAPTAIN_MODE`? Or am I really using the wrong position name?

**Comment by brettdewoody** [comment]
Looking at the [src](https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/7f3ceb53fa07eb36c9a7b270d9a4583b7b0634fa/pydfs_lineup_optimizer/sites/draftkings/captain_mode/settings.py) it appears in `DRAFTKINGS_CAPTAIN_MODE` the only option is to select `CAPT` or `FLEX`. 

I think this answers my question, but will leave this open for today to see if anyone has ideas. 

For example, I would like to optimize for 2 RBs on a team, or 1RB, 1WR, etc.

**Comment by DimaKudosh** [comment]
In draftkings captian mode players have 2 positions (CPT and FLEX) as you mentioned earlier, so this rules don't work with normal positions, because we don't store it for player. Right now it is not possible to do what you want, I'll look how we can fix it later, so I keep this issue open. But I'm not sure when I'll do it, because I already have a lot of open issues with bugs/enhacements and haven't time to close them.

**Comment by brettdewoody** [comment]
Nice, it would be a useful addition. I was thinking how it could be done, maybe by using position names of `CPT-RB`, `FLEX-RB`, `FLEX-WR`, etc. Or splitting position and role, where role is `CPT` or `FLEX`, and position is the actual position. This will require additional changes I know, just thinking through it.

**Comment by sansbacon** [comment]
In captain mode, there are so few RBs available, that you can just run the optimizer a few times and lock in different combinations.

```
# step one: get the ids of the playable RBs (my guess it is between 2-5 players)
playable_rbs = . . . 
rb_ids = [p.id for p in playable_rbs]

# step two: iterate through combinations and generate lineups
from itertools import combinations

n = 10
lineups = []

for rb1_id, rb2_id in combinations(rb_ids, 2):
    rb1 = optimizer.get_player_by_id(rb1_id)
    optimizer.add_player_to_lineup(rb1)
    rb2 = optimizer.get_player_by_id(rb2_id)
    optimizer.add_player_to_lineup(rb2)
    for lineup in optimizer.optimize(n, randomize=True):
        lineups.append(lineup)
    optimizer.remove_player_from_lineup(rb1)
    optimizer.remove_player_from_lineup(rb2)

for lineup in lineups:
    print(lineup)  

```

**Comment by sansbacon** [comment]
I think you can close this.
