### ISSUE TITLE
Is there a way to accept a list of groups?

### ISSUE THREAD

**Issue by BenikaH** [DimaKudosh/pydfs-lineup-optimizer#105]
I want to know is there a way to pass in groups of players that may not be on the same team. For instance, if I want to group Christian McCaffrey and Dalvin Cook and do another group with Matt Ryan, Hooper and Ridley. I want to optimize with both of those groups but not necessarily in the same lineup. Give me all optimal lineups for all groups I pass to the optimizer. Ex. one lineup may have Matt Ryan, Fournette, McCoy, Ridley, Landry, Tate, Hooper, Zeke and Steelers and another lineup may have Dak, McCaffrey, Cook, Beckham, Shepard, Boyd, Zeke and Bucs. Is this functionality available?

**Comment by sansbacon** [comment]
Do you want to specify the groups ahead of time or randomly assign the groups from a pool?

If you specify the groups ahead of time, it would look something like this:

```
lineups = []

player_groups = [['Christian McCaffrey', 'Dalvin Cook'], ['Matt Ryan', 'Austin Hooper', 'Calvin Ridley']]

n = 10

for group in player_groups:
    for player_name in group:
        optimizer.add_player_to_lineup(optimizer.get_player_by_name(player_name))
    for lineup in optimizer.optimize(n, randomize=True):
        lineups.append(lineup)
    for player_name in group:
        optimizer.remove_player_from_lineup(optimizer.get_player_by_name(player_name))

for lineup in lineups:
    print(lineup)
```

Do you want to specify the groups ahead of time or randomly assign the groups from a pool?

If you want to randomize the groups, it would look something like this:

```
from itertools import combinations
import random

lineups = []
players = ['Christian McCaffrey', 'Dalvin Cook', 'Matt Ryan', 'Austin Hooper', 'Calvin Ridley']
n_iterations = 10
n_combos = 10

combinations = list(combinations(players, 2)) + list(combinations(players, 3)) 

for combo in random.sample(combinations, n_combos):
    for player_name in combo:
        optimizer.add_player_to_lineup(optimizer.get_player_by_name(player_name))
    for lineup in optimizer.optimize(n, randomize=True):
        lineups.append(lineup)
    for player_name in combo:
        optimizer.remove_player_from_lineup(optimizer.get_player_by_name(player_name))

for lineup in lineups:
    print(lineup)
```

**Comment by BenikaH** [comment]
@sansbacon Yes, this is exactly what I was looking to do. At the moment I was only getting one big group which is not the expected result. Thanks so much. I can close this question.

**Comment by Denwen12** [comment]
Hey @sansbacon I like @BenikaH idea there ultimately can we change that out for a position stack combos?

**Comment by BenikaH** [comment]
I would think you could. What are you thinking?
