### ISSUE TITLE
Unhandled exception in pulp_solver.py

### ISSUE THREAD

**Issue by utahman** [DimaKudosh/pydfs-lineup-optimizer#108]
Instead of:

                if round(variable.value()) == 1.0:
                    result.append(variable)

Must be:
                try:
                    if variable.name != '__dummy' and round(variable.value()) == 1.0:
                        result.append(variable)
                except Exception as e:
                    print("exception:", e)

**Comment by DimaKudosh** [comment]
Hi, how did you get this exception?

**Comment by utahman** [comment]
I think it was when all players were locked due to all games being started. It's a legit situation.
