### ISSUE TITLE
Unable to build lineup from optimizer result

### ISSUE THREAD

**Issue by ravashjalil** [DimaKudosh/pydfs-lineup-optimizer#11]
Hello, been a long time follower of your app.

Back with the older version, I was able to create tons of lineups, well over 500 but with this newer version, depending on the player projections, once I get to about 20 lineups i get the "Unable to build lineup from optimizer result" error.

Ive tried messing with it but i couldnt get it to work, so i went back to the older version.  However I love how this is newer version is organized in a way we can easily upload projections.

**Comment by DimaKudosh** [comment]
Hello, I can't reproduce your error. Can you provide more info about sport and site that you use? Also if you import players via csv file can you send it to my email (you can find it in my github account)? Probably I missed some use case or site rule changing.

**Comment by ravashjalil** [comment]
Thanks for the quick response.

So I was using Draftkings and it was NBA.  I just loaded up todays Salaries to test it again and it couldnt get to 10 lineups without the error.

**Comment by DimaKudosh** [comment]
Fixed this bug in 1.2.1
