### ISSUE TITLE
Way to Get Min/Max to Work on Same Player?

### ISSUE THREAD

**Issue by Cugr** [DimaKudosh/pydfs-lineup-optimizer#110]
Just testing a few things out and I am unable to use min/max on the same player (example below). Is there a way to do this?

from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter

optimizer = get_optimizer(Site.FANDUEL, Sport.FOOTBALL)
optimizer.load_players_from_csv(r"C:\Users\cugr7\Desktop\FanDuel.csv")
lineup_generator = optimizer.optimize(10)
optimizer.set_positions_for_same_team(['QB', 'WR'])
prescott = optimizer.get_player_by_name('Dak Prescott')
prescott.min_exposure = 0.2
prescott = optimizer.get_player_by_name('Dak Prescott')
prescott.max_exposure = 0.3
for lineup in lineup_generator:
    print(lineup)

**Comment by DimaKudosh** [comment]
Hi, Could you provide more information about your problem?

**Comment by Cugr** [comment]
Hi Dima,
The issue will arise when trying to use the min/max feature on more than one player. I have attached a screenshot (the error is below). If I use it on McCaffrey (I changed the FFPG to 1 to make it stand out) alone, it works fine. If I try to do it on a second player, it throws the error. Also, when trying to use a mixture of Min on some players and Max on others, it will throw an error. Thanks!
![example](https://user-images.githubusercontent.com/56055652/68125595-eb476e80-fedf-11e9-84a0-0784bf118de2.jpg)
---------------------------------------------------------------------------
SolverException                           Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in optimize(self, n, max_exposure, randomness, with_injured)
    434             try:
--> 435                 solved_variables = solver.solve()
    436                 lineup_players = []

~\Anaconda3\lib\site-packages\pydfs_lineup_optimizer\solvers\pulp_solver.py in solve(self)
     51         else:
---> 52             raise SolverException('Unable to solve')

SolverException: Unable to solve

During handling of the above exception, another exception occurred:

LineupOptimizerException                  Traceback (most recent call last)
<ipython-input-4-0284d947f62f> in <module>
      8 optimizer.set_max_repeating_players(7)
      9 
---> 10 for lineup in lineup_generator:
     11     print(lineup)

~\Anaconda3\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in optimize(self, n, max_exposure, randomness, with_injured)
    445                     return
    446             except SolverException:
--> 447                 raise LineupOptimizerException('Can\'t generate lineups')
    448 
    449     def optimize_lineups(self, lineups):

LineupOptimizerException: Can't generate lineups

**Comment by bigboyz** [comment]
I get the same error.  To detail further, I can use min/max on more than one player as long as they don't share the same position.  If I wanted to set a min_exposure of 10% to Tom Brady it works.  If I try and set a min_exposure of 10% to Tom Brady and min_exposure of 20% to Lamar Jackson it fails.  <solver unable to solve>

However, if the position is Running Back it works unless I try to set the min_exposure to 3 running backs.  So I believe the error occurs when you are trying to set a min_exposure to more than that allotted players for any given position.  

I haven't been able to find a workaround yet nor does the problem seem to occur with max_exposure.

**Comment by bigboyz** [comment]
I've also noticed that if I have 8 positions to fill and I set the Min Exposure on 9 players to just 10% it will throw an error whether I generate 1 lineup or 100.  This should be easily solved, but it seems like if it can't do it on the first lineup it throws (unable to solve).

**Comment by bigboyz** [comment]
Just following up on this again.  After more testing I believe what causes this problem is the following:

If you are making 20 lineups with a min_exposure of any player to .20 that player will always appear in first 4 lineups.  If your parameters are greater than what can be configured in the first lineup out of 20 it fails and is unable to solve.

Example:
If I choose 9 players with a min_exposure of .10 and create 10 lineups on DraftKings NBA where we only start 8 players it will fail and say unable to solve.  If I choose 4 centers with a .10 min_exposure and create 10 lineups it fails and is unable to solve since it is not possible to put 4 centers in the first lineup.

**Comment by DimaKudosh** [comment]
It was a bug with previous version, I released new version with fix
