### ISSUE TITLE
Single Game FanDuel Basketball

### ISSUE THREAD

**Issue by benTKam** [DimaKudosh/pydfs-lineup-optimizer#113]
Is there anyway to do single game fantasy basketball on FanDuel I can't seem to figure out how to do it if there is.

**Comment by elitwilliams** [comment]
Seconding this request. Please see attached players list and lineup constraints info. Thanks Dima.
<img width="573" alt="Screen Shot 2019-12-25 at 2 10 58 PM" src="https://user-images.githubusercontent.com/2677808/71450944-8d394980-2720-11ea-9568-f3b8b89264b9.png">
[FanDuel-NBA-2019-12-25-42036-players-list.csv.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/4000851/FanDuel-NBA-2019-12-25-42036-players-list.csv.zip)

**Comment by DimaKudosh** [comment]
Added in 3.0.0
