### ISSUE TITLE
Issue with Tennis Optimizer

### ISSUE THREAD

**Issue by kahlilgedin** [DimaKudosh/pydfs-lineup-optimizer#114]
![image](https://user-images.githubusercontent.com/21266971/67887143-21bc6c80-fb21-11e9-84ee-3769a76de107.png)
![issue](https://user-images.githubusercontent.com/21266971/67887202-3b5db400-fb21-11e9-92a7-96b7647c7579.png)

Has the tennis optimizer been implemented? I'm having trouble loading it into my script.

**Comment by DimaKudosh** [comment]
Please check your library version, tennis was added in version 2.5.0

**Comment by kahlilgedin** [comment]
I had to remove the older packages and then reinstall it.

Thanks!
