### ISSUE TITLE
Feature request- sort by start time

### ISSUE THREAD

**Issue by kpm1988** [DimaKudosh/pydfs-lineup-optimizer#117]
For sports with a 'Flex' or 'Utility' position, I'd like to automatically sort lineups so that the player with the latest start time is used in the most flexible position.  If a football lineup has 3 RBs (one as flex), I'd like the RB who starts at 4PM to be in 'Flex' rather than one who starts at 1PM.

Thanks again as always!

**Comment by DimaKudosh** [comment]
I added sorting in new version
