### ISSUE TITLE
Partial Line (NHL Feature Request)

### ISSUE THREAD

**Issue by elitwilliams** [DimaKudosh/pydfs-lineup-optimizer#118]
Hi Dima - great work on the latest update. Been enjoying trying the new functionality. 

An idea - it would be helpful to be able to add stacks one at a time, with stacking constraints that only apply to those players. For example, instead of

`
optimizer.set_team_stacking([3, 2], for_positions=['C', 'W'])
optimizer.set_spacing_for_positions(['C', 'W'], 1)
`

something along the lines of:

`
optimizer.add_team_stack(3, for_positions=['C', 'W', 'D', 'G'], spacing=1))
optimizer.add_team_stack(2, for_positions=['C', 'W'], spacing=1))
`

Where the stacking constraints only apply to the stacks as specified, and not to other players in the lineup. That way they would behave independently, and I think it would be clearer for the user what's going on. Also, in the current configuration, if I want to have a 3 stack and a 2 stack, I'm unable to have a 3rd C or W player on the 2 stack who isn't spaced more than 1 position away.

**Comment by asardinha** [comment]
On that same note. Would it be beneficial to create a second roster rule so that you could stack one full line and then one power play line?

**Comment by elitwilliams** [comment]
I'm glad you brought that up! Generally, the power play stacking is done on top of line stacking (and mostly for defensemen). So for example, you might require that any players on a given stack are in power play 1 or 2, or alternatively you might require that any defensemen are on power play 1. And yes, having this additional functionality would definitely be beneficial, although even just a function requiring a given position be on power play would be a great start, e.g.:

```
optimizer.set_power_play_positions(['C', 'W'], [1, 2])
optimizer.set_power_play_positions(['D'], [1])
```

If I can be of further help please let me know!

Separately - a small bug I've noticed in pulp_solver.py lines 47-50, and my workaround, something to do with round() not being able to handle None type values:

Change:

```
for variable in self.prob.variables():
    if round(variable.value()) == 1.0:  
        result.append(variable)  
return result
```

to

```
for variable in self.prob.variables():
    if variable.value() == None:
        pass
    elif round(variable.value()) == 1.0:
        result.append(variable)
return result
```

**Comment by elitwilliams** [comment]
@DimaKudosh any chance you could give a timeline on something like this? Sorry to badger you, and thanks again for the fantastic work thus far.

**Comment by DimaKudosh** [comment]
@elitwilliams I don't have much free time now, I think I'll be able to work on this project only after new year, according to your proposal I'm not familiar with hockey strategies what is a power play? Do we store information about it?

**Comment by elitwilliams** [comment]
Ok sounds good. To be clear, the issue where stacking constraints should only be applied to the players in the stack itself and not to other players in the lineup is the priority, since that is more important than Power Play functionality (please see my previous comment from 12/18, or if you would like additional clarification I would be happy to explain further). I still think the way I described in my 11/6 comment might make the most sense and be clearest for the user - but you are the boss! :)

But regarding Power Play - please see this definition: "In ice hockey, a team is said to be on a power play when at least one opposing player is serving a penalty, and the team has a numerical advantage on the ice (whenever both teams have the same number of players on the ice, there is no power play)."

This is designated similar to Lines, where a given player will be on Power Play 1 or 2 or none. For example, you can see who is on the Anaheim Ducks Power Play Units here: https://www.dailyfaceoff.com/teams/anaheim-ducks/line-combinations/  

Players on a Power Play unit are generally more likely to score a goal since there are more players for their own team on the ice than the opposing team during a Power Play. The way this is implemented in DFS is that you may require, say, your defensemen to be on PP1 since those players would have a higher likelihood of scoring compared to the defensemen who are not on a Power Play unit, thus theoretically increasing the # of points your lineup will score, on average.

I think a straightforward way of implementing this would just be the way I described on 11/6, where you can require players in a given position (in particular, Defensemen) to be on PP1 or PP2.

**Comment by jgabbydfs** [comment]
Not sure if it's possible, but adding two roster order columns could solve it. Spacing of 1 in either the first column OR the second column would force either a line stack or a powerplay stack. Allowing for flexibility for teams to overlap would be ideal.

Example:
Stacking a C, LW, RW from Tampa Bay roster order 1 AND stacking a C, RW, D from Tampa Bay roster order 2.

**Comment by DimaKudosh** [comment]
Added new stacking api in new version
