### ISSUE TITLE
Lineup needs to contain players spanning multiple games.

### ISSUE THREAD

**Issue by utahman** [DimaKudosh/pydfs-lineup-optimizer#119]
Got this error message from DK when try to enter generated NBA Classic lineups:
"Lineup needs to contain players spanning multiple games."
I checked and yes, all players were from two teams of the same game.
It seems that Optimizer needs additional rule to avoid that, right?

**Comment by elitwilliams** [comment]
Yes this is a bug. Change the DK  Basketball settings in /pydfs-lineup-optimizer/pydfs_lineup_optimizer/sites/draftkings/classic/settings.py/ to:
```
@SitesRegistry.register_settings
class DraftKingsBasketballSettings(DraftKingsSettings):
    sport = Sport.BASKETBALL
    min_teams = 3
    positions = [
        LineupPosition('PG', ('PG', )),
        LineupPosition('SG', ('SG', )),
        LineupPosition('SF', ('SF', )),
        LineupPosition('PF', ('PF', )),
        LineupPosition('C', ('C', )),
        LineupPosition('G', ('PG', 'SG')),
        LineupPosition('F', ('SF', 'PF')),
        LineupPosition('UTIL', ('PG', 'SG', 'PF', 'SF', 'C'))
    ]
```
