### ISSUE TITLE
DraftKings Hockey KeyError

### ISSUE THREAD

**Issue by jgabbydfs** [DimaKudosh/pydfs-lineup-optimizer#12]
Dima,

line 7, in <module>
    for lineup in lineup_generator:
line 478, in optimize
    lineup = self._build_lineup(lineup_players)
line 312, in _build_lineup
    players.sort(key=lambda p: (len(p.positions), max([single_positions[pos] for pos in p.positions])))
line 312, in <lambda>
    players.sort(key=lambda p: (len(p.positions), max([single_positions[pos] for pos in p.positions])))
line 312, in <listcomp>
    players.sort(key=lambda p: (len(p.positions), max([single_positions[pos] for pos in p.positions])))
KeyError: 'RW'

This is my code:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer

optimizer = get_optimizer(Site.DRAFTKINGS, Sport.HOCKEY)
optimizer.load_players_from_CSV("DKSalaries.csv")
lineup_generator = optimizer.optimize(10)
for lineup in lineup_generator:
    print(lineup)

This is what's happening when trying to generate DraftKings Hockey lineups using the unmodified DKSalaries.csv sheet. Is there something I need to do differently to get this to work?

**Comment by DimaKudosh** [comment]
Got same error when tested on draftkings nhl. Fixed in 1.2.2
