### ISSUE TITLE
FantasyDraft exporter - wrong player ID

### ISSUE THREAD

**Issue by stratm0s** [DimaKudosh/pydfs-lineup-optimizer#121]
When using the CSVLineupExporter for fantasydraft lineup, the exporter spits out IDs that are only 1 to 3 digits long instead of the 7 digit ID in the player information sheet.

```
from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter

optimizer = get_optimizer(Site.FANTASY_DRAFT, Sport.BASKETBALL)
optimizer.load_players_from_csv("nba.csv")
optimizer.set_max_repeating_players(3)
exporter = CSVLineupExporter(optimizer.optimize(60, max_exposure=0.35, randomness=True))
exporter.export('result.csv', lambda p: p.id)

```

**Comment by DimaKudosh** [comment]
FantasyDraft was added in library before they had implemented import lineups feature, so it works only with files downloaded from contest page where ids for players aren't presented. Now you can export players from lineups page where exported file has ids, so for correct export this file from lineups page should be used. Library doesn't support parsing of this type of file for now, I'll add it in next release.

**Comment by str4tm0s** [comment]
Sounds good. Thanks for the reply.

**Comment by DimaKudosh** [comment]
I added export for fantasy draft in new version because fantasy draft export differs from fd or dk I added separate exporter:
```
filename = 'players.csv'
optimizer.load_players_from_csv(filename)
FantasyDraftCSVLineupExporter(optimizer.optimize(10)).export(filename)
```
note that  export filename and import should be the same
