### ISSUE TITLE
trying to use glpk

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#122]
i cant get glpk to solve, Maybe im starting it wrong 

import pulp
from pulp.solvers import GLPK_CMD
from pydfs_lineup_optimizer import get_optimizer, Site, Sport
from pydfs_lineup_optimizer.solvers.pulp_solver import PuLPSolver

class GLPK_CMDSolver(PuLPSolver):
    LP_SOLVER = GLPK_CMD

optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL, solver=GLPK_CMDSolver)

**Comment by DimaKudosh** [comment]
I think your solver class should look like this:
```
class GLPK_CMDSolver(PuLPSolver):
    LP_SOLVER = GLPK_CMD()  # or GLPK_CMD(msg=0) if you don't want to print messages from glpk
```
I've just tried to run it with glpk and it seems that glpk can return None instead of 0 in some cases, so you also should override solve method like this:
```
from pulp import LpStatusOptimal
from pydfs_lineup_optimizer.solvers.exceptions import SolverException

class GLPK_CMDSolver(PuLPSolver):
    LP_SOLVER = GLPK_CMD(msg=0)
    
    def solve(self):
        self.prob.solve(self.LP_SOLVER)
        if self.prob.status == LpStatusOptimal:
            result = []
            for variable in self.prob.variables():
                val = variable.value()
                if val is not None and round(val) == 1.0:
                    result.append(variable)
            return result
        else:
            raise SolverException('Unable to solve')

```
I'll fix it in next release but you can use it for now
