### ISSUE TITLE
Bug NHL set_total_teams

### ISSUE THREAD

**Issue by mikebencho** [DimaKudosh/pydfs-lineup-optimizer#123]
For Draftkings NHL the requirement for total teams is that you need to have 3 separate teams for skaters. Goalie is excluded from that requriement

so when using the rule optimizer.set_total_teams(3)

the C, W and D positions have to include three different teams. 

Currently they are allowed to be two different teams and then the goalie makes three, which is not a valid lineup. Thanks

**Comment by DimaKudosh** [comment]
Fixed in new version
