### ISSUE TITLE
confirmed starters

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#124]
I like to see if you can add a way to put confirmed starters for a column in csv and we can put a "Y for yes" and generate lines like that, and or other commands like to tell it to generate lines with at least 5 confirmed starters if I want

**Comment by kpm1988** [comment]
Are you using ownership projections to create your lineups? If not, you could set 'Projected Ownership' to 1 for all confirmed starters, and then use the constraint: 'set_projected_ownership(min_projected_ownership=0.5)'.

If you're already using projected ownership it's a little bit of work in Python to copy the 'Projected Ownership' code in importer, player, lineup, and constraints; but something I've been able to accomplish with limited coding skills.  I'm sure Dima's solution would be far more elegant than mine.

**Comment by Denwen12** [comment]
that seem like it may work but I also like to set a rule to tell it to use at least a set amount of starters

**Comment by DimaKudosh** [comment]
I'll add this feature in next release

**Comment by Denwen12** [comment]
thanks it would be great to use starters only and a certain amount

**Comment by Denwen12** [comment]
i tryed to use your way to try to use this now but i cant get that too work\optimizer.load_players_from_csv("/root/Downloads/players-list.csv")
for player in optimizer.players:
    if player.efficiency == 0:
        optimizer.remove_player(player)
for player in optimizer.players:
    player.projected_ownership = get_projected_ownership(player)

optimizer.set_teams_max_exposure({team: 0.16 for team in optimizer.available_teams})
optimizer.set_projected_ownership(min_projected_ownership=0.5)
optimizer.set_max_repeating_players(3)
lineups = list(optimizer.optimize(n=5))
for lineup in lineups:
    print(lineup)

then i get 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'get_projected_ownership' is not defined
>>>

**Comment by DimaKudosh** [comment]
Added this feature in new release
