### ISSUE TITLE
Feature Request:  Player Groupings

### ISSUE THREAD

**Issue by mywebpower** [DimaKudosh/pydfs-lineup-optimizer#129]
Could you possibly add a new feature for Player Grouping.

Example:  
# ensure in same lineup
player = optimizer.get_player_by_name('Lebron James')
player2 = optimizer.get_player_by_name('Anthony Davis')

optimizer.set_player_group([ player, player2 ])

# ensure not in same lineup
player = optimizer.get_player_by_name('Lebron James')
player2 = optimizer.get_player_by_name('Anthony Davis')

optimizer.set_player_ungroup([ player, player2 ])

Probably asking too much to have the ability to have multiple groups but that would be pretty sweet.

**Comment by DimaKudosh** [comment]
I changed stacking functionality in new version [here](https://pydfs-lineup-optimizer.readthedocs.io/en/latest/rules.html#group-players) you can find how to group players
