### ISSUE TITLE
Set min total salary

### ISSUE THREAD

**Issue by Sirius1015** [DimaKudosh/pydfs-lineup-optimizer#13]
How can I set salary constraint on the lineup optimizer? e, g. I want to set a min total salary to be $59900 for all lineups in fanduel. Thanks for the help.

**Comment by DimaKudosh** [comment]
Added min salary constraint in 1.4. You can set it using `lineup_optimizer.set_min_salary_cap(min_salary_cap)` method

**Comment by Sirius1015** [comment]
I keep on getting this error:

AttributeError: 'LineupOptimizer' object has no attribute 'set_min_salary_cap'

**Comment by DimaKudosh** [comment]
Did you update library?

**Comment by Sirius1015** [comment]
Yes, I did an upgrade.

pip install pydfs-lineup-optimizer --upgrade

**Comment by DimaKudosh** [comment]
Can you run this code in console.
```
import pydfs_lineup_optimizer
print(pydfs_lineup_optimizer.__version__)
```
It must print 1.4.0 in console if not try to update package again.

**Comment by Sirius1015** [comment]
Output version shows 1.4.0

import pydfs_lineup_optimizer
print(pydfs_lineup_optimizer.__version__)

out:  1.4.0
