### ISSUE TITLE
Still having trouble uploading lineups from exported csv to FanDuel

### ISSUE THREAD

**Issue by BenikaH** [DimaKudosh/pydfs-lineup-optimizer#131]
Was the FanDuel ID format changed in the CSVLineupExporter in 2.7.0? 
Still can't upload the lineups generated using 2.7. Gives an Invalid entry error. 

I'm thinking its because the ID is no longer Name(ID) but it is now ID:Name. Any thoughts here?

**Comment by Denwen12** [comment]
how does your export look?

**Comment by BenikaH** [comment]
[nba-rand-1.xlsx](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/4068092/nba-rand-1.xlsx)

**Comment by BenikaH** [comment]
The players are printed like this; 

Trae Young(42351-84671)

Is yours that way as well?

**Comment by Denwen12** [comment]
can I see the code your using to print

**Comment by BenikaH** [comment]
`for lineup in lineups:
    print(lineup)
    
exporter = CSVLineupExporter(lineups)
exporter.export('/Users/BH/Downloads/nba-rand-1.csv')
`

**Comment by Denwen12** [comment]
for lineup in lineups:
print(lineup)
exporter = CSVLineupExporter(lineups)
exporter.export('/Users/BH/Downloads/nba-rand-1.csv', lambda p: p.id)

Try that and let me know if that worked

**Comment by BenikaH** [comment]
Ok I’ll try when I get home. Yours doesn’t export that way?

**Comment by Denwen12** [comment]
no mine just exports id

**Comment by BenikaH** [comment]
No, that gives an error. 
`TypeError: __init__() takes 2 positional arguments but 3 were given`

**Comment by Denwen12** [comment]
exporter.export('/Users/BH/Downloads/nba-rand-1.csv', p.id)

see what that does

**Comment by Denwen12** [comment]
I'll check mine at home in an hour for you

**Comment by BenikaH** [comment]
That is odd.

**Comment by Denwen12** [comment]
what is odd?

**Comment by Denwen12** [comment]
i noticed you had a question about grouping players but i cant seem to get that right... Have you and gotten that to work?

**Comment by BenikaH** [comment]
Oh, its odd that its printing the names at all. Maybe because I'm getting the players by name. Sure, go to this post, Sansbacon offered a great solution for the two scenarios I wanted.
https://github.com/DimaKudosh/pydfs-lineup-optimizer/issues/105#issuecomment-540873508

**Comment by Denwen12** [comment]
i tryed adding the code but its not working for me

**Comment by BenikaH** [comment]
`from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
optimizer.load_players_from_csv('/Users/bc/Downloads/DKSalaries (8).csv')

#optimizer.set_team_stacking([2,2])
optimizer.set_teams_max_exposure({team: 0.45 for team in optimizer.available_teams})
#optimizer.set_min_salary_cap(49000)
optimizer.set_max_repeating_players(5)
#optimizer.remove_player_from_lineup(optimizer.get_player_by_name('Davante Adams'))
lineups=[]

# make a list of list of desired combinations
player_groups = [['James Harden', 'C.J. McCollum','Hassan Whiteside' ], ['James Harden','Russell Westbrook', 'Derrick Favors']]#,['Lou Williams','Jayson Tatum', 'Montrezl Harrell']]
n = 20

for group in player_groups:
    for player_name in group:
        optimizer.add_player_to_lineup(optimizer.get_player_by_name(player_name))
    for lineup in optimizer.optimize(n, randomness=True):
        lineups.append(lineup)
    for player_name in group:
        optimizer.remove_player_from_lineup(optimizer.get_player_by_name(player_name))

for lineup in lineups:
    print(lineup)
    
    
    
exporter = CSVLineupExporter(lineups)`

**Comment by Denwen12** [comment]
how does your python code look when you run it, i tryed all kinds of ways to  use that

**Comment by BenikaH** [comment]
Try that above. I started with NFL and then used the same approach with NBA.

**Comment by Denwen12** [comment]
okay testing now

**Comment by Denwen12** [comment]
seems to not like me

**Comment by BenikaH** [comment]
Now, that I'm thinking about it. It may be because I'm getting the player by the name and printing it that way. I'll have to adjust it then because FD does not like it the way it prints out.

**Comment by BenikaH** [comment]
That's because of the code marks.
`
from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
optimizer.load_players_from_csv('/Users/bc/Downloads/DKSalaries (8).csv')

#optimizer.set_team_stacking([2,2])
optimizer.set_teams_max_exposure({team: 0.45 for team in optimizer.available_teams})
#optimizer.set_min_salary_cap(49000)
optimizer.set_max_repeating_players(5)
#optimizer.remove_player_from_lineup(optimizer.get_player_by_name('Davante Adams'))
lineups=[]

# make a list of list of desired combinations
player_groups = [['James Harden', 'C.J. McCollum','Hassan Whiteside' ], ['James Harden','Russell Westbrook', 'Derrick Favors']]#,['Lou Williams','Jayson Tatum', 'Montrezl Harrell']]
n = 20

for group in player_groups:
    for player_name in group:
        optimizer.add_player_to_lineup(optimizer.get_player_by_name(player_name))
    for lineup in optimizer.optimize(n, randomness=True):
        lineups.append(lineup)
    for player_name in group:
        optimizer.remove_player_from_lineup(optimizer.get_player_by_name(player_name))

for lineup in lineups:
    print(lineup)
    
    
    
exporter = CSVLineupExporter(lineups)

`

**Comment by Denwen12** [comment]
i must of gotten something to work but now i get

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pydfs_lineup_optimizer/lineup_optimizer.py", line 305, in remove_player_from_lineup
    self._lineup.remove(player)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Fanduel.py", line 31, in <module>
    optimizer.remove_player_from_lineup(optimizer.get_player_by_name(player_name))
  File "/usr/local/lib/python3.7/dist-packages/pydfs_lineup_optimizer/lineup_optimizer.py", line 307, in remove_player_from_lineup
    raise LineupOptimizerException('Player not in line up!')
pydfs_lineup_optimizer.exceptions.LineupOptimizerException: Player not in line up!
root@localhost:~#

**Comment by BenikaH** [comment]
Check the player groups you have and the csv you're using. Make sure the player is there in the csv.

**Comment by Denwen12** [comment]
can you check over the python script? i have the guys in the import file

import pulp
from pulp.solvers import COIN_CMD
from pydfs_lineup_optimizer import get_optimizer, Site, Sport,CSVLineupExporter
from pydfs_lineup_optimizer.solvers.pulp_solver import PuLPSolver
import time

start_time = time.time()

class COIN_CMDSolver(PuLPSolver):
    LP_SOLVER = COIN_CMD(msg=0)

optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL, solver=COIN_CMDSolver)
optimizer.load_players_from_csv('/root/Downloads/players-list.csv')

#optimizer.set_team_stacking([2,2])
optimizer.set_teams_max_exposure({team: 0.45 for team in optimizer.available_teams})
#optimizer.set_min_salary_cap(59000)
#optimizer.set_max_repeating_players(5)
#optimizer.remove_player_from_lineup(optimizer.get_player_by_name('Davante Adams'))


player_groups = [['John Collins', 'Trae Young','Cam Reddish' ], ['Tristan Thompson','Kevin Love', 'Collin Sexton'],['Dwight Powell','Luka Doncic', 'Tim Hardaway']]
n = 20

for group in player_groups:
	for player_name in group:
		optimizer.add_player_to_lineup(optimizer.get_player_by_name(player_name))
for lineup in optimizer.optimize(n, randomness=True):
	lineups.append(lineup)
	for player_name in group:
		optimizer.remove_player_from_lineup(optimizer.get_player_by_name(player_name))

for lineup in lineups:
	print(lineup)

**Comment by BenikaH** [comment]
Let me check, hold on.

**Comment by Denwen12** [comment]
or i could be thinking this wrong i want groups of players together during optimizing

**Comment by Denwen12** [comment]
i get this now
pydfs_lineup_optimizer.exceptions.LineupOptimizerException: You're already select all C's

**Comment by Denwen12** [comment]
i got it too work, thank you

**Comment by BenikaH** [comment]
Oh yeah, remove one of the Centers and re-run.

**Comment by BenikaH** [comment]
You're thinking of it correctly. I don't have all of the solvers installed so I had to install them.

**Comment by Denwen12** [comment]
finally got it working

**Comment by BenikaH** [comment]
Good. How does your csv look? Name and ID or just IDs?

**Comment by Denwen12** [comment]
PG | PG | SG | SG | SF | SF | PF | PF | C | Budget | FPPG
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
42769-84671 | 42769-84667 | 42769-19067 | 42769-15595 | 42769-110339 | 42769-80809 | 42769-9874 | 42769-66236 | 42769-14501 | 59800 | 297.183
42769-84671 | 42769-84667 | 42769-19067 | 42769-15595 | 42769-110339 | 42769-15904 | 42769-9874 | 42769-66236 | 42769-14501 | 59800 | 293.619

**Comment by Denwen12** [comment]
i am on fanduel by the way

**Comment by Denwen12** [comment]
i can check on draftkings if thats what your useing to make sure

**Comment by Denwen12** [comment]
draftkings sould be like this 

PG | SG | SF | PF | C | G | F | UTIL
-- | -- | -- | -- | -- | -- | -- | --
Donte DiVincenzo (14151787) | Spencer Dinwiddie (14151732) | Khris Middleton (14151721) | Derrick Favors (14151728) | Brook Lopez (14151764) | Kyrie Irving (14151707) | Wilson Chandler (14151841) | Giannis Antetokounmpo (14151692)

**Comment by Denwen12** [comment]
for lineup in lineups:
	print(lineup)
exporter = CSVLineupExporter(lineups)
exporter.export('/root/result.csv', lambda p: p.id)

**Comment by BenikaH** [comment]
Wow, so why is mine doing the Name and ID like that? What line do have for exporter?

**Comment by Denwen12** [comment]
change the directory

**Comment by Denwen12** [comment]
let me know what you get

**Comment by BenikaH** [comment]
Now it works! I must have had an old version cached. I re-installed 2.7.0 and ignored old versions. Then I put in the `lambda p: p.id` and it worked. Before, it would throw a Type error. Thanks.

**Comment by Denwen12** [comment]
your welcome and thanks for the help also

**Comment by BenikaH** [comment]
No problem! I want to ask you about COINMD solver. I'll send outside of this thread.

**Comment by Denwen12** [comment]
anytime
