### ISSUE TITLE
DraftKings Hockey Lineup Export Error

### ISSUE THREAD

**Issue by silentjoe4** [DimaKudosh/pydfs-lineup-optimizer#132]
DraftKings expects the position order for NHL lineups for Classic slates to be 'C,C,W,W,W,D,D,G,UTIL' but the pydfs-lineup-optimizer default order is 'W,W,W,C,C,D,D,G,UTIL'. The Center and Wing positions are reversed.

**Comment by DimaKudosh** [comment]
Fixed in new version
