### ISSUE TITLE
Single Game Fanduel MVP constraint 

### ISSUE THREAD

**Issue by jsst28** [DimaKudosh/pydfs-lineup-optimizer#133]
Is there any way to constrain the pool of players for the MVP position? Essentially, there's generally only 4-6 players you'd want to consider for the MVP slot, but the optimizer considers the entire pool. Any way to limit the MVP slot to a select number of players?

**Comment by Denwen12** [comment]
captain_exposures = {
    'Cam Newton': 0.4,
    'Jamies Winston': 0.3,
    # etc
}
for player_name, max_exposure in captain_exposures.items():
    for player in optimizer.find_players(player_name):
        if 'CPT' in player.positions:
            player.max_exposure = max_exposure
            break



I'm not 100% atm but you can probably edit that code to your linking

**Comment by DimaKudosh** [comment]
You can try to remove some mvp players from optimization:
```
my_mvps = ['Player 1', 'Player 2', 'Player 3']
for player in optimizer.players:
    if player.is_mvp and player.full_name not in my_mvps:
        optimizer.remove_player(player)
```

**Comment by jsst28** [comment]
Thanks Dima! The only other aspect I'd probably want to control for is exposure rates for MVP and the entire pool, but this has really helped.

**Comment by DimaKudosh** [comment]
You can set exposure for each player just set max_exposure attribute of player object to desired value
