### ISSUE TITLE
DraftKings NBA Tiers mode

### ISSUE THREAD

**Issue by utahman** [DimaKudosh/pydfs-lineup-optimizer#134]
Hi Dima. Is it possible to add Tiers mode games?
Six players in lineup. Each picked from individual pool.
It is very similar to Classic games. The only difference is that Positions called Tiers. Any player can be assigned to a specific tier like T1 or T2 etc. instead of position like PG or SG.

NBA Tiers
In Tiers contests, participants will create a lineup by selecting players listed in the Player Pool. Each player listed has an assigned Tier and a valid lineup must include a player from each Tier. The number of Tiers may vary based on the Game Set.

Lineup Requirements
Lineups must consist of one player from each Tier and must include players representing at least 2 different NBA games. The number of Tiers may vary based on the Game Set.

Player Pool
The players in each Tier are chosen by DraftKings.

In most circumstances, once the Player Pool is established for a Game Set, including positions and Tiers, the Player Pool will not be adjusted. In the rare event that there is a mistake within the Player Pool that would significantly impact game quality, DraftKings reserves the right to correct the mistake after contests for that Game Set have become available. This may result in valid lineups becoming invalid. This would most likely occur shortly after the Player Pool becomes available, far in advance of the contest start time, and participants who have entered contests for the Game Set prior to the adjustment will be notified via email.

A "Game Set" is a set of games used for contests; each contest is tied to one Game Set. Contests tied to the same Game Set can be created at different times. Therefore, game policies are based on the timing of a Game Set being made available, not each individual contest.

Position Eligibility
Player positions are determined at the sole discretion of DraftKings.

Lineup Edits
Lineups may be edited at any time leading up to games. Each individual player will become "locked" at the scheduled start time of their team's game. A locked player cannot be added or removed from a roster spot. Locked roster spots for all entries are displayed in contest GameCenters. In the rare case that a game starts before the scheduled start time, all players within that game will become locked as soon as our feed reflects that the game has begun. Additionally, any lineup swaps including players from the game that were made after the real-life start time of the game will result in those lineups being disqualified and refunded.

**Comment by utahman** [comment]
Sample file for today's games
[DKEntries.txt](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/4293988/DKEntries.txt)

**Comment by DimaKudosh** [comment]
Added in version 3.3.0
