### ISSUE TITLE
Opposing Tennis Players

### ISSUE THREAD

**Issue by pippinainteasy** [DimaKudosh/pydfs-lineup-optimizer#138]
I am currently using the `optimizer.restrict_positions_for_opposing_team(['P'], ['P'])` to try and prevent opposing tennis players from showing up in the same lineup but am still getting some. Not sure if I am doing something wrong or if I may need to update supporting requirements.

**Comment by DimaKudosh** [comment]
What site are you using? Check position column in import csv I think you set incorrect positions for this rule

**Comment by pippinainteasy** [comment]
I should have prefaced that by saying it is DraftKings. Looking at the CSV it looks like the `Roster Position` column uses `P` as the player designation. I can upload a CSV if that helps. It looks like it is only doing it one time, at most, in each lineup.

**Comment by DimaKudosh** [comment]
Yes, please upload csv I'll look into it

**Comment by pippinainteasy** [comment]
Thanks for the help. If you can get it to work then it could be that I'm missing a dependency, or something. 

[DK_Tennis.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/4208876/DK_Tennis.zip)

**Comment by DimaKudosh** [comment]
It's bug with parsing team name in DK, I fixed it in develop branch, I'll include it in next release later

**Comment by pippinainteasy** [comment]
Thank you very much!
