### ISSUE TITLE
Spacing for positions last number and first number

### ISSUE THREAD

**Issue by mbencho** [DimaKudosh/pydfs-lineup-optimizer#141]
Ideally the spacing for positions needs to account for going from the last position to the first

for example in baseball,  you may have a roster order of 1,2,3,4,5,6,7,8,9. There needs to be a way to tell the optimizer that 9 and 1 are actually beside each other, they are one spot away the same way that 3 and 4 are one spot away from each other. 

not sure this can be accomplished with the existing code. thanks.

**Comment by elitwilliams** [comment]
Seconding this request. For example, just as (1, 2, 3, 4) is a valid 4-spacing roster order lineup, (8, 9, 1, 2) should also be valid. Thanks Dima.

**Comment by brente33** [comment]
I have looked and looked for how to change this but I can't figure it out. Has anyone been able to do it?

**Comment by DimaKudosh** [comment]
Added cyclic spacing in version  3.3.0
