### ISSUE TITLE
exposures after otimizer runs

### ISSUE THREAD

**Issue by will6809** [DimaKudosh/pydfs-lineup-optimizer#142]
Hello I'm new to python and not sure if I'm asking this question in the write place or not.

How can i get my players exposure amounts after i run say 20 lineups.
This is for DraftKings  NBA

Not sure what code i should be putting in for that.
Thanks

**Comment by austinjohnson** [comment]
I don't think there is a way to do this. If you want player exposure you'll have to set it yourself. @will6809

**Comment by kahlilgedin** [comment]
if you want exposures here is a function to do it. 
![Screen Shot 2020-05-04 at 12 09 24 PM](https://user-images.githubusercontent.com/21266971/80987514-27607b00-8e00-11ea-8058-9c2c11443281.png)

**Comment by Denwen12** [comment]
where would I enter this function cods?

**Comment by Denwen12** [comment]
i can not figure out where to enter this function

**Comment by DimaKudosh** [comment]
In version 3.3.0 I added feature that prints information about players used in optimization to console. After lineups generation, you can call this method `optimizer.print_statistic()`
