### ISSUE TITLE
'TeamStack' not defined

### ISSUE THREAD

**Issue by pippinainteasy** [DimaKudosh/pydfs-lineup-optimizer#144]
I am probably doing something wrong but since going to the new `add_stack` from `set_team_stack` feature I am getting `NameError: name 'TeamStack' is not defined` when trying to make lineups. Below is the code I am using 

`from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter`
`optimizer = get_optimizer(Site.DRAFTKINGS, Sport.HOCKEY)`
`optimizer.load_players_from_csv("DK_NHL.csv")`

`for player in optimizer.players:`
`    if player.efficiency == 0:`
`        optimizer.remove_player(player)`
        

`optimizer.set_max_repeating_players(6)`
`optimizer.restrict_positions_for_same_team(['D', 'D'])`
`optimizer.restrict_positions_for_opposing_team(['G'], ['C', 'LW', 'RW', 'D'])`
`optimizer.add_stack(TeamStack(3, for_positions=['C', 'RW', 'LW', 'D'], max_exposure=0.15))`
`optimizer.set_deviation(0.0, 0.10)`

I am using the most recent depository 3.0.1, if that matters.

**Comment by DimaKudosh** [comment]
Did you import `TeamStack` class? 
```
from pydfs_lineup_optimizer import TeamStack
```

**Comment by pippinainteasy** [comment]
I hadn't, I glossed right over that, thanks for the help with that. Still kind of a newb with python. After doing that, though, i get `ImportError: cannot import name 'TeamStack' from 'pydfs_lineup_optimizer'`.

**Comment by elitwilliams** [comment]
Try

`from pydfs_lineup_optimizer.stacks import TeamStack`

**Comment by pippinainteasy** [comment]
That did it. Thank you, @elitwilliams and @DimaKudosh, for the help!
