### ISSUE TITLE
LOL-fanduel

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#148]
would it be hard to add LOL support because of no sports

**Comment by mikebencho** [comment]
it's already supported optimizer = get_optimizer(Site.DRAFTKINGS_CAPTAIN_MODE, Sport.LEAGUE_OF_LEGENDS)

**Comment by Denwen12** [comment]
what about fanduel?

**Comment by DimaKudosh** [comment]
@Denwen12  Could you provide sample of csv for fd lol?

**Comment by jsst28** [comment]
Hey Dima, I wasn't sure if anyone uploaded a LOL sample, so here's one if you have time to get around to it. Thanks! 

[LOL Example.xlsx](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/4453776/LOL.Example.xlsx)

**Comment by Denwen12** [comment]
could this be used now @DimaKudosh

**Comment by DimaKudosh** [comment]
@Denwen12 Yes, i released a new version with lol for fanduel

**Comment by Denwen12** [comment]
Perfect thank you

**Comment by Denwen12** [comment]
i believe you made a mistake in 
LineupPosition('MVP', ('TOP', 'MID', 'ADC', 'JNG', 'SUP', 'TEAM'), for_rank=PlayerRank.MVP),

you cant use Team in MVP

**Comment by DimaKudosh** [comment]
Thank you for feedback, I got info from fd site [https://support.fanduel.com/hc/en-us/articles/360045272553-What-is-League-of-Legends-LoL-](https://support.fanduel.com/hc/en-us/articles/360045272553-What-is-League-of-Legends-LoL-) probably this article already outdated. So for clarifying in classic mode we have STAR instead of MVP, STAR can't be TEAM and positions order should be STAR, TOP, JNG, MID, ADC, SUP, TEAM, is it right? Also did you tried LOL single game? Is settings for it correct?

**Comment by Denwen12** [comment]
I did not try single

**Comment by Denwen12** [comment]
settings look good

**Comment by brente33** [comment]
Minimum of 3 teams also I believe.

**Comment by DimaKudosh** [comment]
Released new version with fixes for fd lol

**Comment by Denwen12** [comment]
> Released new version with fixes for fd lol

I'll test this again this weekend

**Comment by brente33** [comment]
I still can't get STAR to work as a position outside of single games. Says this:
pydfs_lineup_optimizer.exceptions.LineupOptimizerIncorrectPositionName: STAR is incorrect position name.

**Comment by Denwen12** [comment]
I haven't tested yet but maybe @DimaKudosh can answer this

**Comment by Denwen12** [comment]
it looks like dima forgot to add for_rank=PlayerRank.STAR in importer

**Comment by Denwen12** [comment]
if you change for_rank=PlayerRank.STAR to for_rank=PlayerRank.MVP it should work again

**Comment by Denwen12** [comment]
in settings file for fanduel cassic

**Comment by brente33** [comment]
I still can't get it. I changed the code back to .MVP and I tried removing the [FanduelSingleGameStarRule] but that didn't work. I feel like the STAR position is only being brought in for the single games, not the classic game.

**Comment by Denwen12** [comment]
I'll check later for you until dima can check into this

**Comment by brente33** [comment]
Thanks man, appreciate it. It think it has to do with the csv_importer line in settings. Like there is a cross between the classic/single game code.

**Comment by Denwen12** [comment]
I can look at this now real fast

**Comment by Denwen12** [comment]
im gonna test this now for you

**Comment by Denwen12** [comment]
i just tested this and mine worked perfectly

**Comment by Denwen12** [comment]
> Thanks man, appreciate it. It think it has to do with the csv_importer line in settings. Like there is a cross between the classic/single game code.
can i see your python code

**Comment by brente33** [comment]
Sure, I left importer the same and changed settings to PlayerRank.MVP:
@SitesRegistry.register_settings
class FanDuelLOLSettings(FanDuelSettings):
    sport = Sport.LEAGUE_OF_LEGENDS
    max_from_one_team = 4
    min_teams = 3
    csv_importer = build_fanduel_single_game_importer(mvp=False, star=True, pro=False)
    extra_rules = [FanduelSingleGameStarRule]  # type: List[Type[OptimizerRule]]
    positions = [
        LineupPosition('STAR', ('TOP', 'MID', 'ADC', 'JNG', 'SUP'), for_rank=PlayerRank.MVP),
        LineupPosition('TOP', ('TOP',)),
        LineupPosition('JNG', ('JNG',)),
        LineupPosition('MID', ('MID',)),
        LineupPosition('ADC', ('ADC',)),
        LineupPosition('SUP', ('SUP',)),
        LineupPosition('TEAM', ('TEAM',)),
    ]

Here is the run code:
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, CSVLineupExporter
optimizer = get_optimizer(Site.FANDUEL, Sport.LEAGUE_OF_LEGENDS)
from pydfs_lineup_optimizer.stacks import BaseGroup, TeamStack, PositionsStack, BaseStack, Stack, PlayersGroup
optimizer.load_players_from_csv("LOL.csv")


optimizer.add_stack(PositionsStack(['STAR', 'TOP']))

lineups = list(optimizer.optimize(n=1, randomness=False))
for lineup in lineups:
    print(lineup)
exporter = CSVLineupExporter(lineups)
exporter.export('resultlol.csv')

I tried changing csv_importer = build_fanduel_single_game_importer(mvp=False, star=True, pro=False) line to have MVP=True and so on but that didn't work either.
It's got to be something simple...

**Comment by jsst28** [comment]
I'm trying to constrain the STAR position for LOL and I'm using similar run code from Fanduel NBA single game contests but I'm having no luck. When I initially run the code I get this error:
AttributeError: 'Player' object has no attribute 'is_star'

I then added self.is_star = False  # type: bool to player.py, which allows the run code to work, but does not actually constrain the STAR position. Do I need to add something in the settings to allow for this constraint?

**Comment by DimaKudosh** [comment]
@brente33 You got incorrect position name on this line `optimizer.add_stack(PositionsStack(['STAR', 'TOP']))` because actually all players have one of these positions: `TOP', 'MID', 'ADC', 'JNG', 'SUP', 'TEAM'` and stack can't be build because STAR position isn't presented for players.

**Comment by DimaKudosh** [comment]
@jsst28 I removed is_mvp, is_star and is_pro attributes from player in new version and added one single attribute rank, so you can check if player is star like: 
```
from pydfs_lineup_optimizer.constants import PlayerRank

star_players = [p for p in players if p.rank == PlayerRank.STAR]
```

**Comment by brente33** [comment]
@DimaKudosh thanks Dima, really appreciate your work on this. Is there a way to force the STAR player into a 4 person stack then? I want to have a team stack of 4 that included the STAR. Thanks again!

**Comment by DimaKudosh** [comment]
@brente33 I think I'll be able to solve all current issues at the end of the month so I'll look into this issue as well. For now you can try to create custom stack that includes star player by default, [here](https://gist.github.com/DimaKudosh/779b8548f6f5ac4c89d3d5e9f1a42101) is example

**Comment by brente33** [comment]
@DimaKudosh you are the man.

**Comment by jsst28** [comment]
Hey Dima, I'm still getting this error: NameError: name 'players' is not defined
What do I need to do to define players? Sorry for my ignorance, my coding and Pycharm skills are limited.

**Comment by Denwen12** [comment]
if you used the coding dima provided I believe you have to add the players name to the groups

**Comment by brente33** [comment]
You can just add positions, but the issue is once you add the positions those players don't get pulled in as stars. So if you select your star to be with ADC and MID, it won't select a Star from ADC or Mid players.

**Comment by jsst28** [comment]
I'm more looking to add individual players as opposed to positions like I do with NFL and NBA single game. I've tried adding player names to groups but haven't had any luck

**Comment by Denwen12** [comment]
i run my settings tonight with the way i run my script and mine turns out decent
 1. STAR  Kanavi Kanavi                 JNG   JDG            DMO@JDG  0.87    9000.0$   
 2. TOP   Jinoo Jinoo                   TOP   EDG            EDG@IG   0.7     8200.0$   
 3. JNG   JieJie JieJie                 JNG   EDG            EDG@IG   0.7     8300.0$   
 4. MID   Scout Scout                   MID   EDG            EDG@IG   0.7     8500.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   LvMao LvMao                   SUP   JDG            DMO@JDG  0.58    8100.0$   
 7. TEAM  Team WE Team WE               TEAM  WE             WE@LNG   0.54    7300.0$   

Fantasy Points 4.79
Salary 59100.00

 1. STAR  Scout Scout                   MID   EDG            EDG@IG   1.05    8500.0$   
 2. TOP   Morgan Morgan                 TOP   WE             WE@LNG   0.54    8100.0$   
 3. JNG   JieJie JieJie                 JNG   EDG            EDG@IG   0.7     8300.0$   
 4. MID   Yagao Yagao                   MID   JDG            DMO@JDG  0.58    9200.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  Team WE Team WE               TEAM  WE             WE@LNG   0.54    7300.0$   

Fantasy Points 4.81
Salary 58600.00

 1. STAR  Scout Scout                   MID   EDG            EDG@IG   1.05    8500.0$   
 2. TOP   Morgan Morgan                 TOP   WE             WE@LNG   0.54    8100.0$   
 3. JNG   JieJie JieJie                 JNG   EDG            EDG@IG   0.7     8300.0$   
 4. MID   Yagao Yagao                   MID   JDG            DMO@JDG  0.58    9200.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  JD Gaming JD Gaming           TEAM  JDG            DMO@JDG  0.58    8100.0$   

Fantasy Points 4.85
Salary 59400.00

 1. STAR  JieJie JieJie                 JNG   EDG            EDG@IG   1.05    8300.0$   
 2. TOP   Jinoo Jinoo                   TOP   EDG            EDG@IG   0.7     8200.0$   
 3. JNG   Kanavi Kanavi                 JNG   JDG            DMO@JDG  0.58    9000.0$   
 4. MID   Teacherma Teacherma           MID   WE             WE@LNG   0.54    8300.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  JD Gaming JD Gaming           TEAM  JDG            DMO@JDG  0.58    8100.0$   

Fantasy Points 4.85
Salary 59100.00

 1. STAR  Jinoo Jinoo                   TOP   EDG            EDG@IG   1.05    8200.0$   
 2. TOP   Zoom Zoom                     TOP   JDG            DMO@JDG  0.58    9000.0$   
 3. JNG   JieJie JieJie                 JNG   EDG            EDG@IG   0.7     8300.0$   
 4. MID   Teacherma Teacherma           MID   WE             WE@LNG   0.54    8300.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  JD Gaming JD Gaming           TEAM  JDG            DMO@JDG  0.58    8100.0$   

Fantasy Points 4.85
Salary 59100.00

 1. STAR  Scout Scout                   MID   EDG            EDG@IG   1.05    8500.0$   
 2. TOP   Jinoo Jinoo                   TOP   EDG            EDG@IG   0.7     8200.0$   
 3. JNG   JieJie JieJie                 JNG   EDG            EDG@IG   0.7     8300.0$   
 4. MID   Yagao Yagao                   MID   JDG            DMO@JDG  0.58    9200.0$   
 5. ADC   LokeN LokeN                   ADC   JDG            DMO@JDG  0.58    10300.0$  
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  Team WE Team WE               TEAM  WE             WE@LNG   0.54    7300.0$   

Fantasy Points 4.85
Salary 59300.00

 1. STAR  JieJie JieJie                 JNG   EDG            EDG@IG   1.05    8300.0$   
 2. TOP   Jinoo Jinoo                   TOP   EDG            EDG@IG   0.7     8200.0$   
 3. JNG   Kanavi Kanavi                 JNG   JDG            DMO@JDG  0.58    9000.0$   
 4. MID   Scout Scout                   MID   EDG            EDG@IG   0.7     8500.0$   
 5. ADC   LokeN LokeN                   ADC   JDG            DMO@JDG  0.58    10300.0$  
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  Team WE Team WE               TEAM  WE             WE@LNG   0.54    7300.0$   

Fantasy Points 4.85
Salary 59100.00

 1. STAR  Scout Scout                   MID   EDG            EDG@IG   1.05    8500.0$   
 2. TOP   Jinoo Jinoo                   TOP   EDG            EDG@IG   0.7     8200.0$   
 3. JNG   Kanavi Kanavi                 JNG   JDG            DMO@JDG  0.58    9000.0$   
 4. MID   Teacherma Teacherma           MID   WE             WE@LNG   0.54    8300.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  Team WE Team WE               TEAM  WE             WE@LNG   0.54    7300.0$   

Fantasy Points 4.81
Salary 58500.00

 1. STAR  Scout Scout                   MID   EDG            EDG@IG   1.05    8500.0$   
 2. TOP   Zoom Zoom                     TOP   JDG            DMO@JDG  0.58    9000.0$   
 3. JNG   JieJie JieJie                 JNG   EDG            EDG@IG   0.7     8300.0$   
 4. MID   Teacherma Teacherma           MID   WE             WE@LNG   0.54    8300.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  JD Gaming JD Gaming           TEAM  JDG            DMO@JDG  0.58    8100.0$   

Fantasy Points 4.85
Salary 59400.00

 1. STAR  JieJie JieJie                 JNG   EDG            EDG@IG   1.05    8300.0$   
 2. TOP   Jinoo Jinoo                   TOP   EDG            EDG@IG   0.7     8200.0$   
 3. JNG   Kanavi Kanavi                 JNG   JDG            DMO@JDG  0.58    9000.0$   
 4. MID   Yagao Yagao                   MID   JDG            DMO@JDG  0.58    9200.0$   
 5. ADC   Hope Hope                     ADC   EDG            EDG@IG   0.7     9700.0$   
 6. SUP   Meiko Meiko                   SUP   EDG            EDG@IG   0.7     7500.0$   
 7. TEAM  Team WE Team WE               TEAM  WE             WE@LNG   0.54    7300.0$   

Fantasy Points 4.85
Salary 59200.00

**Comment by Denwen12** [comment]
i got my own system that works for me

**Comment by brente33** [comment]
I'd like to be able to add the STAR position to a team stack. I want to make sure the 4 man stack has the STAR player.

**Comment by Denwen12** [comment]
use the first and last name like you would in nfl so it would be "Hope Hope"

**Comment by Denwen12** [comment]
hey @DimaKudosh, I seem to be having some problems running single game lineups for lol and not sure why

**Comment by DimaKudosh** [comment]
@Denwen12 Could you provide more information what problems did you faced?

**Comment by Denwen12** [comment]
I will after work tonight
