### ISSUE TITLE
Is there anything I need to import to get PlayersGroup(), TeamStack(), and PositionsStack() within optimizer.add_stack() to work?

### ISSUE THREAD

**Issue by magelssen88** [DimaKudosh/pydfs-lineup-optimizer#149]
I've just started using this package, and after successfully getting most of the objects to run, for some reason I'm unable to get PlayersGroup(), TeamStack(), and PositionsStack() within optimizer.add_stack() to work, as it says it can't import components of these. I've consulted the readthedocs.io documentation and cannot figure out what I need to import from pydfs_lineup_optimizer to get this to work. (I have the latest version of the package, so not sure if some items were deprecated since the documentation).

Based on previous questions, I've tried:
from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter, TeamStack
from pydfs_lineup_optimizer.stacks import TeamStack

**Comment by DimaKudosh** [comment]
You can import it from stacks submodule like:
```
from pydfs_lineup_optimizer.stacks import TeamStack, PositionsStack, PlayersGroup
```

**Comment by magelssen88** [comment]
Thanks, DimaKudosh - when I try that it returns:
ModuleNotFoundError: No module named 'pydfs_lineup_optimizer.stacks'

Btw, as an aside, this package and its intended uses are absolutely amazing, thank you for creating it!

**Comment by DimaKudosh** [comment]
Are you sure that you are using the latest version? Could you run:
```
from pydfs_lineup_optimizer import __version__
print(__version__)
```

**Comment by magelssen88** [comment]
I believe so, it results in: **2.1.0**

I tried updating packages and re-running, to no avail. Other info: running via Conda-Spyder in IPython console kernel. Python version 3.7.0

**Comment by brente33** [comment]
Make sure you are loading it:

from pydfs_lineup_optimizer.stacks import BaseGroup, TeamStack, PositionsStack, BaseStack, Stack, PlayersGroup

**Comment by magelssen88** [comment]
Thanks, brente33 - I tried that line and still getting the same issue:
`ModuleNotFoundError: No module named 'pydfs_lineup_optimizer.stacks'`

I also tried to uninstall and reinstall the pydfs-lineup-optimizer package. Really not sure if I have a dependency issue or what. Apologies for my naivety on this, am coming back to python after a long stint in R.
