### ISSUE TITLE
Minimum players from group

### ISSUE THREAD

**Issue by asardinha** [DimaKudosh/pydfs-lineup-optimizer#150]
Hi Dima,

I noticed there is a portion of code for "min from group" in "stacks.py." Is it possible to call the following:

```
group = PlayersGroup([optimizer.get_player_by_name(name) for name in ('LeBron James', 'Anthony Davis','Damian Lillard,'Trae Young')], max_from_group=3, **min_from_group=1**)
optimizer.add_players_group(group)
```

For example, if I want to have AT least one of the players in the group in my line-ups, I can, but I can also have more than one (specified by the "max_from_group." )

Essentially, I'd like to have the possibility of having one to three of the players specified in the example, appear in the results.

Thanks again for all that you do.

**Comment by DimaKudosh** [comment]
Hi! Yes you can specify both parameters. In this case optimizer will generate lineups with number of players from group in range from `min_from_group` to `max_from_group`.

**Comment by Denwen12** [comment]
Anyway we can add randomness to the group?
