### ISSUE TITLE
Fanduel PGA can't generate lineups

### ISSUE THREAD

**Issue by jccarrigan** [DimaKudosh/pydfs-lineup-optimizer#153]
Hi there,

Really appreciate the work you have done on this package, its been tremendously useful. 

I've had no problems using it for mlb and pga on DK. I'm currently attempting to use the optimizer for pga on FanDuel, and it is saying it can't solve. When using the debugger, it looks like all the player information is correctly imported. I've tried with importing the players using csv and Player objects. Any ideas?

**Comment by DimaKudosh** [comment]
Hi, could you provide csv that you used I'll try to investigate this issue.

**Comment by jccarrigan** [comment]
[360-1296optimizerprojections.csv.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/4576679/360-1296optimizerprojections.csv.zip)

**Comment by DimaKudosh** [comment]
It's a bug in fanduel golf. I'll fix it in the next release. For now, you can add this line before running optimize:
`optimizer.settings.min_teams = None`
