### ISSUE TITLE
Draftkings MLB max exposure bug

### ISSUE THREAD

**Issue by mbencho** [DimaKudosh/pydfs-lineup-optimizer#154]
The draftkings classic mlb settings only allow for a max_from_one_team of 5. However, you are allowed to have 6 players from one team as long as one of the six is a pitcher(SP/RP). 

Maximum of five for one team for spots C/1B/2B/3B/SS/OF
Maximum of six for one team for spots if one of the spots is SP/RP and then the other five are from C/1B/2B/3B/SS/OF

class DraftKingsBaseballSettings(DraftKingsSettings):
    sport = Sport.BASEBALL
    **max_from_one_team = 5**
        LineupPosition('P', ('SP', 'RP')),
        LineupPosition('P', ('SP', 'RP')),
        LineupPosition('C', ('C', )),
        LineupPosition('1B', ('1B', )),
        LineupPosition('2B', ('2B', )),
        LineupPosition('3B', ('3B', )),
        LineupPosition('SS', ('SS', )),
        LineupPosition('OF', ('OF', )),
        LineupPosition('OF', ('OF', )),
        LineupPosition('OF', ('OF', )),

**Comment by asardinha** [comment]
In "Rules.py"" There will need to be something similar to the FanDuelBaseballRoster rule where 5 hitters are acceptable, opposed the 4.

**Comment by DimaKudosh** [comment]
Fixed this rule in version 3.3.0
