### ISSUE TITLE
Draftkings settings.py should require teams from 2 games for most sports

### ISSUE THREAD

**Issue by elitwilliams** [DimaKudosh/pydfs-lineup-optimizer#157]
Unless I'm mistaken, one of the key lineup rules for classic DK is not being implemented in settings. For all classic lineups in team sports (NFL, NBA, MLB, NHL, LOL, etc - only excluding TEN, NASCAR, Golf) there must be players from at least 2 games. This is different from Fanduel, where there must be players from 3 teams in most sports. Meaning you could have players from only 2 teams in your lineup as long as those 2 teams aren't playing each other.

A (bad) workaround that I've been using is setting `min_teams = 3` but that becomes particularly bad when you have to use stacks of 4 and 3 in a lineup of size 7 for LOL to have any shot of winning the tournament.

**Comment by DimaKudosh** [comment]
Fixed DK settings in version 3.3.0
