### ISSUE TITLE
Question for this star or mvp position

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#158]
@DimaKudosh 
how can I restrict certain players in star positions on fanduel

**Comment by Denwen12** [comment]
i also tryed this but not working neither

`my_mvps = ['Merab Dvalishvli', 'Julia Avila']
for player in optimizer.players:
    if player.is_mvp and player.full_name not in my_mvps:
        `optimizer.remove_player(player)`

**Comment by Denwen12** [comment]
any one have an idea?

**Comment by pippinainteasy** [comment]
You could just change the projections for whatever positions you don't want in the Star spot to 0

**Comment by Denwen12** [comment]
yeah you could do that but then they wouldn't be selected in the other slots cause fanduel isnt the same as draftkings where they have a seperate position like Cpt

**Comment by pippinainteasy** [comment]
I forgot about that. You could always go into the FanDuel settings and take out whatever positions you don't want in the MVP slot out of the settings.

**Comment by Denwen12** [comment]
that is what i did
