### ISSUE TITLE
Feature request - option to calculate exposure levels after each lineup is created instead of as a % of total

### ISSUE THREAD

**Issue by elitwilliams** [DimaKudosh/pydfs-lineup-optimizer#159]
This is a feature in other optimizers - the idea is, if you set a max_exposure, that exposure number is used at the end of each lineup being generated instead of calculated against the full # of lineups being generated. 

By way of example, if you set a max_exposure of 0.50 for player A (assume he is very high value play) for 150 lineups, in the current version you will get him in the first 75 lineups and then 0 times in the last 75 lineups. In the requested version, after the first lineup is generarted exposure is calculated at 100% (since he is used in all currently generated lineups, only 1/1, he is removed from player pool), 2nd lineup would not have him (previous exposure 100%, new exposure 50% after 2nd lineup generated), 3rd lineup would not have him (previous exposure 50%, new exposure 33.33%), and then the 4th lineup would once have him again since exposure of the previous exposure at 33.33% is below the max_exposure threshold of 50%. See attached screenshot of implementation from an optimizer web app.

I could be wrong on the exact implementation here, but the idea is you're recalculating exposures after every lineup and adding/removing players from the player pool given their current exposure level to the number of lineups currently generated as opposed to the total # of lineups to be generated. I think the idea is that this spreads out the best value players a bit more instead of concentrating them at the top of your lineups with exposure caps. Thanks.

![Screen Shot 2020-06-14 at 9 55 39 AM](https://user-images.githubusercontent.com/2677808/84595618-c4162f80-ae26-11ea-9e6e-497b8545eeaa.jpeg)

![Screen Shot 2020-06-14 at 10 07 21 AM](https://user-images.githubusercontent.com/2677808/84595634-ff186300-ae26-11ea-979a-97af1ec90154.jpeg)

**Comment by austinjohnson** [comment]
This is an interesting concept. I would like to have this option too.

**Comment by DimaKudosh** [comment]
Added this feature in version 3.3.0 Here is an example of how you can use it:
```
from pydfs_lineup_optimizer import AfterEachExposureStrategy
optimizer.optimize(10, exposure_strategy=AfterEachExposureStrategy)
```
