### ISSUE TITLE
Cant load CSV file for FanDuel

### ISSUE THREAD

**Issue by litesprof** [DimaKudosh/pydfs-lineup-optimizer#16]
KeyError                                  Traceback (most recent call last)
<ipython-input-48-0fbe4c2e13a3> in <module>()
----> 1 optimizer.load_players_from_CSV("FanDuel-MLB-2018-05-15-25805-lineup-upload-template.csv")

~\Desktop\pydfs-lineup-optimizer-master\pydfs_lineup_optimizer\lineup_optimizer.py in load_players_from_CSV(self, filename)
    162         :type filename: str
    163         """
--> 164         self._players = self._settings.load_players_from_CSV(filename)
    165         self._set_available_teams()
    166 

~\Desktop\pydfs-lineup-optimizer-master\pydfs_lineup_optimizer\settings.py in load_players_from_CSV(cls, filename)
    131                 max_exposure = row.get('Max Exposure')
    132                 player = Player(
--> 133                     row['Id'],
    134                     row['First Name'],
    135                     row['Last Name'],

KeyError: 'Id'

**Comment by ltd9938** [comment]
Hmm I can't seem to recreate. Are you using the latest pull?

**Comment by trevordavies095** [comment]
Hmm I can't seem to recreate. Are you using the latest pull? Is the csv file altered?

**Comment by DimaKudosh** [comment]
Did you use csv generated by fanduel site?
