### ISSUE TITLE
Force CPT into a stack

### ISSUE THREAD

**Issue by mbencho** [DimaKudosh/pydfs-lineup-optimizer#160]
This is likely possible but I can't figure out the correct code for it. 

On draftkings I want to be able to force optimizer to always select a CPT as a part of a team stack. However, for a sport with CAPTAIN mode that has only CPT/FLEX positions when I use:

optimizer.set_team_stacking([3], for_positions=['CPT','FLEX'])

it will place 3 players in FLEX as well. 

Any thoughts as to how to do this?

**Comment by Denwen12** [comment]
I have been working on this but im no expert

**Comment by DimaKudosh** [comment]
You can do it using PositionsStack, in your case it looks like:
```
optimizer.add_stack(PositionsStack(['CPT', 'FLEX', 'FLEX']))
```
