### ISSUE TITLE
NBA Single Game Optimizer

### ISSUE THREAD

**Issue by JoeAndrei** [DimaKudosh/pydfs-lineup-optimizer#163]
Hi
I have tried nba single game optimizer with Player model
And It says "Can't generate lineups".

**Comment by Denwen12** [comment]
Hi can I see your python code you are running

**Comment by JoeAndrei** [comment]
![image](https://user-images.githubusercontent.com/54272208/86421646-62523280-bd0d-11ea-8925-b9cb52149634.png)
![image](https://user-images.githubusercontent.com/54272208/86421660-70a04e80-bd0d-11ea-9e89-e948ef767b35.png)
![image](https://user-images.githubusercontent.com/54272208/86421669-79912000-bd0d-11ea-9976-33b8421d126c.png)

Thanks for you reply
Its are my full code

**Comment by JoeAndrei** [comment]
Hello, did you have a chance check the nba fanduel single game?

**Comment by BenikaH** [comment]
I can take a look at it if you haven't gotten a solution yet. Do you have a csv as well?

**Comment by BenikaH** [comment]
Also, it may be helpful in debugging to use the script, not an image.

**Comment by JoeAndrei** [comment]
I think my problem is player model
If I try with "load_players_from_csv", it is perfect
And I don't know how to make players for fanduel single game.
![image](https://user-images.githubusercontent.com/54272208/87487840-50f41900-c671-11ea-8588-8d3bfced8787.png)
It is my player model.

**Comment by DimaKudosh** [comment]
For FD single game you should create multiple players for each slot (MVP/STAR/UTIL). So after creating a player you also should create a new "MVP" player with multiplied points, that is how it's done in repository https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/sites/fanduel/classic/importer.py#L53 Note that it works in the latest version 3.3.0 in previous versions the special attribute was added to a player object for FD but it break stacks functionality and I replaced it in the new version of package

**Comment by JoeAndrei** [comment]
Thank you
