### ISSUE TITLE
Set ceiling and floor instead of max and min deviation

### ISSUE THREAD

**Issue by austinjohnson** [DimaKudosh/pydfs-lineup-optimizer#164]
Is there a way to replace the max and min deviation with a ceiling a floor option?

For example, I want player X projected score to be a random number between 68 and 75. With min and max deviation you can't accurately set a range as you can with ceiling and floor.

**Comment by austinjohnson** [comment]
I would like to just be able to add a ceiling and floor to the csv like you can with max and min deviation

**Comment by austinjohnson** [comment]
```
class RandomObjective(OptimizerRule):
    def apply_for_iteration(self, solver, players_dict, result):
        variables = []
        coefficients = []
        optimizer_min_deviation, optimizer_max_deviation = self.optimizer.get_deviation()
        for player, variable in players_dict.items():
            variables.append(variable)
            multiplier = uniform(
                player.min_deviation if player.min_deviation is not None else optimizer_min_deviation,
                player.max_deviation if player.max_deviation is not None else optimizer_max_deviation
            )
            coefficients.append(uniform(player.min_deviation, player.max_deviation))
            
        solver.set_objective(variables, coefficients)
```

I think this should do it. I removed the ` process_percents` from max and min deviation and then set the deviation as a floor and ceiling in the csv

**Comment by Denwen12** [comment]
did this work cause I like the idea

**Comment by austinjohnson** [comment]
@Denwen12 as far as I know. I was waiting for @DimaKudosh to confirm.

**Comment by austinjohnson** [comment]
@Denwen12 You're going to have to enter the floor and ceiling in the csv as your min and max values. and remove the `process percents` from the `player.py`

**Comment by Denwen12** [comment]
I'll give it a try tonight after work

**Comment by Denwen12** [comment]
what does the new lines look like? in player.py

**Comment by austinjohnson** [comment]
@Denwen12 
```
@min_deviation.setter
    def min_deviation(self, min_deviation: Optional[float]):
        self._min_deviation = min_deviation
```

You need to do the same for max_deviation too.

**Comment by Denwen12** [comment]
can you upload the file after you have done the mods

**Comment by Denwen12** [comment]
or email the modified file to my email joffen12@gmail.com

**Comment by Denwen12** [comment]
are you able to upload the changed files?

**Comment by austinjohnson** [comment]
Yes I'll upload them. I wanted to get it confirmed that it was working correctly by @DimaKudosh before I did it.

**Comment by Denwen12** [comment]
Okay I just emailed him last night about this

**Comment by DimaKudosh** [comment]
Added this in the new release, you can add `Projection Floor` and `Projection Ceil` columns to csv or set `fppg_floor` and `fppg_ceil` fields in player model

**Comment by Denwen12** [comment]
@DimaKudosh 
Will this select any projection now in between?

**Comment by BenikaH** [comment]
@DimaKudosh and @austinjohnson This is a game changer. I like the concept here. Thanks for the hard work.
