### ISSUE TITLE
Feature Request: Add Max Salary Constraint

### ISSUE THREAD

**Issue by cmay10** [DimaKudosh/pydfs-lineup-optimizer#166]
Can we get a max salary constraint added? Ex. I want all of my lineups to have a max salary of 49500. It helps create more unique lineups.

**Comment by austinjohnson** [comment]
I think feature already exists.

**Comment by DimaKudosh** [comment]
I'm not sure how useful would be this feature, so I won't add it to package. You can achieve the desired effect if you decrease budget. `optimizer.settings.budget = 49500`
