### ISSUE TITLE
Lineup diversity requirement

### ISSUE THREAD

**Issue by sansbacon** [DimaKudosh/pydfs-lineup-optimizer#17]
Is it possible to limit the number of players who appear in the same lineup?
For example, say the optimal lineup is Player A, B, C, D, E, F, G, and H
The overlap parameter is 5, meaning that no lineup should have more than 5 common players. Another lineup with A, B, C, D, E, F, X, Y would fail the constraint, whereas a lineup with A, B, C, D, E, X, Y would be OK. I'm not familiar with how to use pulp, but this is how it might be done (inefficiently) using or-tools:
```
# loop through optimal lineups that have already been generated
# add diversity constraint of no more than overlap in new lineup
for lineup in existing_lineups:
    diversity_cap = solver.Constraint(0, overlap)
    for player in lineup.players:
        # lookup index of player in all_players
        # then set coefficient of that index to 1
        i = [i for i, p in enumerate(all_players) if p.id == player.id][0]
        diversity_cap.SetCoefficient(variables[i], 1)
```

**Comment by DimaKudosh** [comment]
Currently it's not possible, I'll add it in feature release

**Comment by DimaKudosh** [comment]
Added `set_max_repeating_players` method in 2.0
