### ISSUE TITLE
Opposing players on smaller slates

### ISSUE THREAD

**Issue by pippinainteasy** [DimaKudosh/pydfs-lineup-optimizer#171]
I am having trouble getting the `restrict_positions_for_opposing_team` setting from keeping opposing players out of each lineup. For example, on a two game MLB slate I am using `optimizer.restrict_positions_for_opposing_team(['SP'], ['C', '1B', '2B','3B', 'SS', 'OF'], 2)` and still getting full 5 stacks against a pitcher. Was just wondering if anyone else was having this happen? Or maybe I am doing it incorrectly.

**Comment by ravashjalil** [comment]
This is an issue I brought up last season and he marked it as a "question" and closed it. Tons of issues with this program but instead of fixing the existing ones he continues to just try to add more features.

**Comment by pippinainteasy** [comment]
To be fair, this repository is completely free and never once has he asked for compensation. He does this on his own when he can. That said, I am glad it is not just me. I will just avoid these smaller slates until he has a chance to take a look at them.

**Comment by Denwen12** [comment]
Ill see what I can do when i return from vacation.

**Comment by mbencho** [comment]
https://github.com/DimaKudosh/pydfs-lineup-optimizer/commit/37e8c27a16a3bdbd75ea60d67892a9ea990fc9c8 There was an update to allow this functionality, but that only happened a few months ago. If you want absolutely no players against your pitcher remove the 2. i haven't tested this new functionality yet myself
optimizer.restrict_positions_for_opposing_team(['SP'], ['C', '1B', '2B','3B', 'SS', 'OF'])

**Comment by pippinainteasy** [comment]
> [37e8c27](https://github.com/DimaKudosh/pydfs-lineup-optimizer/commit/37e8c27a16a3bdbd75ea60d67892a9ea990fc9c8) There was an update to allow this functionality, but that only happened a few months ago. If you want absolutely no players against your pitcher remove the 2. i haven't tested this new functionality yet myself
> optimizer.restrict_positions_for_opposing_team(['SP'], ['C', '1B', '2B','3B', 'SS', 'OF'])

On a small slate, say 2 games, I want to allow 1 or 2 players against a pitcher. But for some reason I am getting full stacks against a pitcher instead of the max of 2 players. On a big slate I use that no opposing players restriction and it works perfect. It only seems to be an issue on 2 gamers when I am trying to allow a couple of players.

**Comment by Denwen12** [comment]
ill help you thursday thats when im free

**Comment by DimaKudosh** [comment]
It was a problem with restrict method when using it with max_allowed parameter, I fixed it in the new version
