### ISSUE TITLE
DraftKings Tiers Usage

### ISSUE THREAD

**Issue by bimpyinu** [DimaKudosh/pydfs-lineup-optimizer#176]
Hi,
I'm having issues after trying the new tiers feature in 3.3.0 - when I try to run the following line:

`optimizer = get_optimizer(Site.DRAFTKINGS_TIERS, Sport.BASKETBALL)`

I get a NotImplementedError (KeyError: 'BASKETBALL') even though I have the latest version of the package installed

Am I misunderstanding the usage for the new game type?

**Comment by DimaKudosh** [comment]
Hi, It's strange because it works correctly for me, what python version do you use? As a workaround you can try to init optimizer in this way:
```
from pydfs_lineup_optimizer.sites.draftkings.tiers.settings import DraftKingsTiersBasketballSettings
from pydfs_lineup_optimizer import LineupOptimizer

optimizer = LineupOptimizer(DraftKingsTiersBasketballSettings)
```

**Comment by bimpyinu** [comment]
Using that way returns the following for me:

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-115-70f883b32401> in <module>
      1 # generate_lineups_tiers(date,draftgroup,n_lineups=20)
----> 2 from pydfs_lineup_optimizer.sites.draftkings.tiers.settings import DraftKingsTiersBasketballSettings
      3 from pydfs_lineup_optimizer import LineupOptimizer
      4 
      5 optimizer = LineupOptimizer(DraftKingsTiersBasketballSettings)

D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\tiers\settings.py in <module>
      5 from pydfs_lineup_optimizer.lineup_printer import DraftKingTiersLineupPrinter
      6 from pydfs_lineup_optimizer.sites.draftkings.tiers.importer import DraftKingsTiersCSVImporter
----> 7 from pydfs_lineup_optimizer.rules import DraftKingsTiersRule
      8 
      9 

ImportError: cannot import name 'DraftKingsTiersRule' from 'pydfs_lineup_optimizer.rules' (D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\rules.py)`

I had been using 3.6.3, but I tried upgraded to 3.8.3 and the issue still persists unfortunately

**Comment by bimpyinu** [comment]
If it's helpful context, I also get the issue as in [Issue 175](https://github.com/DimaKudosh/pydfs-lineup-optimizer/issues/175) in a new notebook, but not when reimporting the package in this specific notebook. I checked my PuLP version but it's listed as 2.3 and upgrading it doesn't do anything so I'm not sure how to resolve that either, but I'd imagine the two issues are related. I also just clean reinstalled Anaconda but that didn't help

**Comment by DimaKudosh** [comment]
Can you look for a version in your installed package?
```
from pydfs_lineup_optimizer import __version__
print(__version__)
```

**Comment by bimpyinu** [comment]
It prints 3.3.0 in the already-opened workbook, but any new notebook that I open and try to load the package I get the error from Issue 175

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-114ba9f1ee34> in <module>
      5 import os
      6 import warnings
----> 7 from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
      8 from datetime import datetime, timedelta
      9 import json

D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\__init__.py in <module>
      4 from pydfs_lineup_optimizer.exceptions import LineupOptimizerException, LineupOptimizerIncorrectTeamName, \
      5     LineupOptimizerIncorrectPositionName, LineupOptimizerIncorrectCSV
----> 6 from pydfs_lineup_optimizer.lineup_optimizer import LineupOptimizer
      7 from pydfs_lineup_optimizer.lineup import Lineup
      8 from pydfs_lineup_optimizer.sites import SitesRegistry

D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in <module>
      5 from typing import FrozenSet, Type, Generator, Tuple, Union, Optional, List, Dict, Set, cast
      6 from pydfs_lineup_optimizer.lineup import Lineup
----> 7 from pydfs_lineup_optimizer.solvers import Solver, PuLPSolver, SolverException
      8 from pydfs_lineup_optimizer.exceptions import LineupOptimizerException, LineupOptimizerIncorrectTeamName, \
      9     LineupOptimizerIncorrectPositionName

D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\solvers\__init__.py in <module>
----> 1 from pydfs_lineup_optimizer.solvers.pulp_solver import Solver, PuLPSolver
      2 from pydfs_lineup_optimizer.solvers.constants import SolverSign
      3 from pydfs_lineup_optimizer.solvers.exceptions import SolverException
      4 
      5 

D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\solvers\pulp_solver.py in <module>
      5 
      6 
----> 7 class PuLPSolver(Solver):
      8     LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
      9 

D:\Programs\Anaconda\lib\site-packages\pydfs_lineup_optimizer\solvers\pulp_solver.py in PuLPSolver()
      6 
      7 class PuLPSolver(Solver):
----> 8     LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
      9 
     10     def __init__(self):

TypeError: __init__() got an unexpected keyword argument 'verbose'

`

**Comment by bimpyinu** [comment]
The fix in [issue 177](https://github.com/DimaKudosh/pydfs-lineup-optimizer/issues/177) solved my issues. Thank you for looking into this and for the new features!
