### ISSUE TITLE
PuLP version compatibility

### ISSUE THREAD

**Issue by conordurkin** [DimaKudosh/pydfs-lineup-optimizer#177]
Just a quick note - it appears that the latest version of the PuLP package is now 2.3 (as of 4 August 2020). I was unable to run the pydfs-lineup-optimizer properly on 2.3 due to an error being generated by the PuLPSolver function: 

```
File "/opt/anaconda3/lib/python3.8/site-packages/pydfs_lineup_optimizer/solvers/pulp_solver.py", line 8, in PuLPSolver
    LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
TypeError: __init__() got an unexpected keyword argument 'verbose'
```

Seems the arguments required for PULP_CBC_CMD() must have changed between 2.2 and 2.3 and 'verbose' is no longer an expected argument. 

I uninstalled PuLP 2.3, uninstalled pydfs-lineup-optimizer, re-installed PuLP 2.2, re-installed pydfs-lineup-optimizer, and package now runs as expected.

**Comment by jmoore87jr** [comment]
I'm getting the same error on 8 August 2020; verbose is no longer a keyword argument for PULP_CBC_CMD() after the package update.

**Comment by Denwen12** [comment]
Yeah everyone seems to have to uninstall pulp 2.3 for the error

**Comment by leodigi** [comment]
Yes, uninstalling pulp 2.3 and installing pulp 2.2 fixed this issue for me most recently (yesterday).

**Comment by harvitronix** [comment]
Quick reference:

`pip install -I pulp==2.2`

Or in my case:

`pip3 install --user -I pulp==2.2`

**Comment by BenikaH** [comment]
Quick question with the PuLP update. When importing the PULP_CBC_CMD, did pulp.solvers change to pulp.apis?
