### ISSUE TITLE
Max exposure by position

### ISSUE THREAD

**Issue by conordurkin** [DimaKudosh/pydfs-lineup-optimizer#184]
Is there a way to set the **max_exposure** argument only for certain positions? 

In MLB, I'd like to set a max exposure for the P slot, but not for hitters. I think I could in theory do this by setting a max exposure for every pitcher in the player pool but assume there must be a cleaner way.

**Comment by xAffectum** [comment]
Did you already tried:
pitchers = filter(lambda p: p.positions == 'P', optimizer.players)
for pitcher in pitchers:
    pitcher.max_exposure = 0.5

**Comment by conordurkin** [comment]
Just tried running this: 

`    optimizer = get_optimizer(Site.FANDUEL, Sport.BASEBALL)
    optimizer.load_players_from_csv(_file_in_)
    optimizer.restrict_positions_for_opposing_team(['P'], ['C', 'SS', 'OF', '1B', '2B', '3B'])

    pitchers = filter(lambda p: p.positions == 'P', optimizer.players)
    for pitcher in pitchers:
        pitcher.max_exposure = 0.50
        
    optimizer.add_stack(TeamStack(4))    
    for lineup in optimizer.optimize(n = 150):
        out = (lineup)
    optimizer.export(file_out)
    optimizer.print_statistic()`

And the output gave me 150 lineups with the same pitcher, seems like that doesn't work.

**Comment by Denwen12** [comment]
ill try and work on this for you

**Comment by Denwen12** [comment]
here you go
"for player in optimizer.players:
    if 'P' in player.positions:
        player.max_exposure = 0.5"

**Comment by conordurkin** [comment]
This works! Thank you.

**Comment by Denwen12** [comment]
You welcome @conordurkin
