### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by willywill325** [DimaKudosh/pydfs-lineup-optimizer#186]
I installed the package but I keep getting this error message.  I cannot initiate the program.

C:\WINDOWS\system32>$ pip install pydfs-lineup-optimizer
'$' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Denwen12** [comment]
we use pyhton3 so usev
pip3 install pydfs-lineup-optimizer

**Comment by willywill325** [comment]
Ok I am now getting this error for running draftkings golf lineups.  

 1 optimizer = get_optimizer(Site.DRAFTKINGS, Sport.GOLF)
----> 2 optimizer.load_players_from_csv("DKSalaries.csv")
      3 for lineup in optimizer.optimize(n=10):
      4     print(lineup)
      5     print(lineup.players)  # list of players

~\anaconda3\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in load_players_from_csv(self, filename)
    136         if not csv_importer:
    137             csv_importer = self._settings.csv_importer
--> 138         self._players = csv_importer(filename).import_players()
    139 
    140     def load_lineups_from_csv(self, filename: str) -> List[Lineup]:

~\anaconda3\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in import_players(self)
     55 
     56     def import_players(self):
---> 57         with open(self.filename, 'r') as csv_file:
     58             start_line = 0  # Find line with 'TeamAbbrev', that's where players data starts
     59             while True:

FileNotFoundError: [Errno 2] No such file or directory: 'DKSalaries.csv'

**Comment by Denwen12** [comment]
you didnt download your draftkings player list?

**Comment by Denwen12** [comment]
you have to point this to your file
 ----> 2 optimizer.load_players_from_csv("DKSalaries.csv")

**Comment by willywill325** [comment]
Got it to work thanks.  How do i do CPT mode?
