### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by jmackin5** [DimaKudosh/pydfs-lineup-optimizer#187]
threw this into the cell and got the error above

'
from pydfs_lineup_optimizer import get_optimizer, Site, Sport
'

**Comment by jmackin5** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-41b60942a5b9> in <module>
----> 1 from pydfs_lineup_optimizer import get_optimizer, Site, Sport
      2 
      3 optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
      4 optimizer.load_players_from_csv("/Users/JakeMack/Downloads/DKSalaries.csv")
      5 for lineup in optimizer.optimize(n=10):

/opt/anaconda3/lib/python3.7/site-packages/pydfs_lineup_optimizer/__init__.py in <module>
      4 from pydfs_lineup_optimizer.exceptions import LineupOptimizerException, LineupOptimizerIncorrectTeamName, \
      5     LineupOptimizerIncorrectPositionName, LineupOptimizerIncorrectCSV
----> 6 from pydfs_lineup_optimizer.lineup_optimizer import LineupOptimizer
      7 from pydfs_lineup_optimizer.lineup import Lineup
      8 from pydfs_lineup_optimizer.sites import SitesRegistry

/opt/anaconda3/lib/python3.7/site-packages/pydfs_lineup_optimizer/lineup_optimizer.py in <module>
      5 from typing import FrozenSet, Type, Generator, Tuple, Union, Optional, List, Dict, Set, cast
      6 from pydfs_lineup_optimizer.lineup import Lineup
----> 7 from pydfs_lineup_optimizer.solvers import Solver, PuLPSolver, SolverException
      8 from pydfs_lineup_optimizer.exceptions import LineupOptimizerException, LineupOptimizerIncorrectTeamName, \
      9     LineupOptimizerIncorrectPositionName

/opt/anaconda3/lib/python3.7/site-packages/pydfs_lineup_optimizer/solvers/__init__.py in <module>
----> 1 from pydfs_lineup_optimizer.solvers.pulp_solver import Solver, PuLPSolver
      2 from pydfs_lineup_optimizer.solvers.constants import SolverSign
      3 from pydfs_lineup_optimizer.solvers.exceptions import SolverException
      4 
      5 

/opt/anaconda3/lib/python3.7/site-packages/pydfs_lineup_optimizer/solvers/pulp_solver.py in <module>
      5 
      6 
----> 7 class PuLPSolver(Solver):
      8     LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
      9 

/opt/anaconda3/lib/python3.7/site-packages/pydfs_lineup_optimizer/solvers/pulp_solver.py in PuLPSolver()
      6 
      7 class PuLPSolver(Solver):
----> 8     LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
      9 
     10     def __init__(self):

TypeError: __init__() got an unexpected keyword argument 'verbose'

**Comment by Denwen12** [comment]
could i see your code your using

**Comment by jmackin5** [comment]
from pydfs_lineup_optimizer import Site, Sport, get_optimizer


optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
optimizer.load_players_from_csv("mypath")
for lineup in optimizer.optimize(10):
    print(lineup)

**Comment by Denwen12** [comment]
you might be using new version of pulp that you have to downgrade

**Comment by Denwen12** [comment]
seems like your not importing pulp

**Comment by bigboyz** [comment]
I am having a similar issue.  

Brand new install:
Python 3.6.2
Pydfs 3.3

If I run this by itself:
from pydfs_lineup_optimizer import __version__
print(__version__)

It will result in an error here:

  File "go.py", line 3, in <module>
    from pydfs_lineup_optimizer import __version__
  File "MYPATHREMOVED/venv/lib/python3.6/site-packages/pydfs_lineup_optimizer/__init__.py", line 6, in <module>
    from pydfs_lineup_optimizer.lineup_optimizer import LineupOptimizer
  File "MYPATHREMOVED/venv/lib/python3.6/site-packages/pydfs_lineup_optimizer/lineup_optimizer.py", line 7, in <module>
    from pydfs_lineup_optimizer.solvers import Solver, PuLPSolver, SolverException
  File "MYPATHREMOVED/venv/lib/python3.6/site-packages/pydfs_lineup_optimizer/solvers/__init__.py", line 1, in <module>
    from pydfs_lineup_optimizer.solvers.pulp_solver import Solver, PuLPSolver
  File "MYPATHREMOVED/venv/lib/python3.6/site-packages/pydfs_lineup_optimizer/solvers/pulp_solver.py", line 7, in <module>
    class PuLPSolver(Solver):
  File "MYPATHREMOVED/venv/lib/python3.6/site-packages/pydfs_lineup_optimizer/solvers/pulp_solver.py", line 8, in PuLPSolver
    LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
TypeError: __init__() got an unexpected keyword argument 'verbose'

Other versions work great though.

**Comment by Denwen12** [comment]
you have to use pulp 2.2 for python 3

**Comment by bigboyz** [comment]
I downgraded to pulp 2.2 and worked.  Might be the fastest Github reply I've ever seen.  The requirements though install pulp2.3 so I would guess a lot of others will run into this issue.  For those reading this thread a quick:

`pip install pulp==2.2`

....should do the trick

**Comment by sansbacon** [comment]
I submitted a fix for this. You can add a try/except line to pulp_solvers.py
```
class PuLPSolver(Solver):
    try:
        LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
    except TypeError:
        LP_SOLVER = PULP_CBC_CMD(msg=False)
```
