### ISSUE TITLE
Max from team allowed by Count 

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#188]
might be possible already but id like to be able to set how many i want allowed from teams in lineups, ex like i only want to allow 2 players from 9pm games, Thanks in advance. @DimaKudosh

**Comment by Denwen12** [comment]
with teamstack you set the teams exposure but id perfer to set a limit on the players from that team

**Comment by DimaKudosh** [comment]
You can create a player group with players from these games:
```
games_start = datetime(...)  # Should be datetime with timezone
optimizer.add_players_group(PlayersGroup(
    players=[player for player in optimizer.players if player.game_info.starts_at == games_start],
    max_from_group=2,
))
```

**Comment by Denwen12** [comment]
thank you dima do i have to enter a col in csv with game time

**Comment by Denwen12** [comment]
Im working on this by adding

```
from pydfs_lineup_optimizer import set_timezone
set_timezone('EDT')

games_start = datetime('EDT')  # Should be datetime with timezone
optimizer.add_players_group(PlayersGroup(
    players=[player for player in optimizer.players if player.game_info.starts_at == games_start],
    max_from_group=2,
))

i get 
File "Fanduel2Finish.py", line 24, in <module>
    games_start = datetime('EDT')  # Should be datetime with timezone
NameError: name 'datetime' is not defined

**Comment by Denwen12** [comment]
i also tryed
  File "Fanduel2Finish.py", line 22
    games_start = datetime(03:30 pm EDT)  # Should be datetime with timezone
                            ^
SyntaxError: invalid token

**Comment by Denwen12** [comment]
this didnt work neither
```
games_start = datetime('03:30 pm EDT')  # Should be datetime with timezone
optimizer.add_players_group(PlayersGroup(
    players=[player for player in optimizer.players if player.game_info.starts_at == '06:30 pm EDT'],
    max_from_group=2,
))
```

**Comment by Denwen12** [comment]
where would i add gametime in Csv?

**Comment by Denwen12** [comment]
Im also using Fanduel and they dont include time in csv so i have to add that

**Comment by Denwen12** [comment]
i see that this is the info for draftkings in csv, so i gotta some how make it work for fanduel

draftkings......csv
Game Info
DEN@UTA 08/23/2020 09:00PM ET

Fanduel.....csv

Game
MIL@ORL

Fanduel has no time

**Comment by Denwen12** [comment]
have to create a column for time in csv

**Comment by Denwen12** [comment]
seems like i cant figure this out but still working on it

**Comment by Denwen12** [comment]
i seem to got it to run like this but ita not working still
```
games_start = ('03:30:00 PM EDT')  # Should be datetime with timezone
optimizer.add_players_group(PlayersGroup(players=[player for player in optimizer.players if player.game_info.starts_at == '06:30:00 PM EDT'],max_from_group=2,))
```

**Comment by Denwen12** [comment]
Im not sure about this, seems like its not working for me

**Comment by Denwen12** [comment]
i installed a program called DateTime-4.3 but it will not still run

**Comment by Denwen12** [comment]
any idea for this @DimaKudosh

**Comment by Denwen12** [comment]
is there a way to call a custom made column?

**Comment by Denwen12** [comment]
or we can call game info like it shows BKN@TOR MAX 2 PLAYERS SOME HOW

**Comment by DimaKudosh** [comment]
For reading custom column you should also override file parser, I think it will be easier for you if you sort player by teams that play before 9 pm
```
teams = ['BKN', 'TOR']
optimizer.add_players_group(PlayersGroup(
    players=[player for player in optimizer.players if player.team in teams],
    max_from_group=2,
))

```

**Comment by Denwen12** [comment]
i will try this and will this consider players from both games or max 2 from each teams?

**Comment by DimaKudosh** [comment]
In this case optimizer will generate lineups with max 2 players from this players group, players group includes all players from specified teams so max 2 players will be selected from all specified teams

**Comment by Denwen12** [comment]
perfect, thanks for your hard work
