### ISSUE TITLE
Initial Installation Issue - ImportError: No module named solvers

### ISSUE THREAD

**Issue by kevinsoltis41** [DimaKudosh/pydfs-lineup-optimizer#19]
Trying to get initial installation and having a little trouble.

MacOS
pip 10.0.1
Python 2.7.15

After running: $ pip install pydfs-lineup-optimizer
Output shows:
Requirement already satisfied: pydfs-lineup-optimizer in {{PATH}} (2.0.0)
Requirement already satisfied: PuLP>=1.6.8 in {{PATH}} (from pydfs-lineup-optimizer) (1.6.8)
Requirement already satisfied: typing in  {{PATH}} (from pydfs-lineup-optimizer) (3.6.4)
Requirement already satisfied: pyparsing>=2.0.1 in {{PATH}} (from PuLP>=1.6.8->pydfs-lineup-optimizer) (2.2.0)

After attempting to do initial import: from pydfs_lineup_optimizer import get_optimizer, Site, Sport

I get the following error:
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pydfs_lineup_optimizer import get_optimizer, Site, Sport
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydfs_lineup_optimizer/__init__.py", line 7, in <module>
    from pydfs_lineup_optimizer.lineup_optimizer import LineupOptimizer
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydfs_lineup_optimizer/lineup_optimizer.py", line 6, in <module>
    from pydfs_lineup_optimizer.solvers import PuLPSolver, SolverException
ImportError: No module named solvers

Please let me know if I can provide anymore information.

Hoping to get this resolved, this looks awesome!
- Kevin

**Comment by DimaKudosh** [comment]
Try to install it again, now it should work

**Comment by kevinsoltis41** [comment]
Resolved. 
Thanks again!
