### ISSUE TITLE
MLB stacking

### ISSUE THREAD

**Issue by agscarnage** [DimaKudosh/pydfs-lineup-optimizer#200]
Is there a way to not include P in an mlb stack?

**Comment by agscarnage** [comment]
issue resolved

**Comment by lightninglarry** [comment]
@jecarnes how did you go about doing this?
And on 2nd note, how do you include a 2nd Teamstack, if im wanting a 4-3, i dont get that with my output.  The 4 comes through fine, but usually only get 2 with the 2nd stack.

**Comment by wizardous23** [comment]
> @jecarnes how did you go about doing this? And on 2nd note, how do you include a 2nd Teamstack, if im wanting a 4-3, i dont get that with my output. The 4 comes through fine, but usually only get 2 with the 2nd stack.

@lightninglarry did you ever find out how to get the 2nd stack working?

**Comment by lightninglarry** [comment]
@wizardous23 no.  Im hoping someone replies to the other thread about this.

**Comment by jecarnes** [comment]
optimizer.add_stack(TeamStack(4, for_positions=['1B', '2B', '3B', 'C', 'SS', 'OF']))
optimizer.add_stack(TeamStack(4, for_positions=['1B', '2B', '3B', 'C', 'SS', 'OF']))

switch the number for the size, don't use spacing unless you're actually using the roster order
