### ISSUE TITLE
Fan Duel Single Game Question

### ISSUE THREAD

**Issue by ranis1227** [DimaKudosh/pydfs-lineup-optimizer#201]
Thank you for this. The optimizer is brilliant and working for me.  

However, I am having issues with the single game optimizer.  I was able to load the code properly. How do I print out the lineup?  I am still a novice with Python. I am sure it is simple line of code.

**Comment by sansbacon** [comment]
```
for lineup in optimizer.optimize(n_lineups):
    print(lineup)
```

**Comment by ranis1227** [comment]
> ```
> for lineup in optimizer.optimize(n_lineups):
>     print(lineup)
> ```

Thank you!
