### ISSUE TITLE
NFL, NBA Draftkings Caption Mode optimizer is not working

### ISSUE THREAD

**Issue by JoeAndrei** [DimaKudosh/pydfs-lineup-optimizer#202]
```
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, CSVLineupExporter


optimizer = get_optimizer(Site.DRAFTKINGS_CAPTAIN_MODE, Sport.FOOTBALL)
optimizer.load_players_from_csv("DKSalaries.csv")

exporter = CSVLineupExporter(optimizer.optimize(1))
exporter.export('result.csv')

```
I tried to get NFL Draftkings Caption Mode Optimzier result.
And it says "can't generate"

Please help me.
Thank you.

**Comment by agscarnage** [comment]
Use this instead
from pydfs_lineup_optimizer import get_optimizer, Site, Sport
optimizer = get_optimizer(Site.DRAFTKINGS_CAPTAIN_MODE, Sport.BASKETBALL) 
optimizer.load_players_from_csv("DKSalaries.csv")


for lineup in optimizer.optimize(1):
    print(lineup)

optimizer.export('result.csv')

**Comment by sansbacon** [comment]
Before closing this issue, we should do one of two things: change the documentation or the code when it comes to multiple lineups. The documentation gives the example

```
optimizer.optimize(10)
optimizer.export('result.csv')
```

However, as currently designed, it looks like you need to iterate over the generator (or cast it to a list) before you can export lineups. If this is the intended behavior, then the documentation should be changed to reflect it. It could look something like this:

```
# if you want to print the lineups to the screen
for lineup in optimizer.optimize(10):
    print(lineup)
optimizer.export('result.csv')

# if you don't want to print the lineups to the screen
lineups = list(optimizer.optimize(10))
optimizer.export('result.csv')
```

If it is a bug, then maybe the export method should take a list of lineups as an argument?

**Comment by JoeAndrei** [comment]
Thank you
