### ISSUE TITLE
Print statistic error

### ISSUE THREAD

**Issue by will6809** [DimaKudosh/pydfs-lineup-optimizer#214]
I'm getting error when i try to print player stats. If someone could look at my code and help me. 
I am new to python

from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
from pydfs_lineup_optimizer.stacks import TeamStack, PositionsStack, PlayersGroup
from pydfs_lineup_optimizer import AfterEachExposureStrategy

file = 'lineups.csv'

optimizer = get_optimizer(Site.FANDUEL, Sport.FOOTBALL)
optimizer.load_players_from_csv('will.csv')
optimizer.set_deviation(0.4, 0.12)
optimizer.add_stack(TeamStack(2, for_positions=['QB', 'WR']))
optimizer.force_positions_for_opposing_team(('QB', 'WR'))

lineups = optimizer.optimize(40 , max_exposure=0.12 , exposure_strategy=AfterEachExposureStrategy)
optimizer.print_statistic() 

exporter = CSVLineupExporter(lineups)
exporter.export(file)

**Comment by anthonyshook** [comment]
Are you just missing a 'p' in this line?
`otimizer.print_statistic()`  should be `optimizer.print_statistic()`

**Comment by will6809** [comment]
Thanks for noticing that. Did not fix the error.

**Comment by will6809** [comment]
Ok i figured it out.   Thanks
