### ISSUE TITLE
Groups containing the same player and having multiple min_from_group attributes throw a LineupOptimizerException

### ISSUE THREAD

**Issue by seans84** [DimaKudosh/pydfs-lineup-optimizer#221]
When attempting to generate lineups and multiple groups contain the same player a `LineupOptimizerException` will be raised. This doesn't seem like desirable behavior. 

For example, I want to create 2 groups:

group 1 - Lebron James and Jimmy Butler to min_from_group=1 
group 2 - Lebron James and Kevin Durant with min_from_group=2 (effectively a stack).

Due to Lebron James being in both groups and sharing a `min_from_group` constraint a `LineupOptimizerException` is raised.

If `max_from_group` is used for all of the groups then no exception is raised. The issue seems to rest squarely on multiple `min_from_group`'s being used in groups that contain the same player.

**Comment by sansbacon** [comment]
So it looks like the default is that groups cannot intersect. Try replacing class OptimizerStack:
    def __init__(self, groups: List[BaseGroup], can_intersect=False) with can_intersect=True in stacks.py 

For the library, probably should have a way to toggle the intersection value, perhaps as a property of the optimizer class?

**Comment by asardinha** [comment]
Could this also work for player conditional group?

For example:

If player x is in lineup, play min 1, max 3 of player(s) a,b,c?

If not how would we achieve this?
