### ISSUE TITLE
MMA restrict player when opponent is in lineup

### ISSUE THREAD

**Issue by bernienbernard** [DimaKudosh/pydfs-lineup-optimizer#227]
Is there a way to restrict a fighter from getting in your lineup once his opponent is part the lineup? Up until now I've made a PlayerGroup with the two opposing fighters and set the max_exposure=0.01 but I'm hoping someone has a better idea.

**Comment by mbencho** [comment]
optimizer.restrict_positions_for_opposing_team(['F'], ['F']) should work

**Comment by coltonfischer** [comment]
If you load the game info for the fighters, then you can restrict positions from the opposing team to achieve what you are looking for. 

Example: optimizer.restrict_positions_for_opposing_team(['F'], ['F'])
