### ISSUE TITLE
Fanduel NHL Lineups

### ISSUE THREAD

**Issue by anthonyshook** [DimaKudosh/pydfs-lineup-optimizer#233]
Just FYI -- FanDuel changed their NHL settings this year.  Namely, they used to have 4 slots for W, but now it's 2 slots for W, and two UTIL slots:

So this:
https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/41961834b8a57e825a62aaf0cc933b17e0e2715b/pydfs_lineup_optimizer/sites/fanduel/classic/settings.py#L52-L65

should become:
```
class FanDuelHockeySettings(FanDuelSettings):
    sport = Sport.HOCKEY
    budget = 55000
    positions = [
        LineupPosition('C', ('C', )),
        LineupPosition('C', ('C', )),
        LineupPosition('W', ('W', )),
        LineupPosition('W', ('W', )),
        LineupPosition('D', ('D', )),
        LineupPosition('D', ('D', )),
        LineupPosition('UTIL', ('C', 'W', 'D')),
        LineupPosition('UTIL', ('C', 'W', 'D')),
        LineupPosition('G', ('G', )),
    ]
```

**Comment by DimaKudosh** [comment]
Fixed in 3.4.1
