### ISSUE TITLE
How to update to newest version

### ISSUE THREAD

**Issue by will6809** [DimaKudosh/pydfs-lineup-optimizer#234]
Can some tell me how i update to latest version.  Currently I'm  running 3.3 i believe.

Thanks

**Comment by Denwen12** [comment]
git pull "https://github.com/yourUserName/yourRepo.git"
edit the last part should work

**Comment by will6809** [comment]
Thanks

**Comment by Denwen12** [comment]
did that work?

**Comment by will6809** [comment]
yea i got it updated

**Comment by Denwen12** [comment]
ok cool
