### ISSUE TITLE
Export New Late Swap Lineups To CSV

### ISSUE THREAD

**Issue by OzzyDFS** [DimaKudosh/pydfs-lineup-optimizer#236]
Hello, long time user, first time poster. My python knowledge is very limited. This is an amazing tool though and I want to get the most out of it. I have read all the documentation and can't figure out the solution to my problem. 

I am trying to utilize the "late swap" feature on Draftkings and change lineups for tonight's NBA slate but for the life of me, I can't figure out how to export these new lineups into a CSV. Every time I try, the file generated contains the exact same lineups as before. What am I doing wrong?

Here is the code:

from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter

csv_filename = "DKEntries.csv"
optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
optimizer.load_players_from_csv(csv_filename)
lineups = optimizer.load_lineups_from_csv(csv_filename)
for lineup in optimizer.optimize_lineups(lineups):
print(lineup)
optimizer.export('New_Late_Swap_Lineups.csv')

**Comment by OzzyDFS** [comment]
Bump? Anyone have any ideas?

**Comment by OzzyDFS** [comment]
Is this possible @DimaKudosh ?

**Comment by OzzyDFS** [comment]
Bumping again. There has to be a way to do this efficiently, right?

**Comment by DimaKudosh** [comment]
Do you see any changes in lineups when you print them?

**Comment by OzzyDFS** [comment]
> Do you see any changes in lineups when you print them?

Yes, that works fine.

**Comment by DimaKudosh** [comment]
Look like some bug with export, I'll fix it for now you can call exporter manually:
```python
generated_lineups = []
for lineup in optimizer.optimize_lineups(lineups):
    generated_lineups.append(lineup)
optimizer.settings.csv_exporter(generated_lineups).export('New_Late_Swap_Lineups.csv')
```

**Comment by OzzyDFS** [comment]
Thank you so much Dima. It works perfectly!
