### ISSUE TITLE
Randomness for select players?

### ISSUE THREAD

**Issue by McCampy** [DimaKudosh/pydfs-lineup-optimizer#242]
Hello everyone, hope your projects are coming along nicely. I was wondering if it is possible to set that randomness feature to True for only a select group of players? From the documentation, it appears that you can turn off the randomness for players but you would have to manually go through and assign no randomness to almost all the other players. Any insight would be great, thanks.

**Comment by austinjohnson** [comment]
I think you can just set min deviation and max deviation to zero in your excel sheet and only changes the players you want.

**Comment by McCampy** [comment]
> I think you can just set min deviation and max deviation to zero in your excel sheet and only changes the players you want.

ah that makes sense, thank you. Do you by chance know if it matters where the columns are located? In excel, I have min and max deviation in column indexes 15 and 16 but the optimizer doesn't seem to pick them up.

**Comment by ericcolon** [comment]
Are you using an excel spreadsheet or the salary csv file?  You need a csv file in the same format as the one downloaded from DK, FD etc.

What I do is download the salaries sheet, vlookup projections and add a Min Deviation and Max Deviation columns.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by McCampy** [comment]
Thanks, Eric. Yes, i'm doing something similar, I'm grabbing the csv from fd and importing it into excel to edit the columns. It works when I set up some of the extra columns that the optimizer can read, just not min and max deviation for some odd reason. It's good to hear that it's working on your end though, leads me to think I just have some little error somewhere.

**Comment by sansbacon** [comment]
FYI, you don't need your spreadsheet to match a particular format. There are helper functions that will load those particular files, but it is not a requirement.

You can create Player objects however you want and then load them into the optimizer with ```load_players```.

All of the parameters for the Player object are below. You can create Player objects from any csv file or dataframe just by mapping your field/column names to the __init__ signature.

```
    def __init__(self,
                 player_id: str,
                 first_name: str,
                 last_name: str,
                 positions: List[str],
                 team: str,
                 salary: float,
                 fppg: float,
                 is_injured: bool = False,
                 max_exposure: Optional[float] = None,
                 min_exposure: Optional[float] = None,
                 projected_ownership: Optional[float] = None,
                 game_info: Optional[GameInfo] = None,
                 roster_order: Optional[int] = None,
                 min_deviation: Optional[float] = None,
                 max_deviation: Optional[float] = None,
                 is_confirmed_starter: Optional[bool] = None,
                 fppg_floor: Optional[float] = None,
                 fppg_ceil: Optional[float] = None,
                 original_positions: Optional[List[str]] = None,
                 ):

```
For example, this is how I load players from rows of a pandas dataframe
```
from pydfs_lineup_optimizer import Player

def _row_to_player(self, row):
    """Converts dataframe row to Player object
    Args:
        row (namedtuple): dataframe row
    Returns:
        Player
    """
    valid_kwargs = (
            'is_injured', 'max_exposure', 'min_exposure', 
            'projected_ownership', 'game_info', 'roster_order', 
            'min_deviation', 'max_deviation', 'is_confirmed_starter', 
            'fppg_floor', 'fppg_ceil'
    )
        
    kwargs = {field: getattr(row, field) for field in row._fields
                     if field in valid_kwargs}

    return Player (
            player_id=row.player, 
            first_name=self._first_name(row.player),
            last_name=self._last_name(row.player),
            positions=[row.pos],
            team=row.team,
            salary=row.salary,
            fppg=row.proj,
            **kwargs
    )

```

**Comment by McCampy** [comment]
Okay gotcha, thanks for the tip sansbacon. Appreciate ya throwing in your code, i'll see if I can get something similar going.

**Comment by sansbacon** [comment]
If you want more detail about Player objects and how to load them in the optimizer, I've created a [series of notebooks relating to lineup optimization](https://github.com/sansbacon/lineup-optimization-cookbook) that covers this, among other topics.

**Comment by McCampy** [comment]
@sansbacon This is great stuff, thank you.
