### ISSUE TITLE
NBA FANTASYDRAF is not working

### ISSUE THREAD

**Issue by dev0926** [DimaKudosh/pydfs-lineup-optimizer#246]
Hello, how are you?
I have tried to use nba fantasydraft optimizer using the csv from superdraft.
And I have got incorrect csv error.

Also I tried to use load players from players list.
And I am getting yahoo result instance of fantasy_draft

`optimizer = get_optimizer(Site.FANTASY_DRAFT, Sport.BASKETBALL)`

I have used above code

Please help me.
Thanks

**Comment by lightninglarry** [comment]
optimizer is spelled wrong
