### ISSUE TITLE
fanduel NFL optimizer error

### ISSUE THREAD

**Issue by sansbacon** [DimaKudosh/pydfs-lineup-optimizer#25]
I keep encountering a bug in the FanDuel NFL optimizer, regardless of whether I create my own player objects or use load_players_from_CSV. 

Here is an example of the output using the site CSV file:

In [4]: optimizer.load_players_from_CSV('~/fd.csv')

In [5]: lineup_generator = optimizer.optimize(10)
   ...: for lineup in lineup_generator:
   ...:     print(lineup)
   ...:     
---------------------------------------------------------------------------
LineupOptimizerException                  Traceback (most recent call last)
<ipython-input-5-ed6e271df733> in <module>()
      1 lineup_generator = optimizer.optimize(10)
----> 2 for lineup in lineup_generator:
      3     print(lineup)
      4 

~/anaconda3/lib/python3.6/site-packages/pydfs_lineup_optimizer/lineup_optimizer.py in optimize(self, n, max_exposure, randomness, with_injured)
    525                 yield lineup
    526             else:
--> 527                 raise LineupOptimizerException('Can\'t generate lineups')
    528         self._lineup = locked_players
    529         return

LineupOptimizerException: Can't generate lineups
 
[fd.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/2436139/fd.zip)

**Comment by DimaKudosh** [comment]
Tested fanduel nfl optimizers with provided csv and it worked correctly with latest library version. I think FanDuel changed rules for NFL a few month ago and I added changes to made it working with current rules. Try to update this library.

**Comment by sansbacon** [comment]
I thought I had the newest version, but updating solved the error. Thanks!
