### ISSUE TITLE
Max Per team = 2

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#251]
Without delcaring each team on the slate how do you code it where the maximum number of players from ANY team on slate in one lineup could be 2?

**Comment by sansbacon** [comment]
A simple way is to use ```set_total_teams```. Assuming there are 8 lineup slots, if you set it to 7, you will not get more than two players from a team in a lineup.

```
optimizer.set_total_teams(lineup_slots - 1)
```

If you want to have the option of two players from two or more teams each, or no requirement that two players be on the same team, then you would use a loop to discard lineups that violate that constraint, as that particular constraint does not appear to be implemented yet:

```
def valid_lineup(lineup):
    # count players on teams 
    # return False if count wrong, return True if correct
    return True/False depending on condition


valid_lineups = []
n_lineups = 10

for lineup in optimizer.optimize(1000):
    if valid_lineup(lineup):
        valid_lineups.append(lineup)
        if len(valid_lineups) >= n_lineups:
            break
```

To add this functionality to the optimizer, it seems like it is a small variation on the TeamMatesRule
```
class LimitedTeamMatesRule(OptimizerRule):
    def apply(self, solver):
        for team, quantity in self.optimizer.players_from_one_team.items():
            players_from_same_team = [variable for player, variable in self.players_dict.items() if player.team == team]
            solver.add_constraint(variables=players_from_same_team, coefficients=None, sign=SolverSign.LTE, rhs=2)

```
You would likely want to a parameter for 2 in case you wanted to limit to 3 teammates, etc.

**Comment by TheOdenator** [comment]
How would you implement this for showdown? The rule I'd like to set is for NBA showdown. I'm thinking an onslaught isn't likely to win so I'd like a rule to include at least 2 players from each team. I know how to set exactly 2 but not more than 2. Goal is to make 2-4, 3-3, and 4-2 lineups

**Comment by lightninglarry** [comment]
> How would you implement this for showdown? The rule I'd like to set is for NBA showdown. I'm thinking an onslaught isn't likely to win so I'd like a rule to include at least 2 players from each team. I know how to set exactly 2 but not more than 2. Goal is to make 2-4, 3-3, and 4-2 lineups

Anyone know an easy way to Force a 4-2 stack, or 5-1(showdown)

**Comment by lightninglarry** [comment]
> optimizer.set_total_teams(lineup_slots - 1)

@sansbacon definitely a noob here, i tried the 
optimizer.set_total_teams(lineup_slots - 1) code, but i get its not defined error:

NameError: name 'lineup_slots' is not defined


if im loading from csv, heres my current plain code:

optimizer = get_optimizer(Site.FANDUEL, Sport.BASKETBALL)
optimizer.settings.csv_exporter = CustomExporter  # replace default exporter with custom
optimizer.load_players_from_csv(r"C:\Users\brand\Downloads\FanDuel-NBA-2021 ET-10 ET-19 ET-65053-players-list.csv")
optimizer.set_total_teams(lineup_slots - 3)
optimizer.set_min_salary_cap(59400)
optimizer.set_max_repeating_players(7)
optimizer.player_pool.add_filters(PlayerFilter(from_value=5),)  # use only players with points >= 5

lineups = optimizer.optimize(150, exposure_strategy=AfterEachExposureStrategy)
for lineup in lineups:
    print(lineup)
optimizer.export(r"C:\Users\brand\Desktop\PYTHON\NBA\NBAFANDUEL.csv")
optimizer.print_statistic()

**Comment by lightninglarry** [comment]
finally got it @sansbacon.  Closing it.  Thanks

**Comment by lightninglarry** [comment]
@sansbacon After examining this it partially works.  How would u tackle this?
currently on FD it has 9 roster slots, - 1 makes it 8(wanting 2 max per team).
What this does is allow 1 set of teammates in a lineup(Butler/Lowry) from MIami
But it will skip optimal versions if one tandem is already in lineup.  
For example
If lowry/butler are in lineup together, you will never get another "pair" of teammates in the same lineup.  I want this to be possible, but that would be that max of it.  At most 2 "tandems" per lineup.  Thoughts?
