### ISSUE TITLE
Fanduel MMA question

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#256]
I looked through the closed issues and the answer helped a draftkings issue, but as for Fanduel.  Limiting one fighter per fight in a lineup
Example Miocic vs Ngannou.  Id want at maximum one of them per lineup.

Heres the code I tried, that didnt error out, just didnt work.

from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
from pydfs_lineup_optimizer.stacks import TeamStack, PositionsStack, PlayersGroup
from pydfs_lineup_optimizer import AfterEachExposureStrategy

playerList = r"C:\Users\brand\Downloads\FanDuel-UFC-2021 ET-03 ET-27 ET-56105-players-list.csv"
optimizer = get_optimizer(Site.FANDUEL, Sport.MMA)
optimizer.load_players_from_csv(playerList)

fight1 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Jamie Mullarkey', 'Khama Worthyr')], max_from_group=1)
optimizer.add_players_group(fight1)

fight2 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Gillian Robertson', 'Miranda Maverick')], max_from_group=1)
optimizer.add_players_group(fight2)

fight3 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ("Sean O'Malley", "Thomas Almeida")], max_from_group=1)
optimizer.add_players_group(fight3)

fight4 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Vicente Luque', 'Tyron Woodley')], max_from_group=1)
optimizer.add_players_group(fight4)

#fight5 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Stipe Miocic', 'Francis Ngannou')], max_from_group=1)
#optimizer.add_players_group(fight5)

fight6 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Alonzo Menifield', 'Fabio Cherant')], max_from_group=1)
optimizer.add_players_group(fight6)

fight7 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Jared Gooden', 'Abubakar Nurmagomedov')], max_from_group=1)
optimizer.add_players_group(fight7)

fight8 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Modestas Bukauskas', 'Michal Oleksiejczuk')], max_from_group=1)
optimizer.add_players_group(fight8)

fight9 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Omar Morales', 'Shane Young')], max_from_group=1)
optimizer.add_players_group(fight9)

fight10 = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Abu Azaitar', 'Marc-Andre Barriault')], max_from_group=1)
optimizer.add_players_group(fight10)
lineups = optimizer.optimize(n=5, max_exposure=.3, exposure_strategy = AfterEachExposureStrategy)
#optimizer.set_min_salary_cap(95)
for lineup in lineups:
    print(lineup)

unfortunately the load in csv doesnt state opponent like the Draftkings one does so this line wouldnt work.
optimizer.restrict_positions_for_opposing_team(['F'], ['F'])

**Comment by DimaKudosh** [comment]
FanDuel doesn't include information about opponent so `restrict_positions_for_opposing_team ` isn't working because of this. Right now it's only possible to manually add this information into optimizer as in your code sample with player groups.

**Comment by lightninglarry** [comment]
sorry to bring up a closed topic.  This works except for the minor case one fighter is in the MVP slot.  
IE McGregor can be the MVP, but his opponent can be one in the flex fighters.

McGregor and his opponent would never both be flex fighters in same lineup, but its treating MVP as a totally different position.  What is the work around this?


Secondary question, what if if wanted Conor McGregor or his opponent in every lineup.  I tried this, but it didnt like it:

fight1= PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Dustin Poirier', 'Conor McGregor')], max_from_group=1, min_from_group=1)
optimizer.add_players_group(fight1)

and i tried this as well

group = PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Conor McGregor', 'Dustin Poirier')])
optimizer.add_players_group(group)

any thoughts?
