### ISSUE TITLE
adjusting player projections for players NOT used in previous lineup(s)

### ISSUE THREAD

**Issue by Owen-Slater** [DimaKudosh/pydfs-lineup-optimizer#258]
Great Work here. Love the optimizer! 
I've been trying to figure out a way to bump players in the player pool by x% when they have not been used in the previous lineup. Once a player is used in the previous lineup, the projection reverts back to the original projection. 
I am trying to build a portfolio of likely outcomes, and doing this somewhat by hand creates very good results when entering 150 lineups. I've tried using Ceiling and Floor with random = true, but the results are just "too random".... 
Example of what I'm trying to achieve:  

Harden projected at 50fpts,
Harden is _not_ used in lineup 1, Harden's NEW projection is now 51fpts. 
Harden is _not_ used in lineup 2, Harden's NEW projection is 52fpts. 
Harden is _not_ used in lineup 3, Harden's NEW projection is 53fpts. 
Harden is used in lineup 4 at 53fpts, so now Harden's projection reverts back to 50 fpts. 

So its an infinite cycle based on the # of n lineups requested that applies to every player in the player pool. 
 
I would like to simultaneously do this for the entire player pool so mid projected, mid salary guys are not passed over for studs and value plays when making 150 lineups. This creates a nice mix of lineups that are competitive and also not relying on random() projections, or max/min exposures. 

How would I go about doing this? Ideally, it would be column in the CSV called something like Proj+ where you can set the % increase of each players projections when they aren't used in a lineup. This would be a great feature and with the limited testing I've done, is a very valuable addition. Thank you!

**Comment by Owen-Slater** [comment]
<img width="958" alt="Screen Shot 2021-04-03 at 12 14 27 PM" src="https://user-images.githubusercontent.com/81867834/113484422-33244980-9476-11eb-8a8a-3ed65deba0cd.png">

Here is a 'visual' representation of what I am asking to achieve in pydfs

**Comment by McCampy** [comment]
I just wanted to add that this reminds me of the shuffle feature on DailyRoto's optimizer but inverted. Their feature decreases a player's projection as they are filled into more and more lineups to account for the diminishing marginal utility of the player. This seems like it will effectively do the same thing.

**Comment by Owen-Slater** [comment]
@McCampy yes. I didn't realize that DailyRoto did this, but essentially similar/same thing I think. I'm not sure if their is a benefit to one way or the other.

**Comment by Owen-Slater** [comment]
@DimaKudosh  this feature is working great!  Thank you for the quick implementation! .... Eventually keeping the Progressive Projections % as a column in the CSV would be great so you can set individual % increase. 
Also, a Maximum Projection % that stays within The Projected Ceiling Column would be the finishing touch. Great and ty.

**Comment by lightninglarry** [comment]
@Owen-Slater can you help me and show me how to implement this strategy?

larry.mcdonald002@gmail.com is my email.
unless we can DM here?

**Comment by DimaKudosh** [comment]
Add ability to change scale for specific player, released this feature in version 3.5.0
