### ISSUE TITLE
Fanduel Export

### ISSUE THREAD

**Issue by jecarnes** [DimaKudosh/pydfs-lineup-optimizer#260]
For some reason the export file is not working.  What settings should I have to export for Fanduel

currently using 

optimizer.export('fdmlbmme.csv')

**Comment by DimaKudosh** [comment]
You can remove Budget and FPPG columns from the first row in generated file and it should work. I'll fix it in future release

**Comment by jecarnes** [comment]
here is the format it is  exporting

Dustin May(57100-82594) | Wilson Ramos(57100-12123) | Max Muncy(57100-52176) | Justin Turner(57100-6312) | Jazz Chisholm Jr.(57100-82527) | Ronald Acuna Jr.(57100-79756) | Adam Duvall(57100-38117) | Akil Baddoo(57100-82611) | Renato Nunez(57100-53725)
-- | -- | -- | -- | -- | -- | -- | -- | --


here is what it should be

57100-5466 | 57100-52176 | 57100-85504 | 57100-38976 | 57100-38412 | 57100-17086 | 57100-73159 | 57100-17097 | 57100-79401
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by DimaKudosh** [comment]
Fixed in version 3.5.0
