### ISSUE TITLE
Can You Lock a Player Into a Single Position?

### ISSUE THREAD

**Issue by jamesanglin** [DimaKudosh/pydfs-lineup-optimizer#263]
Is it possible to lock a player into a position, even if they qualify for multiple positions?

**Example**
Sport: Basketball
Site: DraftKings
Game Type: Classic

If I lock the player Trae Young, who is a PG, can I make the optimizer ONLY put him in the PG slot in all lineups? (Even though he qualifies for G and UTIL also).

### Lineups
**Wanted**
PG    Trae Young
...
G       Anyone Else
UTIL  Anyone Else

**NOT Wanted**
PG     Anyone Else
...
G       Trae Young
...

**NOT Wanted**
PG     Anyone Else
...
UTIL  Trae Young

**Comment by lightninglarry** [comment]
good question, im following

**Comment by DimaKudosh** [comment]
Currently locking a player to a specific position is not implemented

**Comment by jamesanglin** [comment]
@DimaKudosh thanks for following up. Do you have a protocol for requesting features? I would love to have an option to add a rule that adds this strict position locking constraint.

**Comment by DimaKudosh** [comment]
@jamesanglin I'll add this feature

**Comment by jamesanglin** [comment]
Thanks @DimaKudosh . I can't express just how much I appreciate all your extremely hard work on this project! You have created something really great here.

**Comment by DimaKudosh** [comment]
In version 3.6.1 I refactored methods with player pool and added the ability to lock player in specified position, like this:
```
optimizer.player_pool.lock_player('Trae Young', 'PG')
```
