### ISSUE TITLE
Walk me through install and use optimizer on python 3.9.4 plz

### ISSUE THREAD

**Issue by KyzerX** [DimaKudosh/pydfs-lineup-optimizer#264]
I type in python 3.9.4
Pip install pydfs-lineup-optimizer
And I keep getting 
File "<stdin>" line 1
What am I doing wrong

**Comment by KyzerX** [comment]
Stdin

**Comment by DimaKudosh** [comment]
You are trying to run pip commands in python console, you can read how to install packages using pip here https://docs.python.org/3/installing/index.html

**Comment by KyzerX** [comment]
Why did you close it
