### ISSUE TITLE
NBA Fanduel Single Game names/tied to id setting?

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#271]
Since I believe I read that you cant lock guys in certain spots in a lineup(MVP,STAR,PRO,UTIL).  What setting can I update to spit out this format?

59370-40199:Giannis   Antetokounmpo - MVP

59370-55062:Nikola   Jokic - STAR

59370-14528:Jimmy   Butler - PRO

59370-84717:Anfernee Simons  no need for a position here as its UTIL.

currently every spot spits out just something like this 59370-14528 so without writing names tied to numbers, i dont know who is what.  Is this possible a setting i can change?

--

--

--

**Comment by lightninglarry** [comment]
Does anyone have any insight on this?

**Comment by DimaKudosh** [comment]
Do you mean format in the export file? If so you can override exporter and use another format:
```
from pydfs_lineup_optimizer.lineup_exporter import FanDuelCSVLineupExporter

class CustomExporter(FanDuelCSVLineupExporter):
    @staticmethod
    def render_player(player):
        result = f'{player.id}:{player.full_name}'
        if player.lineup_position != 'UTIL':
           result += f' - {player.lineup_position}'
        return result

optimizer = get_optimizer()  # create optimizer
optimizer.settings.csv_exporter = CustomExporter  # replace default exporter with custom

```

**Comment by lightninglarry** [comment]
> Do you mean format in the export file? If so you can override exporter and use another format:
> 
> ```
> from pydfs_lineup_optimizer.lineup_exporter import FanDuelCSVLineupExporter
> 
> class CustomExporter(FanDuelCSVLineupExporter):
>     @staticmethod
>     def render_player(player):
>         result = f'{player.id}:{player.full_name}'
>         if player.lineup_position != 'UTIL':
>            result += f' - {player.lineup_position}'
>         return result
> 
> optimizer = get_optimizer()  # create optimizer
> optimizer.settings.csv_exporter = CustomExporter  # replace default exporter with custom
> ```

Thanks for the help on this @DimaKudosh .  It was working, until yesterday.  Was there an update?  The output now, basically overrides what you have typed and here is the sample output.
This is the any slot
Playername(#####-#####).


What are your thoughts?

**Comment by lightninglarry** [comment]
> from pydfs_lineup_optimizer.lineup_exporter import FanDuelCSVLineupExporter
> 
> class CustomExporter(FanDuelCSVLineupExporter):
>     @staticmethod
>     def render_player(player):
>         result = f'{player.id}:{player.full_name}'
>         if player.lineup_position != 'UTIL':
>            result += f' - {player.lineup_position}'
>         return result
> 
> optimizer = get_optimizer()  # create optimizer
> optimizer.settings.csv_exporter = CustomExporter  # replace default exporter with custom

having a hard time, and i dont know why.  This code seems right, but im getting

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-35445bf2d533> in <module>
      9         return result
     10 
---> 11 optimizer = get_optimizer(Site.FANDUEL_SINGLE_GAME, Sport.BASKETBALL)
     12 optimizer.settings.csv_exporter = CustomExporter  # replace default exporter with custom
     13 optimizer.load_players_from_csv(r"C:\Users\brand\Downloads\FanDuel-NBA-2021 ET-07 ET-03 ET-61263-players-list.csv")

NameError: name 'get_optimizer' is not defined




it works sometimes, doesnt others.  Suggestions?
