### ISSUE TITLE
FanDuel Single Game Min Max Exposure

### ISSUE THREAD

**Issue by bigboyz** [DimaKudosh/pydfs-lineup-optimizer#273]
Doesn't appear that when loading min/max exposure straight from a csv file per player that PYDFS recognizes the exposure percentages.  

For example:  I want to limit Luka tonight to 75% of my FanDuel single game, but because of the projection I have for him he is still in 100% of my lineups even though I am listing him as .75 in the CSV file for max_exposure.  Works for all the other slates though.

**Comment by bigboyz** [comment]
This is fixed by simply reducing the exposure by 75% to account for 4 possible positions per each player (MVP, STAR, PRO, UTIL)

**Comment by lightninglarry** [comment]
Im curious what your upload file looks like for a single game.  Can you share it. Currently i create WAY too many lineups and just weed them out via excel to trim my exposure down on single games.
