### ISSUE TITLE
Multiple Projection Source Columns in CSV for Optimization [Question] [Help] [Enhancement]

### ISSUE THREAD

**Issue by Owen-Slater** [DimaKudosh/pydfs-lineup-optimizer#276]
I know that using ranges of projections, random, ceiling, floor, etc. are all easily done with a single projection set. I currently use the CSV method that reads the FPPG column and loads my projections into pydfs optimizer. This is best because it makes for quick and easy upload of lineups. 

What I would like to do is use multiple projection sets when optimizing 150 lineups all with the same settings, constraints, exposures, etc, and also not create any duplicate lineups. 

So as an example I have the FD CSV file setup as columns with FPPG1, FPPG2, FPPG3, FPPG4, FPPG5, and I want to set the pydfs script to optimize 30 lineups per FPPG Column for a total of 150 lineups.  How would I go about this? If I run the pydfs optimizer separately, and just loop the optimizer  for each projection set, then exposures / stacks / etc. are reset, duplicate lineups are sometimes created, etc. Its not the same process I'm trying to achieve. Its also tedious to run the script 5 times and append projections, and remove duplicates, etc.....
Below isn't code I am trying to run, obviously this won't work, but this should give you an idea of what I _want_ to achieve as I know sometimes I don't articulate the question in an easy to understand way:

```
N= {FPPG 1 = 30, FPPG 2 = 30, FPPG 3 = 30, FPPG 4 = 30, FPPG 5 = 30}

optimizer = get_optimizer(Site.FANDUEL, Sport.BASEBALL)
optimizer.load_players_from_csv(CSV_FILENAME)
for lineup in optimizer.optimize(N):
optimizer.export('MLB.csv')
```
<img width="500" alt="Screen Shot 2021-07-03 at 2 11 09 PM" src="https://user-images.githubusercontent.com/81867834/124363404-06b0d280-dc09-11eb-8d76-8f43080d5e35.png">

So to reiterate, I just want to create X number of lineups from each projection column when running pydfs. This way all of the constraints such as stacks/exposures/uniques/etc. are applied to the whole group of lineups. 

This should be labeled as Question, Help, Enhancement, Not an Issue :)

@sansbacon 
@DimaKudosh 

Thank you in advance for your time, consideration and help

**Comment by DimaKudosh** [comment]
I'll add the ability to exclude lineups before optimizations in the next release. So you can exclude lineups from the previous step on the current step. For now, you can try to store all lineups in set for avoiding duplicates, but it will produce less than 150 lineups.

**Comment by DimaKudosh** [comment]
You can run optimizer multiple times with different projections and exclude lineups from the previous steps: [docs](https://pydfs-lineup-optimizer.readthedocs.io/en/latest/usage.html#exclude-lineups)
