### ISSUE TITLE
MLB Stack question

### ISSUE THREAD

**Issue by mbencho** [DimaKudosh/pydfs-lineup-optimizer#278]
I'm trying to stack three teams with a 5-4-1 for Draftkings but I always want the 1 to be a SP and the five to be a SP+four bats. Has anyone had any success with this configuration? I can't figure out if it's possible with the current add_stack or if I need to do some modifications. any thoughts appreciated. thanks!

**Comment by DimaKudosh** [comment]
You can use PositionsStack:
```
from pydfs_lineup_optimizer import PositionsStack

HITTERS = ('1B', '2B', '3B', 'SS', 'C', 'OF')
optimizer.add_stack(PositionsStack(
    ['SP', *([HITTERS] * 4)]
))
optimizer.add_stack(PositionsStack(
    [HITTERS] * 4
))
```

**Comment by mbencho** [comment]
This works great. Thanks!

**Comment by lightninglarry** [comment]
@DimaKudosh can you include spacing into this?

Im having an issue with TeamStack, sometimes it includes the P which is something I do not want to do.  Is there a workaround that?
