### ISSUE TITLE
How to constrain which positions allowed in Flex

### ISSUE THREAD

**Issue by jjf9** [DimaKudosh/pydfs-lineup-optimizer#28]
Hi - I'm referring to Draftkings NFL. I've loaded my metrics into the optimizer and it appears that every flex player is a TE in the output. I'm not sure how I can apply a constraint here to allow only WR, RB, in Flex, or just WR in Flex, etc. Thanks

**Comment by DimaKudosh** [comment]
Hi, you can't exclude specific position from UTIL choices, maybe I will add this feature in next release. For now you can only set one specific position that will be used for UTIL using this method `optimizer.set_players_with_same_position({'WR': 1})`
