### ISSUE TITLE
Team Exposure

### ISSUE THREAD

**Issue by bigboyz** [DimaKudosh/pydfs-lineup-optimizer#285]
Is there a way to limit exposure to a given team.  Let's say the Cubs play today and a rainout is 50/50, the matchup is great so I don't want to miss it completely, but lets say I just want 10% exposure to the game.

I see we can do this in stacks specifically, but is that available in overall team exposure?

**Comment by mbencho** [comment]
optimizer.add_stack(PositionsStack(['QB', 'WR'], max_exposure=0.5, max_exposure_per_team={'MIA': 0.6}))  # stack QB and WR  with 0.5 exposure for all team stacks and 0.6 exposure for MIA


https://pydfs-lineup-optimizer.readthedocs.io/en/latest/rules.html#team-stack

I think this example is what you are looking for

**Comment by bigboyz** [comment]
Gave that a shot, but no luck.  Looking more for a way to leave my projections intact, stacks, etc...but because there is a 50/50 chance a game gets rained out etc...I don't want anymore than 10% of my lineups to have exposure to the Cubs.  The matchup is so great though that if they play its likely some of those players will end up in the perfect slate, so I want a little exposure knowing that every lineup with a Cubs player will be a win or loss depending on the game status that night.

So if I build 150 lineups, 15 will have Cubs players scattered in there, but 135 will have no exposure to the Cubs.

Guess not that big of a deal.  Currently, I just build 15 with the exposure and then reduce the teams projections in that game to zero on a second run of 135 lineups.  Would be nice to do it in a single build though
