### ISSUE TITLE
CSV Field/Column Question

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#287]
Besides what is standard in a player list file from either Draftkings or Fanduel, what are other field names I can add to the file to use for pydfs?  Is there a list somewhere?

is projected_ownership one? 

Just trying to be completely ready for NFL season which is upon us.  New to coding so i ask a lot of questions.

**Comment by DimaKudosh** [comment]
There is no single place for all fields they are specified in different places in docs. I'll add them in a single place in the doc. Extra fields are: `Roster Order, Projection Floor, Projection Ceil, Max Exposure, Min Exposure, Projected Ownership, Min Deviation, Max Deviation, Confirmed Starter, Progressive Scale`

**Comment by DimaKudosh** [comment]
Add page with all extra columns to [docs](https://pydfs-lineup-optimizer.readthedocs.io/en/latest/usage.html#additional-columns-in-csv)
