### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Pro1spect** [DimaKudosh/pydfs-lineup-optimizer#289]
I got a question @DimaKudosh and others, 1) how do you stop the optimizer from picking bench players like for MLB? I put a negative 100 projections for batters who are not in the lineup and the optimizer still pick these bats,

and 2) in a 5 players stack, how do you stop the optimizer from including a pitcher as one of the 5 players stack?

Thanks.

**Comment by Denwen12** [comment]
Delete them from the csv or put a comment under injury column

**Comment by DimaKudosh** [comment]
1) You can remove a player from the optimization using remove_player method.
2) You can set positions that should be used in stack: `optimizer.add_stack(TeamStack(5, for_positions=['1B', '2B', '3B', 'C', 'SS', 'OF']))` or if you want make it for whole lineup you can use method `optimizer.restrict_positions_for_same_team(('SP', '1B'), ('SP', '2B'), ...etc)`

**Comment by Pro1spect** [comment]
> 1. You can remove a player from the optimization using remove_player method.
> 2. You can set positions that should be used in stack: `optimizer.add_stack(TeamStack(5, for_positions=['1B', '2B', '3B', 'C', 'SS', 'OF']))` or if you want make it for whole lineup you can use method `optimizer.restrict_positions_for_same_team(('SP', '1B'), ('SP', '2B'), ...etc)`

Thanks.
But for 1) in MLB there will be like (depending on the slate) over 1000+ players with zero points because they are not playing, beside deleting them from the csv, is there a way to make the optimizer to not pick those players?

**Comment by DimaKudosh** [comment]
You can remove all players with 0 points:
```
for player in optimizer.players:
    if player.fppg == 0:
        optimizer.remove_player(player)
```

**Comment by Pro1spect** [comment]
Thanks.
