### ISSUE TITLE
NFL 3 man with a bring back

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#290]
Whats the easiest way with the stacking syntax to get min 2 passcatchers(WR,TE) with my Qb and a bringback(preferrably a wr) from the opposition.

Example.

Lets say i want to run 20 lineups
And only want these 3 qbs
Mahomes, Allen, Prescott

in my Mahomes stacks - id want a minimum 2 of Tyreek, Mecole, Robinson, and Kelce + at least one opposition
Allen - minimum 2 of Diggs, Beasley, Davis, McKenzie, Knox + at least one opposition
Prescott - minimum of 2 Jarwin, Cooper, Lamb, Gallup + at least one opposition?

i tried this line, but it sometimes gives me 3 guys not even with a qb just 3 players from one team: like 3 steelers with no big ben type lineups.

optimizer.add_stack(TeamStack(3, for_positions=['QB', 'WR', 'TE'], for_teams=['DAL', 'ARI', 'BUF', 'KC']))  # stack 3 players with any of specified positions
optimizer.force_positions_for_opposing_team(('QB', 'WR'))

**Comment by DimaKudosh** [comment]
Try to use positions stack:
```
optimizer.add_stack(PositionsStack(['QB', 'WR', ('WR', 'TE')], for_teams=['DAL', 'ARI', 'BUF', 'KC']))
```

**Comment by lightninglarry** [comment]
worked great. Closing
