### ISSUE TITLE
Custom Stacks

### ISSUE THREAD

**Issue by dachel12** [DimaKudosh/pydfs-lineup-optimizer#291]
Could a minimum exposure be set for custom stacks or a way to set a stack to a specific lineup within a set of x lineups? I only see capability to identify max exposure. I have been trying to run lineups with specific stacks in NFL, but the lineup results only contain a fraction of them. I was using the "PlayersGroup" to set stacks and "optimizer.add_stack(Stack(" to add the stacks to the optimizer. However, with only being able to set max exposure for each stack, I don't know that I can set anything up to guarantee all my stacks get into my lineups.

**Comment by lightninglarry** [comment]
can you give an example or 2, i may be able to help you with your question @dachel12

**Comment by dachel12** [comment]
I was testing it out with 150 unique stacks and capping max exposure to just over 1/150
Stack1 = PlayersGroup([optimizer.get_player_by_name(name) for name in ('Gardner Minshew II', 'DJ Chark Jr.', 'Keelan Cole', 'Will Fuller V', 'Jamison Crowder', 'Kenyan Drake')], max_exposure=0.0073)
optimizer.add_stack(Stack([Stack1,Stack2.....Stack150]))

But when I look at the results I can clearly see that I'm getting too much of certain qbs. So I know that the stacks did not work as I hoped they would. Thanks for taking a look

**Comment by lightninglarry** [comment]
so one more question I have, are you getting all the qbs from your custom stacks?  Im guessing you are saying this part of the code isnt working (max_exposure=0.0073) as your saying your getting too much of some, not enough of others?
