### ISSUE TITLE
Playerrank

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#296]
I use my LOL code before but now I can't get it to work @DimaKudosh 
I'm getting 

from pydfs_lineup_optimizer.constants import PlayerRank
ImportError: cannot import name 'PlayerRank' from 'pydfs_lineup_optimizer.constants' (/usr/local/lib/python3.7/dist-packages/pydfs_lineup_optimizer/constants.py)

Use to work just fine

**Comment by Denwen12** [comment]
Code I'm using and it use to work 
`from collections import Counter
from itertools import chain
from pydfs_lineup_optimizer.constants importPlayerRank
from pydfs_lineup_optimizer.stacks import PositionsStack, PlayersGroup, NestedPlayersGroup, OptimizerStack
from pydfs_lineup_optimizer.utils import get_players_grouped_by_teams, list_intersection


class PositionsStackWithStar(PositionsStack):
    def build_stacks(self, players, optimizer):
        players_by_teams = get_players_grouped_by_teams(players, for_teams=self.for_teams)
        all_positions = tuple(set(chain.from_iterable(self.positions)))
        positions_for_optimizer = Counter(self.positions)
        positions_for_optimizer[all_positions] = len(self.positions)
        all_groups = []
        for team_name, team_players in players_by_teams.items():
            groups = []
            groups.append(PlayersGroup(
                players=[player for player in team_players if
                         player.rank == PlayerRank.STAR],
                min_from_group=1,
            ))
            for positions, total in positions_for_optimizer.items():
                groups.append(PlayersGroup(
                    players=[player for player in team_players if
                             list_intersection(player.positions, positions) and
                             player.rank == PlayerRank.REGULAR],
                    min_from_group=total,
                ))
            nested_group = NestedPlayersGroup(
                groups=groups,
                max_exposure=self.max_exposure_per_team.get(team_name, self.max_exposure),
            )
            all_groups.append(nested_group)
        return [OptimizerStack(groups=all_groups)]`

**Comment by Denwen12** [comment]
I believe you removed some stuff for this to work since I tried an older version and it works again

**Comment by DimaKudosh** [comment]
Yes, this code was removed some time ago and replaced with the creation of multiple separate players for each slot as it does in DK, you need to update your code.
