### ISSUE TITLE
FanDuel football lineups are bad

### ISSUE THREAD

**Issue by BigWinston** [DimaKudosh/pydfs-lineup-optimizer#3]
Hey,

Nice work!  Like your library a lot but I'm seeing some issues when creating FanDuel football lineups...

The lineups get generated, but are not optimal - it doesn't function as expected after observing the correct behavior when running through the test CSV file.  _(# Note: I am using a local copy of the source as I found that the pip install is not the latest version.  The only modification I have made is round the FPPG output display for each player selected in a lineup)._

For example, for one of today's FanDuel lobby games, these are the outputs I get are listed below.

Attached is the FanDuel file used.
[FanDuel-NFL-2016-12-18-17288-players-list.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/654863/FanDuel-NFL-2016-12-18-17288-players-list.zip)

Thanks.

BW

Connected to pydev debugger (build 163.8233.8)
1. LeSean McCoy                  ['RB']BUF            18.15 9000.0$   
2. Matt Barkley                  ['QB']CHI            11.06 6200.0$   
3. Sterling Shepard              ['WR']NYG            9.02  5300.0$   
4. Jeremy Kerley                 ['WR']SF             7.05  4900.0$   
5. Justin Hardy                  ['WR']ATL            4.04  4900.0$   
6. Dorial Green-Beckham          ['WR']PHI            5.85  4900.0$   
7. Matt Prater                   ['K']DET            10.0  4800.0$   
8. Shaun Draughn                 ['RB']SF             5.32  4700.0$   
9. Austin Hooper                 ['TE']ATL            4.72  4600.0$   
Fantasy Points 75.2119592009
Salary 49300.0
1. Ryan Mallett                  ['QB']BAL            -0.01 6000.0$   
2. Taylor Heinicke               ['QB']MIN            0.0   5000.0$   
3. Raheem Mostert                ['RB']SF             -0.25 4500.0$   
4. Jalston Fowler                ['RB']TEN            0.95  4500.0$   
5. Tavarres King                 ['WR']NYG            0.55  4500.0$   
6. Devin Hester                  ['WR']BAL            -0.17 4500.0$   
7. Robbie Gould                  ['K']NYG            3.71  4500.0$   
8. Danny Vitale                  ['TE']CLE            0.05  4500.0$   
9. Lucky Whitehead               ['WR']DAL            0.97  4500.0$   
Fantasy Points 5.80095241378
Salary 42500.0
1. Ryan Mallett                  ['QB']BAL            -0.01 6000.0$   
2. Raheem Mostert                ['RB']SF             -0.25 4500.0$   
3. Jalston Fowler                ['RB']TEN            0.95  4500.0$   
4. Keshawn Martin                ['WR']SF             -2.0  4500.0$   
5. Tavarres King                 ['WR']NYG            0.55  4500.0$   
6. Devin Hester                  ['WR']BAL            -0.17 4500.0$   
7. Robbie Gould                  ['K']NYG            3.71  4500.0$   
8. Danny Vitale                  ['TE']CLE            0.05  4500.0$   
9. Lucky Whitehead               ['WR']DAL            0.97  4500.0$   
Fantasy Points 3.80095241378
Salary 42000.0
1. Ryan Mallett                  ['QB']BAL            -0.01 6000.0$   
2. Raheem Mostert                ['RB']SF             -0.25 4500.0$   
3. Jalston Fowler                ['RB']TEN            0.95  4500.0$   
4. Tony Washington               ['WR']JAC            0.8   4500.0$   
5. Keshawn Martin                ['WR']SF             -2.0  4500.0$   
6. Tavarres King                 ['WR']NYG            0.55  4500.0$   
7. Devin Hester                  ['WR']BAL            -0.17 4500.0$   
8. Robbie Gould                  ['K']NYG            3.71  4500.0$   
9. Danny Vitale                  ['TE']CLE            0.05  4500.0$   
Fantasy Points 3.63428572725
Salary 42000.0
1. Ryan Mallett                  ['QB']BAL            -0.01 6000.0$   
2. Taylor Heinicke               ['QB']MIN            0.0   5000.0$   
3. Raheem Mostert                ['RB']SF             -0.25 4500.0$   
4. Jalston Fowler                ['RB']TEN            0.95  4500.0$   
5. Keshawn Martin                ['WR']SF             -2.0  4500.0$   
6. Tavarres King                 ['WR']NYG            0.55  4500.0$   
7. Devin Hester                  ['WR']BAL            -0.17 4500.0$   
8. Robbie Gould                  ['K']NYG            3.71  4500.0$   
9. Danny Vitale                  ['TE']CLE            0.05  4500.0$   
Fantasy Points 2.83428571533
Salary 42500.0

**Comment by DimaKudosh** [comment]
Fixed in 0.4.3
