### ISSUE TITLE
Is there a way to set minimum exposure?

### ISSUE THREAD

**Issue by salland11** [DimaKudosh/pydfs-lineup-optimizer#30]
Hello,

I have been playing around with this program for several weeks and i keep running into the problem that i cannot set minimum exposure without forcing the player/players into the top lineups the optimizer spits out. So say I want to have Duke Johnson Jr. in at least 10% of my lineups but I don't want to force him into the first few lineups (using the add player function), is there a way to do this? This mainly comes up when I have several players that i want at low ownership and they may not be optimal so they don't get spit out in any of the 40+ lineups naturally thus forcing me to make them be in the first 5-10. Any time i want multiple sub optimal players it will try to force them into the same lineup which isn't quite what im going for with the idea. Any help is appreciated and thanks for the awesome groundwork.

**Comment by BenBrostoff** [comment]
@salland11 / @DimaKudosh  - I'm actually in the middle of attempting to [implement this in my optimizer](https://github.com/BenBrostoff/draft-kings-fun/pull/84). One issue I'm having is how to make the determination of what to do *after* the min exposure is reached. Said another way, what logic should be used to determine how far beyond the min (or below the max) to go? There are a couple solutions I'm thinking:

- Make the whole problem an optimization - this requires the most work and I'm not sure how to make this work with solver libraries available
- Allow the user to pass in a custom function that shows how to rank players (if a player has reached their min exposure, choose who to lock in next based on value or minutes or some other metric)

In both solutions, there's the problem of the user passing in impossible min exposures (say for NBA they request 100% exposure for 5 point guards), so this is another thing to think about when implementing.

**Comment by salland11** [comment]
@benbrostoff Would it be possible to pass the percentage as an exact number for now? For example if I want Andrew Luck in exactly 20 % of lineups along with other players being in exactly 5-10% of lineups, would that be easier than having a min and a max exposure. I'm not sure how a min exposure would work because it seems like it would have to check after all the lineups are created and see if the player is populated enough times. The max exposure seems to just count as it goes and knows when it hits x% of your n lineups.

**Comment by BenBrostoff** [comment]
@salland11 Yes, this is a much easier ask at least for me. It's important at least in my opinion to be smart about how this is done - let's say you want Luck in 50% of lineups and you're generating 20 total. The naive way to do it would be to force the optimizer to lock him in the first 10 and then ban him in the next 10.  The better way I think is to get Luck in the first lineup, then ban him in the next and so on (so he is always at max 50% on each optimizer run - 1 in 2, 1 in 3, 2 in 4, 2 in 5, 3 in 6, etc.). Multiple players is a little trickier because let's say you want Luck and Todd Gurley in 50% - should they always be separate or should they be paired? This is where unfortunately the code has to be opinionated unless you have ideas for some way the user can specify what they want.

**Comment by DimaKudosh** [comment]
I think best approach in this case is generate best optimal lineups and if player with min exposure doesn't appear in generated lineups add it at the end. For example we want to generate 10 lineups and set 30% min exposure for Lebron James, so we want at least 3 lineup with James. Firstly we generate best optimal lineup, if Lebron in this lineup we decrease counter for him, if LJ not in lineup we check how many lineups left, if this number > than number of lineups for LJ, we will generate second optimal lineup, if this number equal we lock LJ for next lineup. I think this will be better than forcing player in first n lineups.
