### ISSUE TITLE
max / min ownership

### ISSUE THREAD

**Issue by dachel12** [DimaKudosh/pydfs-lineup-optimizer#303]
I am trying to use the optimizer.set_projected_ownership(max_projected_ownership=0.6) rule, but the optimizer is not following the rules I set for the max/min ownership. I have my projected_ownership in the salaries csv, so it should be pulling it in, but when I check the lineups that were generated, the ownerships are not within the range I specify.

**Comment by Denwen12** [comment]
It should be named projected ownership without the underscore

**Comment by dachel12** [comment]
Wish that was it, but doesn't seem to have changed anything. The lineups run with no issue or error. Just the ownership projections are not taken into consideration

**Comment by dachel12** [comment]
@Denwen12  Have you checked your lineups after the fact for ownership? I keep trying different things, but ultimately the final lineups I get are not following the rule. Also, looking through the code i am confused if I should be entering a max value for total ownership or averaging that value across the 9 players in an NFL lineup. Appreciate any help I can get

**Comment by dachel12** [comment]
finally got it, but had to make several changes to various parts of the code
