### ISSUE TITLE
Limit MVP and Star Positions on Fanduel MLB Single Game

### ISSUE THREAD

**Issue by jsst28** [DimaKudosh/pydfs-lineup-optimizer#306]
In previous versions of this optimizer, I was able to limit players in single contests through this setup (which was given to me by Dima). It doesn't work for current versions of the optimizer, so I was wondering if there was another way to limit exposure in similar ways for single game contests. Thanks!

my_mvps = ['Jayson Wilson']
for player in optimizer.players:
    if player.is_mvp and player.full_name not in my_mvps:
        optimizer.remove_player(player)

my_stars = ['Goran Shake','Clint Horton', 'De’Andre Hunter']
for player in optimizer.players:
    if player.is_star and player.full_name not in my_stars:
        optimizer.remove_player(player)

my_pros = ['Clint Horton', 'De’Andre Hunter', 'Daniel Theis']]
for player in optimizer.players:
    if player.is_pro and player.full_name not in my_pros:
        optimizer.remove_player(player)

**Comment by DimaKudosh** [comment]
is_mvp, is_star and is_pro attributes were removed some versions ago, and positions are used like in draftkings, so you should check positions instead of these attributes. Or can achieve it with player group:
```
optimizer.add_players_group(PlayersGroup([
        *optimizer.player_pool.get_players('Jayson Wilson', PlayerFilter(positions=['MVP'])),
        *optimizer.player_pool.get_players('Goran Shake','Clint Horton', 'De’Andre Hunter', PlayerFilter(positions=['STAR'])),
        *optimizer.player_pool.get_players('Clint Horton', 'De’Andre Hunter', 'Daniel Theis', PlayerFilter(positions=['PRO'])),
    ], min_from_group=3
))
```

**Comment by lightninglarry** [comment]
@DimaKudosh how would you negate a player from showing up in the UTIL.  Superstar players in the NBA (Lebron type, should always be played in the 3 categories you have outlined(mvp,star,pro).  But never the UTIL as his cost would kill your lineup if not getting the multiplier.

How would u have Lebron NOT be able to be the UTIL spot?
