### ISSUE TITLE
Sport.NHL???

### ISSUE THREAD

**Issue by Bloodwolfx7** [DimaKudosh/pydfs-lineup-optimizer#307]
File "<ipython-input-4-9ed034e48e3a>", line 1
    Optimizer = get optimizer(Site.FANDUEL Sport.HOCKEY

SyntaxError: invalid syntax

So that keep showing up was wondering what is the code you use for code letting the program know that you want to play certain sports and can I get a list please

**Comment by mbencho** [comment]
they are in the settings file for each site/contest style 

https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/sites/fanduel/classic/settings.py

syntax error may be that you are missing a comma between "Site.FANDUEL Sport.HOCKEY" 

should be:
optimizer = get_optimizer(Site.FANDUEL, Sport.HOCKEY)

**Comment by Bloodwolfx7** [comment]
Thank you
