### ISSUE TITLE
MMA FD Q

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#318]
since FDs csv doesnt list opponent, i make a seperate playersgroup for each fight to max from 1 since i dont want fighters fighting each other in same lineup.

fight1= PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Tagir Ulanbekov', 'Allan Nascimento')], max_from_group=1)
optimizer.add_players_group(fight1)

fight2= PlayersGroup([optimizer.get_player_by_name(Nickname) for Nickname in ('Hu Yaozong', 'Andre Petroski')], max_from_group=1)
optimizer.add_players_group(fight2)

etc for the whole card.

Run into this error after the new update. 

players)
    172         if players:
    173             if len(players) > 1:
--> 174                 raise LineupOptimizerException('More than 1 player is found for: %s' % player_name)
    175             return list(players)[0]
    176         if self.search_threshold:

LineupOptimizerException: More than 1 player is found for: Tagir Ulanbekov

So its not getting past first fighter.  
Heres my import
from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
from pydfs_lineup_optimizer.stacks import TeamStack, PositionsStack, PlayersGroup
from pydfs_lineup_optimizer import AfterEachExposureStrategy
from pydfs_lineup_optimizer import PlayerFilter

class CustomExporter(CSVLineupExporter):
    @staticmethod
    def render_player(player):
        result = f'{player.id}:{player.full_name}'
        if player.lineup_position != 'UTIL':
           result += f' - {player.lineup_position}'
        return result
        
optimizer = get_optimizer(Site.FANDUEL, Sport.MMA)
optimizer.settings.csv_exporter = CustomExporter  # replace default exporter with custom
optimizer.load_players_from_csv(r"C:\Users\brand\Downloads\FanDuel-MMA-2021 ET-10 ET-30 ET-66119-players-list.csv")

 Any ideas @DimaKudosh

**Comment by Owen-Slater** [comment]
Hey, so I run this a completely different way. I make the Fighters a 'team' and use Team column , min. teams rule. Very simple. Works perfectly. Here's my Example:
Team (this is a column in CSV you add)
Land vs Klein
Sanchez vs Silva

optimizer.set_total_teams(min_teams=5)

using min_teams=5 means that you will only get one player from each fight assuming you have 5 positions to fill.... There are many ways to do this, but this is quick and easy if you are setting the vs fighter column make it a Team column

<img width="1244" alt="Screen Shot 2021-10-30 at 12 31 43 PM" src="https://user-images.githubusercontent.com/81867834/139541457-aad6cca7-e058-484f-8faf-32375aded56a.png">

**Comment by Owen-Slater** [comment]
@lightninglarry

**Comment by lightninglarry** [comment]
> @lightninglarry

Thanks for this, this helps a lot and saves time @Owen-Slater.
Team is already a csv column so i did as your example stated, but now i get this.  Any ideas?


GenerateLineupException: Can't generate lineups. Following constraints are not valid: positions_F,total_players

**Comment by Owen-Slater** [comment]
@lightninglarry ..... This is currently working for me regarding the minimum teams (no fighter vs fighter). 

```
from pydfs_lineup_optimizer import Site, Sport, get_optimizer, TeamStack, PositionsStack, PlayersGroup

N = 2
CSV_FILENAME= "FD_MMA.csv"

optimizer = get_optimizer(Site.FANDUEL, Sport.MMA)
optimizer.load_players_from_csv(CSV_FILENAME)

optimizer.set_total_teams(min_teams=5)

for lineup in optimizer.optimize(N):
    print(lineup)

optimizer.export('MMA.csv')
optimizer.print_statistic()
```

**Comment by lightninglarry** [comment]
@Owen-Slater is your .csv in same folder as your script?

the FD_MMA.csv?

**Comment by Owen-Slater** [comment]
@lightninglarry  yes. but if your's isn't just need to add the file path

**Comment by lightninglarry** [comment]
i tried to taylor my file and put in same directory as my script.  Even called it the same file name as yours.

FileNotFoundError: [Errno 2] No such file or directory: 'FD_MMA.csv'

i use jupiter notebook if that matters to run this stuff.
@Owen-Slater

**Comment by Denwen12** [comment]
Can I see your script?

**Comment by lightninglarry** [comment]
from pydfs_lineup_optimizer import get_optimizer, Site, Sport, CSVLineupExporter
from pydfs_lineup_optimizer.stacks import TeamStack, PositionsStack, PlayersGroup
from pydfs_lineup_optimizer import AfterEachExposureStrategy
from pydfs_lineup_optimizer import PlayerFilter

N = 150
CSV_FILENAME= "FD_MMA.csv"

optimizer = get_optimizer(Site.FANDUEL, Sport.MMA)
optimizer.load_players_from_csv(CSV_FILENAME)

optimizer.set_total_teams(min_teams=5)

for lineup in optimizer.optimize(N):
    print(lineup)

optimizer.export(r"C:\Users\brand\Desktop\PYTHON\UFC\FDUPLOAD.csv")
optimizer.print_statistic()

**Comment by Denwen12** [comment]
What's the location of your input file and why is there an R in your export
code

**Comment by Denwen12** [comment]
In front of the output code

**Comment by lightninglarry** [comment]
Input file is in same location now as my script.  and the R reads the output file for tinkering, taking it all out and made it this, optimizer.export("FDUPLOAD.csv")


still gets the same error

**Comment by lightninglarry** [comment]
gonna try again this weekend @Denwen12 @Owen-Slater

**Comment by lightninglarry** [comment]
finally got it working @Owen-Slater I do appreciate it.  So strange that your player csv has to be in the same folder as your script.  All my other scripts look at my download folder and run fine.  This one will not.  I appreciate the help.

**Comment by lightninglarry** [comment]
@Owen-Slater So i got the code to work finally after I got around to it.
In the past I would use PlayersGroup to control title fights.  Where I would want at least 1 of the 5 round fighter.  min_from_group=1 like below.

#fight1 = PlayersGroup([optimizer.player_pool.get_player_by_name(Name) for Name in ('Ciryl Gane', 'Francis Ngannou')], max_from_group=1,min_from_group=1)
#optimizer.add_players_group(fight1)

ERROR
LineupOptimizerException: More than 1 player is found for: Ciryl Gane

know what i could do to remedy this?
