### ISSUE TITLE
Draftkings Basketball Keyerror

### ISSUE THREAD

**Issue by therollingbird** [DimaKudosh/pydfs-lineup-optimizer#32]
Hi when i try to do a basketball lineup im getting this error 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\importer.py", line 20, in import_players
    name = row['Name'].split()
KeyError: 'Name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 174, in load_players_from_csv
    self._players = csv_importer(filename).import_players()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\importer.py", line 32, in import_players
    raise LineupOptimizerIncorrectCSV
pydfs_lineup_optimizer.exceptions.LineupOptimizerIncorrectCSV: Incorrect csv format!
>>>

but i got the csv from draftkings

**Comment by sansbacon** [comment]
Can you attach the CSV file that you tried to load?

**Comment by sansbacon** [comment]
I just downloaded a DK salary file and had no problem on Linux. It could be something windows-specific, a problem with your specific csv file, or an error due to artifacts from opening the file and editing it.

**Comment by sansbacon** [comment]
I just downloaded a DK salary file and had no problem on Linux. It could be something windows-specific, a problem with your specific csv file, or an error due to artifacts from opening the file and editing it.

**Comment by therollingbird** [comment]
this is the nba salary i downloaded , and also i am using windows 10 and using python 3.7
[DKSalaries(1).zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/2626331/DKSalaries.1.zip)

i havent edited the file i just downloaded it

**Comment by sansbacon** [comment]
The problem is that DK provides two different files with the same name. The file you are using is the template for uploading lineups via csv. DK also provides a bare-bones salaries file. 

Don't get the salary data from Lineups ---> Download Template
Instead, in the lobby, click ENTER on a contest on the slate you want to play and, underneath the list of players, there will be a link to "Export to CSV." It should look like the attached file.
[nba.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/2626464/nba.zip)

**Comment by sansbacon** [comment]
This converts the template file into a salary file that you can load into the optimizer.

```
import csv
from itertools import islice
from pathlib import Path

templatefn = Path.home() / 'template.csv'
salfn = Path.home() / 'sal.csv'

with open(templatefn, 'r') as f, open(salfn,"w") as out:   
    reader = csv.DictReader(islice(f, 7, None))
    flds = [fld for fld in reader.fieldnames if fld != '']
    writer = csv.DictWriter(out, flds) 
    writer.writeheader()
    for row in reader:
        d = {k:v for k,v in row.items() if v != ''}
        writer.writerow(d)

```
