### ISSUE TITLE
Can't generate further lineups help

### ISSUE THREAD

**Issue by bluh32** [DimaKudosh/pydfs-lineup-optimizer#334]
Thanks so much for the optimizer, super cool.

I am testing building some lineups with a lot of constraints added -- and the optimizer sometimes fails out after x lineups.

Is there any easy way to have the optimizer export to csv the lineups it already generated before error?

Thanks in advance

**Comment by corey-Robinson1337** [comment]
Perhaps you could hold each generated lineup in another data structure, then catch the Failed to generate lineup exception. Then in your finally/catch block then create your csv based on your data structure filled with your lineups.

**Comment by bluh32** [comment]
Thanks so much Corey -- I think I can figure out how to make that work with your suggestion above.  Appreciate the help.

Will go ahead and close this issue.

**Comment by Denwen12** [comment]
Did you figure this out cause I like to also have this done?
