### ISSUE TITLE
max from one team

### ISSUE THREAD

**Issue by holmes72** [DimaKudosh/pydfs-lineup-optimizer#338]
I want to limit the number of players from a single team in any lineup.  I'm currently grouping players by team and setting a max_from_group on each group.  Is there a more elegant/simpler way to do this?  I see the attribute "max_from_one_team" but don't see how to modify this value.

**Comment by holmes72** [comment]
Sorry...this has been asked and answered.  It looks like if you want to adjust this value on the fly, this is as good as it gets.  Has anyone added a setter for this value?

**Comment by holmes72** [comment]
Looks like I added a setter.

In lineup_optimizer.py, within class LineupOptimizer add:
```
    def set_max_from_one_team(self, max: int):
        self.settings.max_from_one_team = max
```

Then you can call this when you're setting up your optimizer:
`opt.set_max_from_one_team(maxStack)`

**Comment by Denwen12** [comment]
I'm not sure how I can get this to work I want to limit the max players for 1 team to 3 from thunders today

**Comment by holmes72** [comment]
If you're saying "I want no more than three OKC players in any given line":
players = optimizer.player_pool.get_players(PlayerFilter(teams=['OKC']))
group = PlayersGroup(players, max_from_group=3)
optimizer.add_players_group(group)

**Comment by Denwen12** [comment]
Cam I use multiple group settings for every team

**Comment by holmes72** [comment]
I'm not a fan of "RTFM" responses, but it seems to apply here.  The answer is "yes", and I encourage you to check out the readthedocs site: https://pydfs-lineup-optimizer.readthedocs.io/en/latest/index.html

**Comment by Denwen12** [comment]
Thanks, I'll check it out.

**Comment by Denwen12** [comment]
I I got a question, why do I get this

Traceback (most recent call last):
  File "Fanduel2Finish2.py", line 62, in <module>
    players = optimizer.player_pool.get_players(PlayerFilter(teams=['MIN']))
NameError: name 'PlayerFilter' is not defined

**Comment by Denwen12** [comment]
Fixed it
