### ISSUE TITLE
Display Ceiling in exported CSV without using randomness

### ISSUE THREAD

**Issue by austinjohnson** [DimaKudosh/pydfs-lineup-optimizer#342]
Is there a way to see the potential ceiling of a lineup without using the randomness strategy? For example, I want to generate lineups based on FPPG but then analyze these lineups with the ceiling and floor.

**Comment by austinjohnson** [comment]
I also want to export these lineups to csv.

**Comment by austinjohnson** [comment]
An example would be this lineup is projected to score 125 fpts with a ceiling of 175 and a floor of 100.

**Comment by Denwen12** [comment]
do you still need this?
