### ISSUE TITLE
Adding in a new column in csv for custom settings

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#348]
Can we have a new column in csv we can use for custom data. I'd like to use like dvp or player value maybe.... something like "projected value" and we can use that data for whatever just like Ownership

**Comment by lightninglarry** [comment]
Yes.  Id like to incorporate Leverage as to what @Denwen12 described above.  Where we can clarify min/max leverage per lineup would be awesome.

**Comment by Denwen12** [comment]
The column can be named projected custom and we can incorporate anything we want in that column

**Comment by Denwen12** [comment]
@lightninglarry 
I'm going to try to add this in tonight, if I'm successful I'll get back to you.

**Comment by lightninglarry** [comment]
@Denwen12 did you get this to work?
