### ISSUE TITLE
P included in TeamStack

### ISSUE THREAD

**Issue by lightninglarry** [DimaKudosh/pydfs-lineup-optimizer#356]
how do you not include a P into a TeamStack?
if im wanting a 4-3-1 build, that is all batters.
optimizer.add_stack(TeamStack(4, spacing=2, for_teams=['PHI','TOR','TB','ATL','STL']))  # stack 4 players
optimizer.add_stack(TeamStack(3, spacing=1, for_teams=['LAD', 'HOU', 'COL', 'LAA', 'ATL', 'CIN', 'SD']))  # stack 3 players

it gives me 4(1 could be the P, or not)
but im not getting the 3 stack .
Thoughts?

**Comment by kryptickevin** [comment]
Change your code to the following if you want to only include batters in your stack:

`optimizer.add_stack(TeamStack(4, spacing=2, for_teams=['PHI','TOR','TB','ATL','STL'], 
                                                    for_positions=['1B', '2B', '3B', 'SS', 'C', 'OF',])) # stack 4 players`

**Comment by lightninglarry** [comment]
Thanks, that worked.
