### ISSUE TITLE
Feature request: point multipliers in scoring?

### ISSUE THREAD

**Issue by harvitronix** [DimaKudosh/pydfs-lineup-optimizer#36]
FanDuel has quite a few variations of contest scoring, especially for single games, where certain lineup slots have multipliers on the scoring, like 2.0x, 1.5x, 1.2x, etc.

Is it possible to add this more dynamic lineup scoring to the optimizer to handle these situations?

**Comment by DimaKudosh** [comment]
Hi, I can't use FanDuel because it gives me Restricted Location error. Can you send csv with this type of contest to my mail, you can view it in my profile

**Comment by DimaKudosh** [comment]
Duplicated #56
