### ISSUE TITLE
MLB Stacks

### ISSUE THREAD

**Issue by Milkman9691** [DimaKudosh/pydfs-lineup-optimizer#362]
@DimaKudosh how would one go about creating stacks depending upon slate size? Depending on game slates I am trying to create anywhere from a 2/2/2 with Pitcher stack to a 4/4 stack without Pitcher. Short slates stacks are simple just TeamStack=4-5 players (<5 games). When it comes to the >7 game slates it gets a bit more complicated in how many players and what stack split to utilize. Any help on this would be greatly appreciated

**Comment by norraist** [comment]
You can do something like this if you're running Python 3.10:

```
match slatesize:
        case 3:
#stack defined here
            
        case (10|13|14|15):
# stack defined here
            
        case _:
#default stack defined here
