### ISSUE TITLE
College Football

### ISSUE THREAD

**Issue by Milkman9691** [DimaKudosh/pydfs-lineup-optimizer#376]
Can someone please provide the "optimizer = get_optimizer(Site.DRAFTKINGS, Sport. XXXXXX)" for College Football I have tried CFB, NCAAF, NCAA, COLLEGE_FOOTBALL etc and cant find it on my own so maybe someone can give it to me Thx beforehand

**Comment by mbencho** [comment]
COLLEGE_FOOTBALL = 'COLLEGE_FOOTBALL'

![image](https://user-images.githubusercontent.com/8965153/187046554-1227eab7-d1e5-49fa-a325-606b9faaea78.png)
 
it looks like when it was updated last year the second one was left as 'CANADIAN_FOOTBALL'. If you are running the most recent version you will need to update that
