### ISSUE TITLE
Issues Importing GameStack 

### ISSUE THREAD

**Issue by HumanStatSheet** [DimaKudosh/pydfs-lineup-optimizer#377]
I have an issue I'm not seeing anywhere else. Keep in mind I have almost no coding experience; almost certainly an ID10T error. It's right at the beginning of my code. I've pip installed pydfs-lineup-optimizer and I can import most of the modules but when I try to import GameStack I get the following error (i've included a copy of the original code as well). TeamStack, PositionsStack, etc. all work fine. Help?

#Importing Modules

from pydfs_lineup_optimizer import get_optimizer, Site, Sport
from pydfs_lineup_optimizer import GameStack, TeamStack, PositionsStack
import pandas as pd
import numpy as np

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_5188/2903601192.py in <module>
      2 
      3 from pydfs_lineup_optimizer import get_optimizer, Site, Sport
----> 4 from pydfs_lineup_optimizer import GameStack, TeamStack, PositionsStack
      5 import pandas as pd
      6 import numpy as np

ImportError: cannot import name 'GameStack' from 'pydfs_lineup_optimizer' (C:\Users\joepo\anaconda3\lib\site-packages\pydfs_lineup_optimizer\__init__.py)

**Comment by Milkman9691** [comment]
This is what I have and get no errors

from pydfs_lineup_optimizer.stacks import GameStack, TeamStack, PositionsStack, NestedPlayersGroup, OptimizerStack, Stack

**Comment by Denwen12** [comment]
Cause he has the first peice wrong its
pydfs_lineup_optimizer.stacks
