### ISSUE TITLE
Max Salary

### ISSUE THREAD

**Issue by chrisbach1** [DimaKudosh/pydfs-lineup-optimizer#379]
For DKINGS single showdowns,  does anyone know how to change a max salary setting?  If I change below:

class DraftKingsCaptainModeSettings(BaseSettings):
    site = Site.DRAFTKINGS_CAPTAIN_MODE
    budget = 50000
    max_from_one_team = 5
    csv_importer = DraftKingsCaptainModeCSVImporter
    positions = [
        LineupPosition('CPT', ('CPT')),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)), 
    ]

to 

class DraftKingsCaptainModeSettings(BaseSettings):
    site = Site.DRAFTKINGS_CAPTAIN_MODE
    budget = 49000
    max_from_one_team = 5
    csv_importer = DraftKingsCaptainModeCSVImporter
    positions = [
        LineupPosition('CPT', ('CPT')),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)),
        LineupPosition('UTIL', ('UTIL',)), 
    ]

this does not work.  Is it pulling salary from somewhere else?

**Comment by mbencho** [comment]
You can change it in your code when you run the optimizer rather than changing it in the settings.

optimizer.settings.budget = 49500

**Comment by chrisbach1** [comment]
Perfect.  Exactly what I needed.  Thank you @mbencho much appreciated
