### ISSUE TITLE
Unable to import players from an array

### ISSUE THREAD

**Issue by mjester93** [DimaKudosh/pydfs-lineup-optimizer#38]
Hello,

I am trying to import players that are from a Google Sheet. I believe I have it formatted correctly. It is in an array. See below for the first two records:

['site_id', 'first_name', 'last_name', 'pos', 'team', 'salary', 'fppg', 'injury', 'max_exposure', 'min_exposure', 'ownership']
['58312', "D'Angelo", "Russell", 'SG', 'BKN', '9000', '10.39', '', '23%', '3%', '14%']

However, I get the following error when i run optimizer.load_players(player_array_final):
AttributeError: 'list' object has no attribute 'team'

**Comment by DimaKudosh** [comment]
Hello, 
`load_players` method takes list of Player objects, so you should convert you player arrays to `Player` objects before.

**Comment by mjester93** [comment]
Oh ok, that makes sense. Thanks! I got it to load, however there seems to be something wrong with the position. For example, when I try to pass D'Angelo Russell (like in the example originally mentioned) his positions goes from SG to S/G, causing an error that won't let me optimize.

Do you know of a way around this? Not sure why it's adding the random "/"

**Comment by DimaKudosh** [comment]
It because positions should be list of positions, it was made in this way because some sites support multipositional players, in your case it should be `['SG']`
