### ISSUE TITLE
Locking players to certain positions

### ISSUE THREAD

**Issue by Scottw1105** [DimaKudosh/pydfs-lineup-optimizer#384]
Just curious if there's a way to lock a specific player to a specific position?
 
Ex: LeBron James @ PF only.

**Comment by Milkman9691** [comment]
Why not just lock the player in with **optimizer.player_pool.get_player_by_name** or with a **PlayersGroup(optimizer.player_pool.get_players** I believe you can use them together as well but why complicate it

**Comment by BenikaH** [comment]
You could also set LeBron's position in  your CSV/JSON to PF instead of SF/PF/F depending on the site. So he would only be considered for the PF position.

**Comment by Scottw1105** [comment]
> Why not just lock the player in with **optimizer.player_pool.get_player_by_name** or with a **PlayersGroup(optimizer.player_pool.get_players** I believe you can use them together as well but why complicate it

So the reason I need a player locked to a specific position is for late swap. So yes, you can late swap to an "optimal" lineup but I do a lot to my potential lineups after that. So I'd like to have 150 lineups of LeBron @ PF with other pieces around that to determine which lineup I'm going to play.

**Comment by Scottw1105** [comment]
> You could also set LeBron's position in your CSV/JSON to PF instead of SF/PF/F depending on the site. So he would only be considered for the PF position.

That's a fantastic idea, I'm sure that'll do exactly what I need it to do, thanks so much!

**Comment by Scottw1105** [comment]
Haha I'm silly, it's built right into the .lock_player class.

optimizer.player_pool.lock_player('Zach Collins', 'C') works like a charm.
