### ISSUE TITLE
Generate multiple lineups with the same point total?

### ISSUE THREAD

**Issue by greencoder** [DimaKudosh/pydfs-lineup-optimizer#39]
I was trying to generate the top optimal lineups for yesterday's DK PGA tournament and noticed that when I generate multiple lineups, each generated lineup has a discrete point total despite having multiple ways to arrive at that total. 

Specifically, there were several combinations of players under salary cap that arrive at 586.0 points, (which was the winning GPP total) but only one lineup is generated with 586.0 points. 

Is this something that is intentionally being done by the optimizer?

--- 

This is the only 586.0 point lineup that was generated by the library when I don't lock any players:
![image](https://user-images.githubusercontent.com/239861/52969426-97a2ee00-336d-11e9-9b01-51a70f416e3a.png)

But if I lock the players to just the lineup that won the GPP yesterday, I get a different lineup at 586.0 points:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/239861/52969477-c28d4200-336d-11e9-9657-adc530ee226f.png">

I'm guessing that it's picking the "best" lineup for each 0.5 point interval, since the one it chose had a lower salary total than the one that won the GPP.

Ideally, I'd want to see all the permutations for a point total before it goes on to the next lower one. Is there a way to control for this?

**Comment by DimaKudosh** [comment]
What version of library are you using?

**Comment by greencoder** [comment]
I'm investigating it now, I think it might be outdated. If it is, I'll close this issue with my apologies.

**Comment by greencoder** [comment]
I was using an old version of the library. Updated to latest and this behavior is no longer being exhibited. I'm sorry for not checking this first.
