### ISSUE TITLE
Maximum Valid Lineups

### ISSUE THREAD

**Issue by GoSpinBoy** [DimaKudosh/pydfs-lineup-optimizer#390]
I have multiple lineup constraints. When I try to create, say 150 lineups, pydfs-lineup-optimizer will create well over a hundred then return an error code (see screen grabs below). I can see the lineups with the print function up to the error, but cannot export any of the good lineups prior to failure. 

My question is this: Is there a way to stipulate the maximum number of lineups until failure and then allow for the export of those good lineups? Or, conversely, a way to simply print all lineups that meet criteria?

In advance, thanks for helping out a noob.

<img width="845" alt="001" src="https://user-images.githubusercontent.com/71551668/201507112-1c8cde1b-c764-45b3-996f-0810b8352983.PNG">

<img width="841" alt="002" src="https://user-images.githubusercontent.com/71551668/201507114-afc6bdb9-e8cf-4b3e-bb3c-16728335c3b8.PNG">

**Comment by Denwen12** [comment]
What constraints are you running cause I can still get 150, also can run a try pass and still do export

**Comment by mbencho** [comment]
In the lineup_export.py I added the following except/pass to deal with when I ended up in the situation where my constraints didn't allow as many lineups as I was expecting

    def export(self, filename, render_func=None):
        with open(filename, 'a', newline='') as csvfile:
            lineup_writer = csv.writer(csvfile, delimiter=',')
            try: #added sep1 2022
                for index, lineup in enumerate(self.lineups):
                    if index == 0:
                        header = [self.COLUMNS_MAPPING.get(player.lineup_position, player.lineup_position)
                                  for player in lineup.lineup]
                        header.extend(self.EXTRA_COLUMNS)
                        lineup_writer.writerow(header)
                    row = [(render_func or self.render_player)(player) for player in lineup.lineup]
                    row.extend(self._get_extra_columns(lineup))
                    lineup_writer.writerow(row)
            except: #added 
                pass #added

**Comment by Denwen12** [comment]
Same thing  I did, just in my normal code config

**Comment by GoSpinBoy** [comment]
Thank you! I'll give it a try.

Update: Worked like a charm. Thanks, again!
