### ISSUE TITLE
lock_player - Request this be an array

### ISSUE THREAD

**Issue by mcarroll316** [DimaKudosh/pydfs-lineup-optimizer#393]
Requesting that locking of players be moved to an array as opposed to individual calls. I'm feeding a player pool in from my site and not sure I find a creative solution to accept more than one locked player when each one is its own method call.

From this...
optimizer.player_pool.lock_player('Juan Soto')
optimizer.player_pool.lock_player('Aaron Nola')

To this...
optimizer.player_pool.lock_player['Juan Soto', 'Aaron Nola']

**Comment by mcarroll316** [comment]
Closing this as I answered my own question. Put it in a loop. Duh.

**Comment by Denwen12** [comment]
Can you share the code for the loop been trying this also

**Comment by mcarroll316** [comment]
@Denwen12 - Here ya go. I spent hours over-thinking this. Lol.

lockedPlayers = ["Hunter Greene","Javier Baez","Jeimer Candelario"]

for lockedPlayer in lockedPlayers:
    optimizer.player_pool.lock_player(lockedPlayer)

**Comment by Denwen12** [comment]
Lol
