### ISSUE TITLE
MLB Fanduel occassional "unable to build lineup" error

### ISSUE THREAD

**Issue by drewwwwstyles** [DimaKudosh/pydfs-lineup-optimizer#408]
Having this issue on MLB FD where the program throws an exception while building lineups. Anybody know a fix or hack that I could use to bypass this issue? For some reason the exception is thrown at the line where I try to iterate through the lineups (to print the player ids) and not on optimizer.optimize().

Error: 

for l in lineups:
  File "C:\Users\Drew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 425, in optimize
    lineup = self._build_lineup(lineup_players, context)
  File "C:\Users\Drew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 534, in _build_lineup
    players_with_positions = link_players_with_positions(players, positions)
  File "C:\Users\Drew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pydfs_lineup_optimizer\utils.py", line 110, in link_players_with_positions
    raise LineupOptimizerException('Unable to build lineup')
pydfs_lineup_optimizer.exceptions.LineupOptimizerException: Unable to build lineup

**Comment by mbencho** [comment]
Assuming you have some restrictions on your lineup generation? (i.e. stacking etc)? Are you getting some lineups and then hitting this error? or nothing at all? You may need to remove those restrictions one by one to see what is causing it to be unable to build a lineup.

**Comment by Denwen12** [comment]
Post your config and we may be able to identify the issue

**Comment by drewwwwstyles** [comment]
Thanks for the responses, it currently does happen intermittently, I would say roughly 25% of the time. This happens without any restrictions. I have the same process for other sports and haven't run into this issue (with many more restrictions), though I've been using Draftkings for other sports. Not sure if it has something to do with certain players on Fanduel having three eligible positions? (as the exception:  line 110, in link_players_with_positions leads me to believe)

I'm not sure what config you would like me to post but happy to share whatever. The only reason this is an issue for me is that the exception is causing the file I'm writing (large batch of lineups) to return with errors and at times lock up the whole system.

**Comment by Denwen12** [comment]
You can edit the pydfs to add in a pass continue

**Comment by drewwwwstyles** [comment]
Since nobody else seems to be having the same issue, I have to assume there is something wrong on my end so I'll go ahead and close this. Thanks for the responses and thanks to the author for the library.

**Comment by Denwen12** [comment]
Share the code your trying to run then i could help you out.

**Comment by madkap7** [comment]
@drewwwwstyles were you able to get this resolved? having same problem.
