### ISSUE TITLE
optimizer.get_player_by_name ERROR

### ISSUE THREAD

**Issue by LoganNeptune** [DimaKudosh/pydfs-lineup-optimizer#418]
When trying to run a basic function I am receiving an error. optimizer.get_player_by_name returns an error "more than one player is found" this also happens when I try by other methods such as player_id etc 

I have used Excel as well as used "ctrl f" in the csv and there is no other instance of any one single player.

 ![image](https://github.com/DimaKudosh/pydfs-lineup-optimizer/assets/102203064/33537f03-778b-4538-96f8-ff64b34e618e)

![image](https://github.com/DimaKudosh/pydfs-lineup-optimizer/assets/102203064/0e91c7d0-35e6-49ca-bbfa-eb7f3c6e83ca)

**Comment by Milkman9691** [comment]
optimizer.player_pool.get_player_by_name("Travis Kelce")

You do not need the Kelce =

**Comment by Milkman9691** [comment]
Also if you are doing this for ShowDown slates you will need to do it by 

optimizer.player_pool.get_player_by_id("id number from csv whether be Flex or CPT")

Thats most likely why you are seeing the "more than one player by name"

**Comment by Denwen12** [comment]
You also get error, you can add playername and MVP IF YOU WANT THE MVP
PLAYER

**Comment by Denwen12** [comment]
Travis kelse MVP

**Comment by LoganNeptune** [comment]
Do you have to include a position with it? I am currently trying to remove a player but he still shows up in over half the lineups.
