### ISSUE TITLE
FantasyDraft Golf

### ISSUE THREAD

**Issue by hdtact** [DimaKudosh/pydfs-lineup-optimizer#42]
FantasyDraft golf should have 7 roster spots instead of 6.

**Comment by utahman** [comment]
For DraftKings its 6

**Comment by hdtact** [comment]
Yeah, I know for DK it is 6.  But for Fantasy Draft it is 7 players in a
golf lineup.  Currently the optimizer puts 6 players in a Fantasy Draft
lineup, which is not correct.
