### ISSUE TITLE
Example Code Not Working ( No CSV File Present ) 

### ISSUE THREAD

**Issue by saqib772** [DimaKudosh/pydfs-lineup-optimizer#427]
`from pydfs_lineup_optimizer import Site, Sport, get_optimizer

optimizer = get_optimizer(Site.YAHOO, Sport.BASKETBALL)
optimizer.load_players_from_csv("yahoo-NBA.csv")

lineup_generator = optimizer.optimize(10)

for lineup in lineup_generator:
    print(lineup)
    
optimizer.print_statistic()

`

I want to run the following code but there's no "yahoo-NBA.CSV" Files or how to generate the CSV Files for Multiple games. Pls help

**Comment by lightninglarry** [comment]
your player file yahoo needs to be named that, or you need to adjust the load players line to reflect what your files name is that you grab from yahoo.

**Comment by saqib772** [comment]
But from where to get that file, i didn't get it? How to get the csv file from yahoo

**Comment by lightninglarry** [comment]
> But from where to get that file, i didn't get it? How to get the csv file from yahoo

Within whatever contest your looking for you will see a link labeled "Export players list"

**Comment by saqib772** [comment]
oh, ok. understand!
