### ISSUE TITLE
Game Stacks

### ISSUE THREAD

**Issue by brente33** [DimaKudosh/pydfs-lineup-optimizer#44]
Hi Dima, 

This is great, I really appreciate you creating this for us.

I see you can stack one team using optimizer.set_players_from_one_team({'PHO': 3}) , is there a way to Game Stack by setting the number of players from two different  teams?

For instance, tonight GS plays PHI, I'd like to know how to force the optimizer to give me several lineups containing the maximum 4 players from each team.

Thanks!

**Comment by DimaKudosh** [comment]
Hi, if you want to generate lineups with 4 players from GS and 4 players from PHI you can do:
```optimizer.set_players_from_one_team({'GS': 4, 'PHI': 4})```

**Comment by utahman** [comment]
Hi Dima,

How to set that number for every team currently loaded?

**Comment by brente33** [comment]
I ran them one at at time. It would be helpful to be able to do

optimizer.set_players_from_one_team({'GS': 4, 'PHI': 4}) N=10
optimizer.set_players_from_one_team({'BOS': 4, 'LAL': 4}) N=10
optimizer.set_players_from_one_team({'DET': 4, 'IND': 4}) N=10

I don't know anything about how to do this so not sure that is feasible. Either way, you've made a great tool Dima!

**Comment by DimaKudosh** [comment]
> Hi Dima,
> 
> How to set that number for every team currently loaded?

I'm not sure what you want do with this, but if you set this constraint for every team you will get error because lineups has restricted number of players


> I ran them one at at time. It would be helpful to be able to do
> 
> optimizer.set_players_from_one_team({'GS': 4, 'PHI': 4}) N=10
> optimizer.set_players_from_one_team({'BOS': 4, 'LAL': 4}) N=10
> optimizer.set_players_from_one_team({'DET': 4, 'IND': 4}) N=10
> 
> I don't know anything about how to do this so not sure that is feasible. Either way, you've made a great tool Dima!

Thanks. You could run 3 separate optimizers with different constraints, and for this situation optimizers will produce different lineups. But I'm not sure what you want to do with this, maybe I misunderstood.

**Comment by utahman** [comment]
I mentioned in another issue that in Captain mode optimizer can choose all 6 players from the same team thus making illegal lineup. So if I set max 5 from any team the problem will disappear.
On other hand, maybe I misunderstand set_players_from_one_team. I assume that it means max players from a team. No more than 4, for example. So 4+2 is correct and 3+3 is correct but not 5+1.
Otherwise maybe another method needed, something like:
max_players_from_same_team(5)

**Comment by DimaKudosh** [comment]
Yeah, I saw your issue, currently optimizer has incorrect settings for captain mode where max from one team restriction isn't set. I will fix it. 
set_players_from_one_team set exact number of players, so if you pass 4 players, it will generate lineups with exact 4 players for passed team.

**Comment by brente33** [comment]
One more item I thought about for this...

Can you make a general setting to force the optimizer to stack? So, instead of telling the optimizer to select 'BOS': 4 , could you create something that goes 'Stack': 4, 'Stack':3  that would tell the optimizer to select 4 players from the same team and 3 hitters from another. 

Ideally the Pitcher would not be included in the stack since you are trying to group hitters together to increase the correlation of your lineup. So if you try select 'Stack': 4, the pitcher spot would not be an option and the optimizer would insert 4 hitters from the same team in your lineup.

**Comment by DimaKudosh** [comment]
Added `set_team_stacking` method in version 2.4.0

**Comment by brente33** [comment]
Dima - one more question on this. Is there an easy way to exclude the P has part of a stack? Optimally we want to correlate the hitters and we need 3 teams represented. I think the best way is to have a P from one team and then two four man stacks of hitters. Right now I often get a 3 hitter stack with the Pitcher included.

**Comment by brente33** [comment]
Could you just modify this to make it same team?

optimizer.restrict_positions_for_opposing_team(['P'], ['1B', '2B', '3B', 'OF', 'SS', 'C'])

so -  optimizer.restrict_positions_for_**same**_team(['P'], ['1B', '2B', '3B', 'OF', 'SS', 'C'])

**Comment by DimaKudosh** [comment]
@brente33 There is no such functionality right now, I'll add it in feature release.
