### ISSUE TITLE
Feature Request: Question: MySQL vs. CSV

### ISSUE THREAD

**Issue by dexter1964** [DimaKudosh/pydfs-lineup-optimizer#49]
Thank you so much for  writing and posting this, I love it.
I have one question.  Is it possible to use my "mySQL" database instead of reading from a CSV file?

I scrape FanDuel and DraftKings Websites on a daily basis and store that data into a mySQL table, then I can work on it.  I'm just wondering if there is a way to Import directly from a query into your Player List / Dictionary? instead of from a CSV File.
I know that I could write my query to output to a CSV file, then use your scripts to read in that CSV file. but, if I could read in directly from a mySQL DB, that would be great! 

Is this possible now? or is this a Function Request?  or something I can do on my own, with a little direction from you.

Thank you again, SO MUCH.

**Comment by dexter1964** [comment]
I found this in your documentation. can you please give me an example on How to use it? please.
==================================================
Or you can load players using load_players method and pass list with players.

from pydfs_lineup_optimizer import Player
optimizer.load_players(players)  # players is list of Player objects
===========

**Comment by DimaKudosh** [comment]
Hi, currently library supports only csv, so you should write you custom players importer for this. You can just write function that queries your database and then map returned rows to optimizer [Player](https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/player.py#L11) objects, and then pass list of Player objects to `load_players` method that you mentioned before. [Here](https://github.com/DimaKudosh/pydfs-lineup-optimizer/blob/master/pydfs_lineup_optimizer/sites/fanduel/importer.py#L14) you can view how it made for fanduel and csv.

**Comment by dexter1964** [comment]
Thanks for your reply.  Here's my problem.: I can get my data out of my mySQL database and into a list using my "mySql Query" below:
My problem is getting the player data into the "Player Objects", can you help me with that part?  I think it would be something like the "code segment" below:  (but I'm getting this "error message")

I'm sorry to be a bother, but I can't figure out what I'm doing wrong. Please help, and thank you so much!!

***  Error Message  ********************************************************************************
File "C:\Users\Larry Brown\AppData\Local\Programs\Python\Python37\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 385, in optimize
    solved_variables = solver.solve()
  File "C:\Users\Larry Brown\AppData\Local\Programs\Python\Python37\lib\site-packages\pydfs_lineup_optimizer\solvers\pulp_solver.py", line 47, in solve
    raise SolverException('Unable to solve')
**pydfs_lineup_optimizer.solvers.exceptions.SolverException: Unable to solve**
(and)
   for lineup in lineup_generator:
  File "C:\Users\Larry Brown\AppData\Local\Programs\Python\Python37\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 397, in optimize
    raise LineupOptimizerException('Can\'t generate lineups')
**pydfs_lineup_optimizer.exceptions.LineupOptimizerException: Can't generate lineups**
***  Code Segment  ********************************************************************************
row_number = 0
players = []
for row in playerInfo:
    playerName = row[0].split()
    player = Player(
        row_number,             # Seqential PlayerID
        playerName[0],          # First Name
        playerName[1],          # Last Name
        row[2].split('/'),      # Player Position
        row[1],                 # Team
        float(row[3]),          # Fanduel Salary Only (for now)
        float(row[4]),          # Fantasy Points
        False,                  # Holder for Injury Indicator
        None                    # Holder for Max Exposure
    )
    players.append(player)
    row_number += 1

optimizer.load_players(players)
**** mySql Query *******************************************************************************
    qPlayerInfo = \
    "Select \
        MLBStartingLineups.PlayerName, \
        MLBStartingLineups.TeamShort, \
        MLBStartingLineups.PlayerFDPosition, \
        MLBStartingLineups.FanDuelSalary, \
        MLBStartingLineups.FanDuelFPoints, \
        MLBStartingLineups.PlayerDKPosition, \
        MLBStartingLineups.DraftKingsSalary, \
        MLBStartingLineups.DraftKingsFPoints \
    from MLBStartingLineups \
    where (FanDuelSalary != 0) and (FanDuelFPoints != 0) \
    order by FanDuelSalary Desc;"

    cur.execute(qPlayerInfo)
    playerInfo = cur.fetchall()
***********************************************************************************

**Comment by DimaKudosh** [comment]
You got error because you set incorrect data in `Player` constructor. `fetchall` returns list of your players rows so you should iterate on this list and create Player on each iteration, so it should like this:
```
players_rows = cur.fetchall()
players = []
for i, player_info in enumerate(player_rows):
    name = player_info['PlayerName'].split(' ')
    players.append(Player(
        i,
        name[0],
        name[1],
        player_info['PlayerFDPosition'].split('/'),
        player_info['TeamShort'],
        player_info['FanDuelSalary'],
        player_info['FanDuelFPoints']
    ))
optimizer.load_players(players)
```
Not sure that it will work because it's unclear how you use it.

**Comment by dexter1964** [comment]
Thanks for your help.
    (I know it's something I'm doing wrong)
**On this line:** "    name = player_info['PlayerName'].split(' ')"
**I'm getting this error, "**
File ".\example.py", line 63, in <module>
    player_info['PlayerFDPosition'].split('/'),
TypeError: tuple indices must be integers or slices, not str

**So I'm trying this:** "    name = player_info[0].split(' ')"
and I'm able to get around that error. but now I'm back to the "Unable to solve" error.
( -- I'm still trying different things on my end. )
**Any thoughts, Please? and thanks again for all your help.**
********************************************************************************************
roster = getAllMLBPlayerInfo()
for i, player_info in enumerate(roster):
    name = player_info[0].split(' ')
    players.append(Player(
        i,
        name[0],
        name[1],
        player_info[2].split('/'),
        player_info[1],
        player_info[3],
        player_info[4]
    ))
optimizer.load_players(players)

***************************************************************************
def getAllMLBPlayerInfo():
    conn = mysql.connector.connect(user='larryb64', password='Logical1', host='192.168.1.248', database='MLB_Statroute')
    cur = conn.cursor()

    qPlayerInfo = \
    "Select \
        MLBStartingLineups.PlayerName, \
        MLBStartingLineups.TeamShort, \
        MLBStartingLineups.PlayerFDPosition, \
        MLBStartingLineups.FanDuelSalary, \
        MLBStartingLineups.FanDuelFPoints, \
        MLBStartingLineups.PlayerDKPosition, \
        MLBStartingLineups.DraftKingsSalary, \
        MLBStartingLineups.DraftKingsFPoints \
    from MLBStartingLineups \
    where (FanDuelSalary != 0) and (FanDuelFPoints != 0) \
    order by FanDuelSalary Desc;"

    cur.execute(qPlayerInfo)
    playerInfo = cur.fetchall()

    cur.close()
    return(playerInfo)

**Comment by dexter1964** [comment]
also. Here's a snippet of my data: (I'm sorry, if I'm just doing something very stupid, or missing something)
As you can see I have 190 playerRecords.
**********************************************************************
roster = mF.getAllMLBPlayerInfo()
for i, player_info in enumerate(roster):
    name = player_info[0].split(' ')
    print('player_info[' + str(i) +'] : ')
    print('PlayerName : ' + str(player_info[0]))
    print('Name[0]    : ' + str(name[0]))
    print('Name[1]    : ' + str(name[1]))
    print('TeamShort  : ' + str(player_info[1]))
    print('Position   : ' + str(player_info[2]))
    print('Salary     : ' + str(player_info[3]))
    print('FanPoints  : ' + str(player_info[4]))

***********************************************************
player_info[187] :
PlayerName : Patrick Kivlehan
Name[0]    : Patrick
Name[1]    : Kivlehan
TeamShort  : ARI
Position   : OF
Salary     : 2000.0
FanPoints  : 27.4
player_info[188] :
PlayerName : Chris Owings
Name[0]    : Chris
Name[1]    : Owings
TeamShort  : ARI
Position   : OF
Salary     : 2000.0
FanPoints  : 34.9
player_info[189] :
PlayerName : Jeff Mathis
Name[0]    : Jeff
Name[1]    : Mathis
TeamShort  : ARI
Position   : C-1B
Salary     : 2000.0
FanPoints  : 22.2
player_info[190] :
PlayerName : Gerardo Parra
Name[0]    : Gerardo
Name[1]    : Parra
TeamShort  : COL
Position   : OF
Salary     : 2000.0
FanPoints  : 3.0

**Comment by DimaKudosh** [comment]
As I can see from your data snippet, you separate positions for multi-positional players with char '-', so in Player creation change position to: `player_info[2].split('-')`.

**Comment by dexter1964** [comment]
Thank you sooooo much!!! That did it, thanks!!!
      Ohhh... because that's the way I'm scraping it from the RotoGrinders Website!!!

You are Awesome!! and again thank you soo much for all your patience and help!

Please let me know if there's anything I can do for you!
