### ISSUE TITLE
add_player_to_lineup requires Player object rather than full_name

### ISSUE THREAD

**Issue by sansbacon** [DimaKudosh/pydfs-lineup-optimizer#5]
I think it would be helpful to have a convenience method 'get_player' or 'find_player':

    from fuzzywuzzy import fuzz, process

    def get_player(self, full_name):
        player = [x for x in self.players if x.full_name == full_name]
        if not player:
            fuzzy, confidence = process.extractOne(full_name, [x.full_name for x in self.players])
            if confidence >= threshold:
                player = [x for x in self.players if x.full_name == fuzzy]
        if player:
            return player[0]
        else:
            return None

**Comment by DimaKudosh** [comment]
Added 2 new methods: find_players(name) that returns sorted list with players with similar names, and get_player_by_name(name) that returns player with closest match.
