### ISSUE TITLE
Seems like a bug in late-swap Classic MLB

### ISSUE THREAD

**Issue by utahman** [DimaKudosh/pydfs-lineup-optimizer#52]
MLB roaster positions: P | P | C | 1B | 2B | 3B | SS | OF | OF | OF
NBA roaster positions: PG | SG | SF | PF | C | G | F | UTIL

NBA positions are all unique, while MLB (which is baseball) have several identical names, like two Ps and three OFs. So in this code:

1        if unswappable_players:
2           locked_positions = [player.lineup_position for player in unswappable_players]
3           players = [player for player in players if player not in unswappable_players]
4           positions = [position for position in positions if position.name not in locked_positions]
5           lineup.extend(unswappable_players)

In line 4 'positions' will be missing all three 'OF' positions even if only a single player in 'OF' position is unswappable.
Which means that late-swap optimization will not be correct.

**Comment by utahman** [comment]
If the above logic is correct, one way to fix it would be temporary renaming of identical names to unique names. Instead of "P | P" make "P1 | P2", and "OF | OF | OF" rename to "OF1 | OF2 | OF3"
Then was the problem will be avoided.
However, possible positions for each player must also be renamed and extended. For example:
"Adam Smith P" should become "Adam Smith P1/P2" 
"Bob Dole 1B/OF" should become "Bob Dole 1B/OF1/OF2/OF3"

**Comment by brente33** [comment]
Is there a way to prevent the optimizer from selecting hitters vs the pitcher in each lineup? Today I have Marquez for Col and I noticed two Tampa Bay Rays are in my lineup.

**Comment by utahman** [comment]
Another way to avoid it would be to assign indexes for each position, instead using position names. So if "OF | OF | OF" have indexes 7, 8, 9 and unswappable player at position 8 then positions 7 and 9 still be available, despite having the same name.

**Comment by DimaKudosh** [comment]
> Is there a way to prevent the optimizer from selecting hitters vs the pitcher in each lineup? Today I have Marquez for Col and I noticed two Tampa Bay Rays are in my lineup.

Hi, do you mean prevent selecting hitters and pitchers from same team? Right now it's not implemented. Can you create separate issue for this?
