### ISSUE TITLE
Pitcher vs Opposing Hitter

### ISSUE THREAD

**Issue by brente33** [DimaKudosh/pydfs-lineup-optimizer#53]
Hi Dima,

Can you make it so the optimizer doesn't select hitters from the team your pitcher is opposing?

For instance, if Boston were playing Houston and I was using Chris Sale in a Pitcher spot, I wouldn't want any batters in my lineup from Houston. Likewise, if I were using Gerrit Cole for Houston I wouldn't want any Boston hitters in my lineup.

The reason being your upside is limited if you have hitters that are facing the pitcher you roster. If Sale has a great game, then the Houston batters likely had a poor game. You wouldn't want them in the same lineup.

**Comment by DimaKudosh** [comment]
Added `restrict_positions_for_opposing_team` method in version 2.4.0
