### ISSUE TITLE
DraftKings and Hockey, Doesn't like my data.

### ISSUE THREAD

**Issue by dexter1964** [DimaKudosh/pydfs-lineup-optimizer#54]
Hello again;
       and again, this issue is caused by my own stupidity.

I'm pulling my data from mySql Data Tables that I've scraped from various websites.  I've gotten the FanDuel Hockey, working and it's great (Thank you so much) ,
but for some reason, I can't figure out what I'm missing on the DraftKings side.  (I have a feeling that my Position(s) are wrong for DraftKings, but I don't know how to fix it.) 
Can you please help me? -- Thanks.
-- ==================================================
Here's a sample of my input data:  (The first two are goalies, the second two are ['C','UTIL'] and ['W', 'UTIL']... 
player_info[0] : 
PlayerName : Marc-Andre Fleury
Name[0]    : Marc-Andre
Name[1]    : Fleury
TeamShort  : VGK
Position   : ['G']
Salary     : 8200.0
FanPoints  : 10.6
player_info[1] : 
PlayerName : Matt Murray
Name[0]    : Matt
Name[1]    : Murray
TeamShort  : PIT
Position   : ['G']
Salary     : 8000.0
FanPoints  : 2.6
PlayerName : S. Stamkos
Name[0]    : S.
Name[1]    : Stamkos
TeamShort  : TBL
Position   : ['C', 'UTIL']
Salary     : 7100.0
FanPoints  : 6.0
player_info[10] : 
PlayerName : V. Tarasenko
Name[0]    : V.
Name[1]    : Tarasenko
TeamShort  : STL
Position   : ['W', 'UTIL']
Salary     : 7000.0
FanPoints  : 6.0
-- ===================================================
Here's my code:
    players.append(Player(
        int(i),
        name[0],
        name[1],
        player_info[2].split('/'),    # for Fanduel use '-' for Draftkings use '/'
        player_info[1],
        float(player_info[3]),
        float(player_info[4])
    ))
optimizer.load_players(players)
for player in optimizer.players:
    if player.efficiency == 0:
        optimizer.remove_player(player)
lineup_generator = optimizer.optimize(3)

*_Here's the Error:_*
pydfs_lineup_optimizer.solvers.exceptions.SolverException: Unable to solve
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".\NHLDKTodaysTop3Lineups(TXT).py", line 147, in <module>
    for lineup in lineup_generator:
  File "C:\Users\Larry Brown\AppData\Local\Programs\Python\Python37\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 397, in optimize
    raise LineupOptimizerException('Can\'t generate lineups')
pydfs_lineup_optimizer.exceptions.LineupOptimizerException: Can't generate lineups
-- ====================================================

**Comment by DimaKudosh** [comment]
You have incorrect positions names, optimizer uses names from exported csv, so correct position names for NHL are: `LW, RW, C, D, G`
