### ISSUE TITLE
DK NBA Late Swap IndexError

### ISSUE THREAD

**Issue by ozzydfs** [DimaKudosh/pydfs-lineup-optimizer#58]
Hello, thank you so much for providing this amazing tool.

I am trying to edit my NBA entries post lock but I am getting an "IndexError". I have looked over everything but still cannot figure out what the issue is.

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-e3b721f30541> in <module>
      3 csv_filename = r"C:\Users\OzzyDFS\Downloads\DK NBA 05-12-2019 - DK Entries.csv"
      4 optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
----> 5 optimizer.load_players_from_csv(csv_filename)
      6 lineups = optimizer.load_lineups_from_csv(csv_filename)
      7 for lineup in optimizer.optimize_lineups(lineups):

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in load_players_from_csv(self, filename)
    185         if not csv_importer:
    186             csv_importer = SitesRegistry.get_csv_importer(self._settings.site)
--> 187         self._players = csv_importer(filename).import_players()
    188 
    189     def load_lineups_from_csv(self, filename):

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in import_players(self)
     68                     csv_data = csv.DictReader(islice(csv_file, start_line, None),
     69                                               skipinitialspace=True)
---> 70                     return [self._row_to_player(row) for row in csv_data]
     71                 elif line == '':
     72                     raise LineupOptimizerIncorrectCSV

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in <listcomp>(.0)
     68                     csv_data = csv.DictReader(islice(csv_file, start_line, None),
     69                                               skipinitialspace=True)
---> 70                     return [self._row_to_player(row) for row in csv_data]
     71                 elif line == '':
     72                     raise LineupOptimizerIncorrectCSV

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in _row_to_player(self, row)
     46             player = Player(
     47                 row['ID'],
---> 48                 name[0],
     49                 name[1] if len(name) > 1 else '',
     50                 row['Position'].split('/'),

IndexError: list index out of range

**Comment by ozzydfs** [comment]
I thought maybe the issue was me using google sheets so I tried using the excel version for the "Entries.CSV". Now a different issue came up. "Attribute Error"

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-81541a3c4bf9> in <module>
      3 csv_filename = r"C:\Users\OzzyDFS\Downloads\DKEntries.csv"
      4 optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASKETBALL)
----> 5 optimizer.load_players_from_csv(csv_filename)
      6 lineups = optimizer.load_lineups_from_csv(csv_filename)
      7 for lineup in optimizer.optimize_lineups(lineups):

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in load_players_from_csv(self, filename)
    185         if not csv_importer:
    186             csv_importer = SitesRegistry.get_csv_importer(self._settings.site)
--> 187         self._players = csv_importer(filename).import_players()
    188 
    189     def load_lineups_from_csv(self, filename):

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in import_players(self)
     68                     csv_data = csv.DictReader(islice(csv_file, start_line, None),
     69                                               skipinitialspace=True)
---> 70                     return [self._row_to_player(row) for row in csv_data]
     71                 elif line == '':
     72                     raise LineupOptimizerIncorrectCSV

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in <listcomp>(.0)
     68                     csv_data = csv.DictReader(islice(csv_file, start_line, None),
     69                                               skipinitialspace=True)
---> 70                     return [self._row_to_player(row) for row in csv_data]
     71                 elif line == '':
     72                     raise LineupOptimizerIncorrectCSV

c:\users\OzzyDFS\appdata\local\programs\python\python37\lib\site-packages\pydfs_lineup_optimizer\sites\draftkings\classic\importer.py in _row_to_player(self, row)
     43         try:
     44             max_exposure = row.get('Max Exposure', '').replace('%', '')
---> 45             name = row['Name'].split()
     46             player = Player(
     47                 row['ID'],

AttributeError: 'NoneType' object has no attribute 'split'

**Comment by DimaKudosh** [comment]
Hi, you should pass csv file with lineups generated by DK, it's look like error while parsing file, so it has incorrect format. Could you send your csv file to my email, I'll check why you got this error, because from traceback I can't do this.
