### ISSUE TITLE
Can Tennis be added for Draftkings??

### ISSUE THREAD

**Issue by faithhealer** [DimaKudosh/pydfs-lineup-optimizer#59]
Heya, 

Is it possible to add tennis?

**Comment by DimaKudosh** [comment]
Hi, I will add it in next version

**Comment by ericcolon** [comment]
That is awesome.  I have been playing a lot of tennis dfs lately.  One suggestion is to have the optimizer check for player vs opponent in the same lineup.

**Comment by wawegner** [comment]
@ericcolon this would be a great implementation for the MMA optimizer as well.  You don't often want both fighters.

**Comment by faithhealer** [comment]
@DimaKudosh  thank you!!!! Its an amazing tool, finally I can grind my 25 cent contests against all the sharks :) 

I actually had someone change my code so it gives me a proper output file that I can use for DK.

I added the script and the output file. Like that you can just paste it into the CSV of DK and uploadthem right away.

**Comment by faithhealer** [comment]
> Hi, I will add it in next version

Any idea when this might happen? Possible to have it ready before Wimbledon starts end of June?

**Comment by DimaKudosh** [comment]
@faithhealer I'm planning to publish it in end of june

**Comment by faithhealer** [comment]
> @faithhealer I'm planning to publish it in end of june

cool, thank you! Wimbledon starts 1st of July. Is there a way to donate to you?

**Comment by DimaKudosh** [comment]
It's not necessary to donate I'll add tennis anyway, but if you still want this you can send it on skrill

**Comment by faithhealer** [comment]
> It's not necessary to donate I'll add tennis anyway, but if you still want this you can send it on skrill

same email as here?

**Comment by DimaKudosh** [comment]
@faithhealer yes, dimakudosh@gmail.com

**Comment by DimaKudosh** [comment]
@ericcolon @wawegner Now you can use `restrict_positions_for_opposing_team` for tennis, MMA. For tennis: `optimizer.restrict_positions_for_opposing_team(['P'], ['P'])`, for MMA: `optimizer.restrict_positions_for_opposing_team(['F'], ['F'])`

**Comment by ericcolon** [comment]
Fanduel just added tennis!
