### ISSUE TITLE
Multi-positional eligibility

### ISSUE THREAD

**Issue by sansbacon** [DimaKudosh/pydfs-lineup-optimizer#6]
From reviewing the code, I can't tell if the optimizer handles multi-position eligibility

**Comment by rneu31** [comment]
I do not believe so. I looked at this in the past and ended up writing my
own from scratch.

**Comment by sansbacon** [comment]
What constraints did you add? No more than 1 of a player ID?

**Comment by sansbacon** [comment]
If you add a player multiple times to the pool for different positions, you could create a constraint like this.
    for pid in set([p.id for p in players]):
        prob += sum([x[player] for player in players if player.id == pid]) <= 1

**Comment by DimaKudosh** [comment]
I'll look into it on weekends.

**Comment by brendanahart** [comment]
Kudos to the optimizer that was created, it really is a great solution, efficien, is very customizable, and fits my exact needs. I just wanted to second that I am still encountering this issue where a player with multiple positions will be added to the lineup as a member of both those positions. 

A work around I found was adding the player twice to the pool, assigning them a unique id, then creating a constraint in the optimizer listed above (this was inserted into the optimizer function): 
```
for pid in set([p.id for p in players]):
                prob += lpSum([x[player] for player in players if player.id == pid]) <= 1
```

**Comment by DimaKudosh** [comment]
What version of library you use? It should be fixed in latest version.

**Comment by brendanahart** [comment]
I'm running version 1.1.2 of the library and python 2.7

**Comment by DimaKudosh** [comment]
Can you provide info about site and sport and players list sample?
