### ISSUE TITLE
Team Related Constraints in FantasyDraft

### ISSUE THREAD

**Issue by resumeman** [DimaKudosh/pydfs-lineup-optimizer#60]
I think the answer is I can't do this, but I wanted to check.

I tried to include the set_players_from_one_team option for my MLB lineups playing FantasyDraft, but kept getting an error "incorrect team name" even though I was using the only abbreviation that exists for a given team. I think the problem is that in the Fdraft csv format, the only team related info is Matchup, so like "ATL @ STL" and it doesn't look like the CSV does anything to differentiate the teams.

Is that right? If so is there anything i can do about it?

**Comment by DimaKudosh** [comment]
You are right, because fantasydraft doesn't provide player team info I just set info about game to it. So it will not work well with teams constraints. If you change team name to correct it should work as expected, so you should to retrieve this information somewhere else

**Comment by resumeman** [comment]
OK it does look like it just looks in the "Game" column, which as noted above in FantasyDraft has both teams. But I just switched that column to have the player's team, and it seems to work. Since I'm creating the csv from within a more involved spreadsheet, that change was trivially easy. Thanks for the guidance on that.
