### ISSUE TITLE
Using CPLEX

### ISSUE THREAD

**Issue by asardinha** [DimaKudosh/pydfs-lineup-optimizer#63]
Dima,

I have access to CPLEX and it is install using the API. How would I go about changing the solver to use CPLEX, opposed to CBC?

Any insight would be greatly appreciated.

**Comment by asardinha** [comment]
Dima,

I was able to get CPLEX working, however, when implementing the team stacking  feature, several lineups are incomplete, producing anywhere from 4 to the required 9 for MLB. If this is taken off, the program produces the required 9 players for the lineup.

Are there any specific changes that need to be made to the TeamStackRule?

Thanks again for all of your help.

**Comment by DimaKudosh** [comment]
Hi, how you replace optimizer? I have section how to do this in [documentation](https://pydfs-lineup-optimizer.readthedocs.io/en/latest/performance-and-optimization.html#optimizer-parameters-tuning). Did you do the same?

**Comment by asardinha** [comment]
Dima,

here is my code to run the file
---
import pulp
from pulp import *
from pulp.solvers import CPLEX_PY
from pydfs_lineup_optimizer import get_optimizer, Site, Sport
from pydfs_lineup_optimizer.solvers.pulp_solver import PuLPSolver
class CustomPuLPSolver(PuLPSolver):
    LP_SOLVER = pulp.CPLEX_PY(msg=0)
optimizer = get_optimizer(Site.FANDUEL, Sport.BASEBALL, solver=CustomPuLPSolver)

optimizer.load_players_from_csv("MLB.csv")
optimizer.set_team_stacking([4, 4])
for lineup in optimizer.optimize(n=150):
    print(lineup.players)  # list of players
**###**

I've also changed line 7 of pulp_solver.py to reflect this change.

I'm finding the using CBC and GLPK produces the correct constraints, with CPLEX not following any rules, often producing anywhere from 4 players to 9 players in a lineup.

Please let me know if there is anything else I can provide, or if there are any questions that I can clarify.

Thanks again.

**Comment by DimaKudosh** [comment]
Optimizer with CPLEX returns incorrect result because sometimes it returns computation result with float number, when CBC returns integer number. I fixed this, you can wait for next release or reinstall library from develop branch.

**Comment by BenikaH** [comment]
Hi @asardinha, in pulp_solver.py line 7, what exactly did you have to change to get CPLEX to work?

**Comment by DimaKudosh** [comment]
For running with cplex you should install cplex using pip: `pip install cplex`, then create new cplex solver:
```
from pulp.solvers import CPLEX_PY
from pydfs_lineup_optimizer.solvers.pulp_solver import PuLPSolver


class CPLEXSolver(PuLPSolver):
    LP_SOLVER = CPLEX_PY(msg=0)

```
and create optimizer like this: 
```
optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASEBALL, solver=CPLEXSolver)
```

**Comment by zwag20** [comment]
Is there an updated way to use CPLEX? I don't see a pulp.solvers

I tried something like this:

```
from pydfs_lineup_optimizer.solvers.pulp_solver import PuLPSolver
import cplex

class CPLEXSolver(PuLPSolver):
    LP_SOLVER = cplex

optimizer = get_optimizer(Site.DRAFTKINGS, Sport.BASEBALL, solver=CPLEXSolver)

```
I get an error that says module cplex has no attribute 'actualSolve'
