### ISSUE TITLE
Small issue in __init__.py

### ISSUE THREAD

**Issue by Haris987** [DimaKudosh/pydfs-lineup-optimizer#7]
Type in __init__.py: 
Site.FANDUEL: {
        Sport.BASKETBALL: FanDuelBasketballSettings,
        Sport.FOOTBALL: FanDuelFootballSettings,
        Sport.HOCKEY: FanDuelHockeySettings,
        Sport.**BASEBALL**: **FanDuelBasketballSettings**,
    },

It should be FanDuelBaseballSettings

Also, Sport.BASEBALL: DraftKingBaseballSettings, you are missing 's' in DraftKing(**s**)

**Comment by DimaKudosh** [comment]
Fixed!
