### ISSUE TITLE
Min Exposure

### ISSUE THREAD

**Issue by brente33** [DimaKudosh/pydfs-lineup-optimizer#70]
I see you closed this issue a long time ago, but I've never been able to get Min Exposure to work in my csv file. Max Exposure has always worked fine. Anyone else have a problem with Min Exposure?

**Comment by brente33** [comment]
I added the min_exposure lines to the lineup_importer.py and it seemed to work:

![Capture](https://user-images.githubusercontent.com/45069480/60301783-3a610f80-9900-11e9-99a3-d022baa7cc24.PNG)

**Comment by DimaKudosh** [comment]
Yes, currently min exposure can be added only from code, I will add additional field parsing to importer as in your code.

**Comment by brente33** [comment]
Is Projected Ownership the same issue? I've never been able to get that to work, it's as if when I load players from csv the 'Projected Ownership' column is not included.

**Comment by brente33** [comment]
I fetched your updates and now it seems neither max or min exposure are working.
