### ISSUE TITLE
Player stack rules

### ISSUE THREAD

**Issue by asardinha** [DimaKudosh/pydfs-lineup-optimizer#71]
I was looking through some of the closed issues and didn’t see something similar. But I’m wonder how/if we could set a feature to stack by a player array. 

For example. Stacking at least/maximum (number) player(s) from an array in every lineup

Or

If “Player X” is in lineup, stack with at least/maximum player(s) from the array in every lineup. 

Let me know your thoughts or if there is anything I can clarify. 

Thanks again.

**Comment by DimaKudosh** [comment]
Now library supporting only stacking for players from same team, I'm not sure about use-case when we need to stack players from array.

**Comment by asardinha** [comment]
Dima,

I hope this can clarify some of the possibilities.

I think this would be beneficial specifically in football, where there are many players on a team with the same position, and instead of stacking by team, we can stack by a group of players.

Using a roster from last year as an example, if Tom Brady is in your lineup, he is always paired with a certain amount of players (2, 3, 4, etc.) from a group, containing: Julian Edelman, James White, Gronk and Chris Hogan (leaving out Sony Michel).

Anyways, just an option. Thanks again, and if there any questions that I can clarify, please let me know.

**Comment by DimaKudosh** [comment]
In this case you can use `set_positions_for_same_team` rule.

**Comment by asardinha** [comment]
I have another example that may be applicable in this instance. 

In NHL, how would you go about ensuring that exactly or at a minimum of one player from a list of players with a salary greater than $5000 appear in all of my line ups. 

More specifically, if I have a list of 5 defensemen with a salary of $5000, how can I assure that all my lineups have at least one of these players. 

Let me know if there is anything I can provide. 

Thanks again.

**Comment by asardinha** [comment]
I have another example that may be applicable in this instance. 

In NHL, how would you go about ensuring that a group of players always appear in your lineups. 

For example if I have a group of defensemen from various teams with a salary greater than 5k. I would like all of my line ups to feature one (or more) of these players. 

Please let me know if I can send a csv or if there is anything I Can do to assist.
