### ISSUE TITLE
Android usage?

### ISSUE THREAD

**Issue by buddahb88** [DimaKudosh/pydfs-lineup-optimizer#74]
Has anyone tried to use this on their android device? I have it installed and even running to a point... it is getting stalled out on an OSError..  I'm hoping I can get some help on this as I love the desktop python 3 install that I use, just hoping to get a little more mobility!

Thanks for the great product! 
![qpython3-screenshot](https://user-images.githubusercontent.com/53489375/62150741-bddd9a00-b2cc-11e9-987e-ac37da99c9d7.png)

**Comment by DimaKudosh** [comment]
I think you have problem with precompiled version of CBC that doesn't work on android. Probably it'll work if you build it on your phone from source, but I'm not sure that it possible. If you want to run it from phone it will be better to write small web service for library and use this service.
