### ISSUE TITLE
Printing current exposure?

### ISSUE THREAD

**Issue by PatrickAllen1** [DimaKudosh/pydfs-lineup-optimizer#76]
Was wondering if there was a way to print player exposures?

**Comment by DimaKudosh** [comment]
Do you mean min/max exposures that should be set before optimization start?

**Comment by PatrickAllen1** [comment]
More specifically, after optimizing and i suppose it can be after exporting as well, would there be a command to count how many lineups each player appears in? Pretty new to Python so excuse the noobiness lol

**Comment by DimaKudosh** [comment]
Library doesn't provide this functionality, but you can easily write your own players counter:
```python
from collections import Counter
from itertools import chain

print(Counter(chain.from_iterable(lineups)))  # lineups is a list with all generated lineups
```
