### ISSUE TITLE
Team stack exposure

### ISSUE THREAD

**Issue by asardinha** [DimaKudosh/pydfs-lineup-optimizer#79]
Hi Dima,

I’m wondering if it would be possible to add a “stack exposure” setting while using the team stacks rule? I was thinking something similar to the player exposure rule or maybe the Lambda filtering for removing players. 

Essentially, say you want to “fade” a team as a stack but have the possibility of having players on those teams appear in your lineup. For example. Setting the stack exposure for BOS to 0, but still having a possibility of having players from BOS appear as “fillers.”

Please let me know if there is anything I can clarify. Thanks for all of your help.

**Comment by DimaKudosh** [comment]
I'll add it in next release
