### ISSUE TITLE
Can't get players

### ISSUE THREAD

**Issue by Enrql** [DimaKudosh/pydfs-lineup-optimizer#8]
Hi,

I can't get players with the 'optimizer.players', neither with the 'optimizer.get_player_by_name()'
What am I doing wrong?

Thanks for the help!

**Comment by DimaKudosh** [comment]
Hi, are you sure that you loaded players? Can you provide more info what you got when trying to call `optimizer.get_player_by_name()` or `optimizer.players`?

**Comment by OptimalZ06** [comment]
Hi Dima,

I'm also having some issues. It could be the formatting of my CSV file, but it imports without error. This is specifically for Yahoo football. Here's the CSV headers and an example row. Is 'Id' just something we come up with? Is it important that it match up with Yahoo's Player ID?


Id | First Name | Last Name | Position | Team | Salary | FPPG | Injury Status
-- | -- | -- | -- | -- | -- | -- | --
0 | Tom | Brady | QB | PAT | 12 | 2 | 0

Is this correct?

Here are the outputs for the two commands mentioned above.

>>> optimizer.players[0]
<pydfs_lineup_optimizer.player.Player object at 0x026C7070>

>>> optimizer.players[254]
<pydfs_lineup_optimizer.player.Player object at 0x03009E90>

>>> optimizer.get_player_by_name("Tom Brady")
<pydfs_lineup_optimizer.player.Player object at 0x03010B90>

Thanks!

**Comment by DimaKudosh** [comment]
Your csv has correct format and players are loaded. Maybe optimizer can't generate lineups because some other condition isn't fulfilled. For example you provide csv without defences or other positions that required for fantasy site. Can you send your csv to my email and I will look why it's happens?

**Comment by OptimalZ06** [comment]
Thanks. I've sent the spreadsheet over to you.

**Comment by DimaKudosh** [comment]
I answered to your email.

**Comment by mjester93** [comment]
Hi, I am also having trouble with loading players. Here is what mine csv file looks like:


Id | First Name | Last Name | Position | Team | Salary | FPPG
-- | -- | -- | -- | -- | -- | --
0 | Russell | Westbrook | PG | OKC | $11,100 | 74.87
1 | Giannis | Antetokounmpo | SF | MIL | $12,600 | 66.19

When I try to run optimizer.load_players_from_CSV("filepath\players.csv"), I get the following error
`File "<stdin>", line 1
SyntaxError: (unicode error) 'unicode escape' codec can't decode bytes in position 2-3: truncated \UXXXXXXX escape`

Do you know what is causing this?

**Comment by ltd9938** [comment]
Was this ever fixed? Having the same issue.

**Comment by jayna456** [comment]
@DimaKudosh , I am facing same issue. I am using load_players() and passing array of objects. but getting this

`<generator object LineupOptimizer.optimize at 0x0000023F50241748>`

Please help me out..
