### ISSUE TITLE
Min # of teams = 3 for FD?

### ISSUE THREAD

**Issue by elitwilliams** [DimaKudosh/pydfs-lineup-optimizer#82]
Dima - one general rule for FanDuel is there should be at least 3 teams represented in each lineup, but I don't see that as a setting or rule option. From https://www.fanduel.com/rules under Lineup Restrictions,

> "For most contests, you must pick players from at least three different teams and you may not pick more than four players from the same team. However, for MLB contests, you may select up to five players from the same team, provided one player is a pitcher. For single game contests, you must pick players from at least two different teams."

Has this been addressed already?

**Comment by elitwilliams** [comment]
For most sports this naturally works itself out since max players from one team = 4 and # players per lineup = 9, but for MLB since you can have 5 players per team it becomes an issue. E.g. in MLB you can create a team with 5 players from one team and 4 from another, violating the # of teams >= 3 constraint, whereas in other sports you are constrained to maximum of 4-4-1, which by default satisfies constraint.

**Comment by DimaKudosh** [comment]
Hi, yes I missed this restriction for FD. I'll fix it in next release.
