### ISSUE TITLE
NFL Single game

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#86]
Does this support NFL single game for fanduel

**Comment by DimaKudosh** [comment]
Hi, this library doesn't support NFL single game for fanduel. I think it will be easy to add it, because it's like DK showdown that already implemented.  I'm not playing in fanduel, so it will be fine if you attach exported csv for this type of contests, so I can look how FD represents players in this contests.

**Comment by Denwen12** [comment]
Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Dima Kudosh <notifications@github.com> Date: 9/5/19  1:56 PM  (GMT-05:00) To: DimaKudosh/pydfs-lineup-optimizer <pydfs-lineup-optimizer@noreply.github.com> Cc: Denwen12 <joffen12@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DimaKudosh/pydfs-lineup-optimizer] NFL Single game (#86) Hi, this library doesn't support NFL single game for fanduel. I think it will be easy to add it, because it's like DK showdown that already implemented.  I'm not playing in fanduel, so it will be fine if you attach exported csv for this type of contests, so I can look how FD represents players in this contests.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DimaKudosh/pydfs-lineup-optimizer/issues/86?email_source=notifications\u0026email_token=ANBWO7X4IF5FZRCW4XGSRGLQIFB3JA5CNFSM4IUAPOX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6AEXUA#issuecomment-528501712",
"url": "https://github.com/DimaKudosh/pydfs-lineup-optimizer/issues/86?email_source=notifications\u0026email_token=ANBWO7X4IF5FZRCW4XGSRGLQIFB3JA5CNFSM4IUAPOX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6AEXUA#issuecomment-528501712",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Denwen12** [comment]
here we go

[FanDuel-NFL-2019-09-05-37436-lineup-upload-template.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/3580734/FanDuel-NFL-2019-09-05-37436-lineup-upload-template.zip)

**Comment by DimaKudosh** [comment]
I've added FD Single Game for football. Changes in develop branch, so you can reinstall library from develop and give your feedback before I release new version. For using this feature you should init optimizer like this: `optimizer = get_optimizer(Site.FANDUEL_SINGLE_GAME, Sport.FOOTBALL)`

**Comment by Denwen12** [comment]
fantastic I'll try it

**Comment by jamesmosier** [comment]
Looks like it works well! I just tested it out for tonight's MNF game and the output seemed good.

**Comment by gimann421** [comment]
When will this feature be added? Slash I am new to github can someone tell me how to install a version with this feature?
