### ISSUE TITLE
CPT Max Exposure

### ISSUE THREAD

**Issue by austinjohnson** [DimaKudosh/pydfs-lineup-optimizer#90]
For single game mode specifically NFL captain mode on DK - is there a way to limit exposure just for the cpt position for each player? For example, on Thursday night if I want Cam Newton’s max exposure for just the cpt position to 0.4% and his max exposure for all my lineups can be whatever is optimal - how would I do that?

**Comment by DimaKudosh** [comment]
If you want to set same max exposure for all captains you can add this code before optimizer start:
```python
for player in optimizer.players:
    if 'CPT' in player.positions:
        player.max_exposure = 0.4
```

**Comment by austinjohnson** [comment]
But is there a way to set it individually for each player? Because I wanted to do something like Cam Newton 0.4%, Jameis Winston 0.3%, etc...

**Comment by DimaKudosh** [comment]
Yes, off course. You have 2 ways how to do this. The first is to add additional column to imported csv named `Max Exposure` and set exposure values for interested players. For this type of contest players represented as 2 rows in csv: one for util and another one for captain. Also you can do it from code, like this:
```python
captain_exposures = {
    'Cam Newton': 0.4,
    'Jamies Winston': 0.3,
    # etc
}
for player_name, max_exposure in captain_exposures.items():
    for player in optimizer.find_players(player_name):
        if 'CPT' in player.positions:
            player.max_exposure = max_exposure
            break
```

**Comment by austinjohnson** [comment]
Is there also a way to specify deviation for each position? For example, QBs are less volatile than WR and would therefore require less deviation when adding randomness to projections.

**Comment by austinjohnson** [comment]
Or is there a way I could add a column in excel to set each individual player’s deviation. That would be ideal.

**Comment by DimaKudosh** [comment]
No, there is no way to specify different deviation for players

**Comment by DimaKudosh** [comment]
I've added player specific deviation, Player object has 2 new fields: `min_deviation` and `max_deviation`
