### ISSUE TITLE
ownership

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#91]
how can I use ownership percentage to build my lineups

**Comment by Denwen12** [comment]
also how do I tell the optimizer to continuously make lineups till it runs out of optimizing

**Comment by utahman** [comment]
Set a million lineups. Eventually it will stop with exception (which you need to catch).

**Comment by Denwen12** [comment]
next, how do I add the exposures in the import filw

**Comment by DimaKudosh** [comment]
You can add additional columns to import file. For exposure columns names should be `Min Exposure`/`Max Exposure`, for ownership - `Projected Ownership`

**Comment by Denwen12** [comment]
do I use any more commands in python to use the projected ownership columns

**Comment by DimaKudosh** [comment]
Yes you also need to set ownership range in optimzer: `optimizer.set_projected_ownership(min_projected_ownership=0.4, max_projected_ownership=0.7)`
[Here](https://pydfs-lineup-optimizer.readthedocs.io/en/latest/rules.html#ownership-projections-constraint) you can find docs for this.
