### ISSUE TITLE
Restricting Opposing Team For Pitchers

### ISSUE THREAD

**Issue by geoffstrong55** [DimaKudosh/pydfs-lineup-optimizer#96]
Hello, 

I am trying to use the optimize.restrict_positions_for_opposing_team function MLB with the draft kings CSV.  

This is my code so far:
`for lineup in optimizer.optimize(n=20, randomness=True, max_exposure=0.3):
    optimizer.restrict_positions_for_opposing_team(['P'], ['1B', '2B', '3B', 'C', 'SS', 'OF'])
    optimizer.set_team_stacking([3, 3], for_positions=['1B', '2B', '3B', 'C', 'SS', 'OF'])
    print(lineup)
    print(lineup.players)  # list of players
    print(lineup.fantasy_points_projection)
    print(lineup.salary_costs)`

 However, I continue to get this error:
`---------------------------------------------------------------------------
LineupOptimizerException                  Traceback (most recent call last)
<ipython-input-34-6493dac54702> in <module>()
      1 #create conditions for optimzier and then print rosters
      2 for lineup in optimizer.optimize(n=20, randomness=True, max_exposure=0.3):
----> 3     optimizer.restrict_positions_for_opposing_team(['P'], ['1B', '2B', '3B', 'C', 'SS', 'OF'])
      4     optimizer.set_team_stacking([3, 3], for_positions=['1B', '2B', '3B', 'C', 'SS', 'OF'])
      5     print(lineup)

~\Anaconda3\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py in restrict_positions_for_opposing_team(self, first_team_positions, second_team_positions)
    381         # type: (List[str], List[str]) -> None
    382         if not self.games:
--> 383             raise LineupOptimizerException('Game Info isn\'t specified for players')
    384         self._opposing_teams_position_restriction = (first_team_positions, second_team_positions)
    385         self.add_new_rule(RestrictPositionsForOpposingTeams)

LineupOptimizerException: Game Info isn't specified for players`
The Game Info column from the original draft kings CSV is in the file but it still does not work. Should I be changing the format of the Game Info column before loading the CSV into my script?

Thank you for help,
Geoff

**Comment by DimaKudosh** [comment]
Hi,
Where did you get this csv? I just downloaded csv for today contest and it works fine.
It's problem that we need to know information about game for `restrict_positions_for_opposing_team` rule, but this information wasn't parsed from your file.

**Comment by geoffstrong55** [comment]
Thank you for response!

I just figured out the problem I was experiencing. I downloaded the CSV file from the draft kings website for today's contest. I then added my projections to file using R. When I then saved the file again, R changed the formatting of the column names. 

After making these changes, it then worked for me. Sorry for any inconvience.
