### ISSUE TITLE
creating player object for DST in NFL

### ISSUE THREAD

**Issue by tanner-ducharme** [DimaKudosh/pydfs-lineup-optimizer#97]
How do we set first_name and last_name when creating a Player() object for a DST?

**Comment by DimaKudosh** [comment]
Player constructor takes first_name and last_name parameters, you can use them

**Comment by sansbacon** [comment]
So edit your csv file to change it from "Patriots" to "Patriots DST"
or if you are creating player objects directly, set first_name = 'Patriots' and last_name = 'DST'

**Comment by sansbacon** [comment]
I think you can close this.
