### ISSUE TITLE
Same Team-Same Position

### ISSUE THREAD

**Issue by brente33** [DimaKudosh/pydfs-lineup-optimizer#98]
Is there a way to exclude players from the same team/position from the same lineup? For instance, I don't want both Melvin Gordon and Austin Ekeler as my RB's this week. Also applies to the NE RB's, I only ever just want one of them.

**Comment by sansbacon** [comment]
This is a low-probability scenario and probably doesn't merit its own constraint. My recommendation is to just generate additional lineups and then filter for this condition in your code.

```
want_number_of_lineups = 20
lineups = []

while len(lineups) < want_number_of_lineups:
    for lineup in optimizer.optimize(1, randomize=True):
        # pseudocode
        if count of position from same team > threshold:
            pass
        lineups.append(lineup)

```

**Comment by DimaKudosh** [comment]
I've added this feature in new release, it's example of using new rule: `optimizer.restrict_positions_for_same_team(('RB', 'RB'))`
